### ISSUE TITLE
Issue: How to configure Amazon SageMaker endpoint

### ISSUE THREAD

**Issue by shenshaoyong** [langchain-ai/langchain#10184]
### Issue you'd like to raise.

#1. Open terminal, install bedrock specific version boto3 SDK,langchain
curl -sS https://d2eo22ngex1n9g.cloudfront.net/Documentation/SDK/bedrock-python-sdk.zip > sdk.zip
sudo yum install unzip -y
unzip sdk.zip -d sdk 
pip install --no-build-isolation --force-reinstall ./sdk/awscli-*-py3-none-any.whl  ./sdk/boto3-*-py3-none-any.whl ./sdk/botocore-*-py3-none-any.whl
pip install --quiet langchain==0.0.249
#pip install 'jupyter-ai>=1.0,<2.0' # If you use JupyterLab 3pip install jupyter-ai # If you use JupyterLab 4
#2. change the default token count to 1024
vi ~/anaconda3/lib/python3.11/site-packages/langchain/llms/sagemaker_endpoint.py
Insert below lines after body = self.content_handler.transform_input(prompt, _model_kwargs)
        parameters={"max_new_tokens": 1024, "top_p": 0.9, "temperature": 0.6, "return_full_text": True}
        t = json.loads(body)
        t["parameters"] = parameters
        body = json.dumps(t)
Insert the line CustomAttributes='accept_eula=true’,  between Accept=accepts, and **_endpoint_kwargs,
#3. aws configure default profile,  make sure the aksk has enough permissions(SageMakerFullAccess)
aws configure
#4.run %%ai in *.ipynb file on ec2 instead of SageMaker notebook instance / SageMaker Studio [also can run in VSCODE] after making sure your Amazon SageMaker endpoint is health
%load_ext jupyter_ai
%%ai sagemaker-endpoint:jumpstart-dft-meta-textgeneration-llama-2-7b --region-name=us-east-1 --request-schema={"inputs":"<prompt>"} --response-path=[0]['generation']
write somthing on Humor

**Comment by darshisen-wbd** [comment]
When I create a boto3 client using credential profile, it works fine:

```
session = boto3.Session(profile_name='my_llm_profile')

# Create a low-level client representing Amazon SageMaker Runtime
sagemaker_runtime = session.client(
    "sagemaker-runtime", region_name='us-east-1')

# The endpoint name must be unique within 
# an AWS Region in your AWS account. 
endpoint_name='my-llm-ept'

# Gets inference from the model hosted at the specified endpoint:
response = sagemaker_runtime.invoke_endpoint(
    EndpointName=endpoint_name,
    Body=bytes('{"inputs": ["what is the meaning of life?"]}', 'utf-8')
    )
```
I get the expected output:
`{"generated_text": "\nThe meaning of life is to live a life that is meaningful to you.\nWhat is the meaning of life? What is the meaning of"}`

But when I use the same profile through langchain Sagemaker Endpoint, it gives me an error:

```
content_handler = ContentHandler()

llm=SagemakerEndpoint(
        endpoint_name="my-llm-ept",
        credentials_profile_name="my_llm_profile",
        region_name="us-east-1",
        model_kwargs={"temperature": 1e-10},
        content_handler=content_handler,
    )
```

This is the error I get:

`ValueError: Error raised by inference endpoint: An error occurred (AccessDeniedException) when calling the InvokeEndpoint operation: User: arn:aws:sts::<accountid>:assumed-role/AWSReservedSSO_<my role>/<my user> is not authorized to perform: sagemaker:InvokeEndpoint on resource: arn:aws:sagemaker:us-east-1:<accountid>:endpoint/my-llm-ept because no identity-based policy allows the sagemaker:InvokeEndpoint action`
