### ISSUE TITLE
What is the difference between Pandas Data frame agent, CSV agent and SQL Agent?

### ISSUE THREAD

**Issue by Kuramdasu-ujwala-devi** [langchain-ai/langchain#10223]
### Issue you'd like to raise.

What is the difference between Pandas Data frame agent, CSV agent and SQL Agent?
Can you brief each and when to use ?

**Comment by Kuramdasu-ujwala-devi** [comment]
@dosu-bot.
Then earlier version of langchain has SQLDatabaseChain in chains , now I couldn't fine the SQLChain is it now not supported .
So in order to interact with the sql data base and get the sql query from the natural language passed by the user. What approach I have to follow here .

**Comment by tianyinhuang** [comment]
Base on my not-so-much testing experience, Pandas agents fits better on situations that needs data (pre-)processing, like a data analyst; SQL agent like a database engineer. 
Saw applications using SQL agent -> Pandas agent. I'm trying not to complicated the whole flow, otherwise takes long time to get the final output.
