### ISSUE TITLE
Own Api LLM

### ISSUE THREAD

**Issue by brightebyte** [langchain-ai/langchain#10359]
### Feature request

The Project [Basaran](https://github.com/hyperonym/basaran) lets you host an api that is similar to the OpenAI api, but with a self hosted llm. Support for such custom API LLMs would be great

### Motivation

Further democritizig LLMs

### Your contribution

I could test it

**Comment by joshuasundance-swca** [comment]
Basaran is designed so that you can use the `openai` Python library with a different the base url. See their example [here](https://github.com/hyperonym/basaran/blob/master/examples/openai-python-library/main.py). This should make it easy to use Basaran in LangChain.

I was able to call a local Basaran server by setting environment variables `OPENAI_API_BASE` and `OPENAI_API_KEY` before creating a `langchain.llms.openai.OpenAI` object, or by passing those values in as keyword arguments. You could also set `model_name`.

I tested using 0.19.0 because 0.21.1 [seems to have a breaking change](https://github.com/hyperonym/basaran/issues/253).

`docker run -p 80:80 -e MODEL=bigscience/bloomz-560m hyperonym/basaran:0.19.0`

```python
>>> import langchain
>>> # 172.27.0.3 is the IP of the basaran server on my docker network
>>> llm = langchain.llms.openai.OpenAI(
...     openai_api_base='http://172.28.0.3/v1',
...     openai_api_key='this_value_does_not_matter',
...     model_name='bigscience/bloomz-560m',
... )
>>> llm.openai_api_base, llm.openai_api_key, llm.model_name
('http://172.28.0.3/v1', 'this_value_does_not_matter', 'bigscience/bloomz-560m')
>>> llm('Large language models can be used to')
' generate a wealth of data'
>>>
```

If you wanted to, you could probably create a Basaran LLM class similar to how `ChatAnyscale` was implemented. See the API reference [here](https://api.python.langchain.com/en/latest/chat_models/langchain.chat_models.anyscale.ChatAnyscale.html) and the source code [here](https://api.python.langchain.com/en/latest/_modules/langchain/chat_models/anyscale.html#ChatAnyscale). 

According to Basaran's README, it looks like implementing chat models [may be more difficult](https://github.com/hyperonym/basaran#chat).
