### ISSUE TITLE
Summarize agent_scratchpad when it exceeds n tokens

### ISSUE THREAD

**Issue by mdziezyc** [langchain-ai/langchain#10446]
### Feature request

Similarly to `memory=ConversationSummaryBufferMemory(llm=llm, max_token_limit=n)` passed in `initialize_agent`, there should be a possibility to pass `ConversationSummaryBufferMemory` like-object which would summarize the `intermediate_steps` in the agent if the `agent_scratchpad` created from the `intermediate_steps`  exceeds `n` tokens

### Motivation

Agents can run out of the context window when solving a complex problem with tools.

### Your contribution

I can't commit to anything for now.

**Comment by rhamnett** [comment]
Did you solve this? I am looking to solve the same issue when the agent loops and continues to pull extra documents from the vector store. I think what needs to happen is the scratchpad almost needs to be run through a document compressor? Thoughts?

**Comment by mdziezyc** [comment]
Hi! I have not developed a solution. For now, I just moved on to other things.

I saw that there is a `intermediate_steps` variable in `/langchain/agents/agent.py:1029` which is than changed to the text `agent_scratchpad`. IMHO the solution is either to compress `intermediate_steps` or the resulting `agent_scratchpad`. TBH I hoped for any input from dosu bot.

I'd suggest that anyone who is interested in this feature should "up vote" the issue - maybe we will be able to gain some momentum. :)

**Comment by rhamnett** [comment]
I had the same thought, I will try and work on compressing the agent_scratchpad inside the loop and let you know if I have any success.

**Comment by obujacz** [comment]
@dosu-bot thank you for answer. However, my understanding of the problem is a little bit different. I would like to summarize `agent_scratchpad` created from `intermediate_steps` within one prompt from the user, so that complex problem can be solved.
Your solution adds content of the `agent_scratchpad` to the memory of the entire conversation, this not a desired behavior. Could you adjust your reponse?

**Comment by mdziezyc** [comment]
I have to be the one to ask dosu bot :) 

@dosu-bot thank you for answer. However, my understanding of the problem is a little bit different. I would like to summarize `agent_scratchpad` created from `intermediate_steps` within one prompt from the user, so that complex problem can be solved.
Your solution adds content of the `agent_scratchpad` to the memory of the entire conversation, this not a desired behavior. Could you adjust your reponse?

**Comment by rhamnett** [comment]
At least we know where to start looking now, I wouldn't be using 'sumy' but an extra call to the existing given LLM. I haven't had time to progress this personally.

**Comment by Jasonthefirst** [comment]
Did someone achieve this? I am trying to retreive mails but as soon as I request more than two the agent stops because the token length is exceeded. If I could summarize the scratchpad this wouldn't happen. I tried to adapt the toolkit I used and add an additional chain for summarization after the retreive step of on tool but fail to add the chain as an intermediate step so summarizing the scratchpad would work as well I think.

**Comment by rhamnett** [comment]
This should definitely not be closed. There is still no way to easily achieve this in the libaray and is a major blocker

**Comment by SpBills** [comment]
Agreed. Major blocker.

**Comment by zunairazaman** [comment]
@mdziezyc  did you find a proper solution to this issue?
