### ISSUE TITLE
RetrievalQA custom prompt to accept prompts other than context and question e.g. language for use in Sequential Chain

### ISSUE THREAD

**Issue by PeterWelchWork** [langchain-ai/langchain#10557]
### Feature request

Update RetrievalQA chain so that custom prompts can accept parameters other than input_documents and question. 
Current functionality is limited by call to StuffDocumentsChain:

answer = self.combine_documents_chain.run(
    input_documents=docs, question=question, callbacks=_run_manager.get_child()
)

Any additional parameters required aren't passed, including chat history.

2 line code update required:

inputs['input_documents'] = docs
answer = self.combine_documents_chain.run(
  inputs, callbacks=_run_manager.get_child()
)

### Motivation

Improve flexibility of the RetrievalQA chain enabling system message to be customised, chat history to be passed so GPT can reference back to previous answers. Customise language in answer in QA chain etc. 

### Your contribution

Will submit PR with above change in-line with contributing guidelines.

**Comment by tedsecretsource** [comment]
I _sort of_ got this to work (but not really, see below) using this code:

```python
db = PGVector(
    embedding_function=self.embedding,
    collection_name="MY_FANCY_COLLECTION",
    connection_string=os.environ["DATABASE_URL"]
)
search_results = db.similarity_search(self.text, k=4)
logging.debug("Search results: %s", search_results)
llm = ChatOpenAI(model_name=self.llm_name, temperature=0)
qa_chain = RetrievalQA.from_llm(
    llm,
    retriever=db.as_retriever(),
    prompt=hub.pull("secretsourceorg/my-system-prompt")
)        
result = qa_chain({"query": self.text})
```

I say "sort of" because this is being processed as a HUMAN role and not as a SYSTEM role, which is what I think you are looking for. At this time, I think, if you want to be able to do that you'll need to write your own retrieval_qa chain (but it shouldn't be too hard if you can read the source for the RetrievalQA class).

Do note, your prompt needs to include the `{context}` and `{question}` placeholders [just like the sample](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/retrieval_qa/prompt.py)

HTH
