### ISSUE TITLE
When I use a prompt with "{", I get an error

### ISSUE THREAD

**Issue by llmnb112** [langchain-ai/langchain#10639]
### Issue you'd like to raise.

Error message:
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PromptTemplate
__root__
  Format specifier missing precision (type=value_error)

My prompt looks like this:
I want you to generate results in json format like :{"key1":... , "key2":.... , "key3":... ,... }

**Comment by joshuasundance-swca** [comment]
Instead of putting those instructions directly in the prompt, consider using something like a [`PydanticOutputParser`](https://python.langchain.com/docs/modules/model_io/output_parsers/pydantic). This allows you to use a partial variable in the prompt, which is filled with output formatting instructions:

```python
prompt = PromptTemplate(
    template="Answer the user query.\n{format_instructions}\n{query}\n",
    input_variables=["query"],
    partial_variables={"format_instructions": parser.get_format_instructions()},
)
```

You may also consider using function calling to get good structured output, especially if you're using OpenAI:
* https://python.langchain.com/docs/modules/agents/agent_types/openai_functions_agent
* https://python.langchain.com/docs/modules/chains/how_to/openai_functions

**Comment by llmnb112** [comment]
Thanks, I made it by using double curly braces.

**Comment by kat-dearstyne** [comment]
I realize there are work arounds here, but I am confused why langchain doesn't use a smarter why to detect format variables?? For example, a simple regex expression such as re.findall(r'\{(\w*)\}', string) would detect all normal format variables such as {var} without incorrectly identifying json as an input variable
