### ISSUE TITLE
Issue: Remove "AI:" and "Human:" prefixes in memory history

### ISSUE THREAD

**Issue by AdrialfB** [langchain-ai/langchain#10630]
### Issue you'd like to raise.

Hi,
I am trying to make a chatbot with a LLM based on LLaMa2.
When I use the memory (ConversationBufferWindowMemory), it creates a default prompt like:
"""
    Human: input
    AI: output
    Human: input
"""
However, with LLaMa2 I need to create a prompt like:
"""
    [INST] {input} [/INST]
    {output}
    [INST] {input} [/INST]
"""
I discovered that I can change the "Human" and "AI" prefixes, but I can’t delete the ":", so I am getting:
"""
    : [INST] {input} [/INST]
    : {output}
    : [INST] {input} [/INST]
"""
Is there any way I can modify the whole prefix?
Thanks

**Comment by codeananda** [comment]
@dosu-bot it is helpful that we need to know what to change... but this means we have to fork langchain in order to use it properly. 

Open-source models have been trained using different prompt formats. We cannot fully utilise these models if we pass incorrectly formatted prompts. 

It would be great if Langchain had a way to automatically format prompts for each open source model.

An example of how to properly format prompts for Alpaca and Llama2 can be found [here](https://github.com/oobabooga/text-generation-webui/wiki/01-%E2%80%90-Chat-Tab#mode)

If a model is downloaded from HuggingFace Hub, for instance, there is usually info about the prompt format in `models/config.yaml`. Is there a way for Langchain to check this?

**Comment by codeananda** [comment]
@AdrialfB did you find a way to solve this problem? Or just accepted that the prompt won't be formatted properly?

**Comment by AdrialfB** [comment]
@codeananda No, I stopped working on it and I assumed prompt will be incorrectly formatted. I just parse the output to delete the ":" and " " characters the model outputs because of this. It is not the best solution, but as it is for personal use, I am ok with it.
