### ISSUE TITLE
SQLAgent fails to connect to Postgres multiple schemas

### ISSUE THREAD

**Issue by andywl** [langchain-ai/langchain#10811]
### System Info

I'm using latest langchain version 0.0.295.  It turns out langchain SQLAgent always connects to Postgres public schema.  I need SQLAgent to check all schemas to generate SQL query.  How to configure SQLAgent to connect to all Postgres schemas?

Tried both pg_uri = f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{mydatabase}?currentSchema=myschema",  pg_uri = f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{mydatabase}?search_path=myschema" when creating SQLDatabase: db = SQLDatabase.from_uri(pg_uri).  It doesn't work. 
 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

When creating SQLDatabase for postgres, I can't specify schema.  It only connects to postgres public schema.  As a result, SQLAgent doesn't produce meaningful result.

# pg_uri = f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{mydatabase}?search_path=myschema"
pg_uri = f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{mydatabase}?currentSchema=myschema"

db = SQLDatabase.from_uri(pg_uri)

### Expected behavior

Expect SQLAgent or SQLDatabase can configure schemas for Postgres so that SQLAgent can generate meaningful SQL query.

**Comment by anurag9099** [comment]
@andywl @dosu-bot Above solution does work! Thank you for the temporary resolution, hope this will be fixed in the upcoming release.
I want to highlight one more point in the _populate_all_tables method, in 'postgresSQL' dialect _table_schema_ _= 'public'_ is static and it does not resolve the problem of connecting the default public schema.
Hence, I have replaced it with this __table_schema_ = self.__schema_
And initializing the DB with _schema_ parameter:
_db = SQLDatabase.from_uri(pg_uri, schema=<schema_name>)_
