### ISSUE TITLE
ValueError Regarding Required Metadata Variables When Using RedisVectorStoreRetrieverWithScores

### ISSUE THREAD

**Issue by gorkanauta** [langchain-ai/langchain#11062]
### System Info

LangChain version: **0.0.301**
**Python 3.9.6**
System Version: **macOS 13.5.2 (22G91)**
Kernel Version: **Darwin 22.6.0**

### Who can help?

@hwchase17 @agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I encountered a ValueError when using a custom Redis retriever (RedisVectorStoreRetrieverWithScores) with the SemanticDocumentSearch component in langchain. Below is the code snippet that reproduces the error:

```python
from langchain.vectorstores.redis.base import Redis, RedisVectorStoreRetriever
from langchain.chains import SemanticDocumentSearch
from langchain.schema import Document
from typing import List

class RedisVectorStoreRetrieverWithScores(RedisVectorStoreRetriever):
    def get_relevant_documents(self, query: str) -> List[Document]:
        docs_and_scores = self.vectorstore.similarity_search_with_score(query, k=self.search_kwargs["k"])
        for doc, score in docs_and_scores:
            doc.metadata = {**doc.metadata, **{"score": score}}
        return [doc for (doc, _) in docs_and_scores]

# Assuming initialization of redis_vector_store with necessary parameters
redis_retriever = RedisVectorStoreRetrieverWithScores(redis_vector_store)
semantic_search = SemanticDocumentSearch(retriever=redis_retriever)

# Error occurs when calling the following method
answer = semantic_search.get_answer("How are you?")

``` 
Error:

```python
Traceback (most recent call last):
  ...
ValueError: Document prompt requires documents to have metadata variables: ['source']. Received document with missing metadata: ['source'].

``` 

1. Implement a custom Redis retriever class RedisVectorStoreRetrieverWithScores inheriting from RedisVectorStoreRetriever.
2. Instantiate SemanticDocumentSearch with the custom Redis retriever.
3. Call the get_answer method of the SemanticDocumentSearch instance.

### Expected behavior

I expected the get_answer method to execute without errors and return a relevant answer based on the input query. However, a ValueError is thrown indicating a missing source metadata variable in the Document objects.

I am kindly seeking guidance on how to resolve this issue, and I am very thankful for any assistance or pointers provided. Thank you in advance for your time and help! 😊

**Comment by FrancescoSaverioZuppichini** [comment]
> _🤖_
> 
> Hello,
> 
> Thank you for reaching out and providing a detailed description of the issue you're facing.
> 
> The error message you're seeing is indicating that the `Document` objects returned by your `RedisVectorStoreRetrieverWithScores` retriever are missing the `source` key in their `metadata` attribute. The `SemanticDocumentSearch` component in LangChain expects this key to be present in the `metadata` of each `Document` object it processes.
> 
> To resolve this issue, you should ensure that each `Document` object returned by your `get_relevant_documents` method includes a `source` key in its `metadata`. Here's how you can modify your `get_relevant_documents` method to include a `source` key:
> 
> ```python
> class RedisVectorStoreRetrieverWithScores(RedisVectorStoreRetriever):
>     def get_relevant_documents(self, query: str) -> List[Document]:
>         docs_and_scores = self.vectorstore.similarity_search_with_score(query, k=self.search_kwargs["k"])
>         for doc, score in docs_and_scores:
>             doc.metadata = {**doc.metadata, **{"score": score, "source": "your_source"}}
>         return [doc for (doc, _) in docs_and_scores]
> ```
> 
> In the above code, replace `"your_source"` with the actual source of your documents. If the source varies for each document, you'll need to adjust the code to set the correct source for each document.
> 
> Please note that the `source` key in the `metadata` is just an example. The `SemanticDocumentSearch` component may require other keys to be present in the `metadata` depending on its configuration. You should adjust the `metadata` of your `Document` objects to include all the keys required by your specific configuration of the `SemanticDocumentSearch` component.
> 
> I hope this helps! Let me know if you have any other questions or if there's anything else I can do to assist you.
> 
> Best regards, Dosu
> 
> ## Sources
> * [libs/langchain/langchain/vectorstores/redis/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/redis/base.py)
> * [libs/langchain/langchain/schema/document.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/schema/document.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

The `source` is already present in the stored metadata in redis

**Comment by Spartee** [comment]
Hi @FrancescoSaverioZuppichini, can you please show how you're initializing the ``redis_vector_store`` variable? If you're initializing from an existing index you likely need to pass in a schema correlating to the metadata you want to be using. 

This extra step enables the implementation to take advantage of filtered(hybrid) queries with metadata. It's eventually going to be automatically populated from the index information within Redis, but for now it's passed in. This was changed fairly recently.

Happy to help you with this

**Comment by tylerhutcherson** [comment]
We are investigating further and will work on a solution to address this. Thanks for your patience!

**Comment by Spartee** [comment]
This is not as well documented nor easy as it should be. Unfortunately it requires a server side change in Redis to be able to accomplish (returning all metadata field parameters from FT.INFO in order to reconstruct the index perfectly). We decided to implement the "manual" approach for the time being as we thought overt errors were better than silent ones and we needed the metadata capability for customers who asked for it in langchain. Despite this you've found a silent error mode which is using the ``Redis`` initializer after creating an existing index instead of ``from_existing_index``, ``from_documents``, ``from_texts``, etc.

Here's whats happening right now

I've created a test script to demonstrate this. It's obviously not a real QnA example, but I've included the entire script so you can try it yourself.


### Working example with ``from_texts``

This is likely what you do first.

```python
import os
from typing import List, Tuple


from langchain.chains import RetrievalQA
from langchain.embeddings import OpenAIEmbeddings
from langchain.llms import OpenAI
from langchain.llms.base import LLM
from langchain.prompts import PromptTemplate
from langchain.vectorstores.redis import Redis

import openai
openai.api_key = os.environ["OPENAI_API_KEY"]

EMBEDDINGS = OpenAIEmbeddings()
TEXTS = [
    "foo", "bar", "baz"
]
METADATAS = [
    {"title": "foo", "links": "foo.com"},
    {"title": "bar", "links": "bar.com"},
    {"title": "baz", "links": "baz.com"},
]


def make_qna_chain(retriever: Redis):
    """Create the QA chain."""

    # Define our prompt
    prompt_template = """Use the following pieces of context to answer the question at the end. If you don't know the answer, say that you don't know, don't try to make up an answer.

    This should be in the following format:

    Question: [question here]
    Answer: [answer here]

    Begin!

    Context:
    ---------
    {context}
    ---------
    Question: {question}
    Answer:"""

    prompt = PromptTemplate(
        template=prompt_template, input_variables=["context", "question"]
    )


    # Create retreival QnA Chain
    chain = RetrievalQA.from_chain_type(
        llm=OpenAI(model_name="text-davinci-003"),
        chain_type="stuff",
        retriever=retriever,
        return_source_documents=True,
        chain_type_kwargs={"prompt": prompt},
    )
    return chain


if __name__ == "__main__":
    import yaml
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--content_query", type=str, default="bar")
    parser.add_argument("--num_results", type=int, default=2)
    parser.add_argument("--redis_url", type=str, default="redis://localhost:6379")
    args = parser.parse_args()


    # will work, documents create schema
    vector_db = Redis.from_texts(
        TEXTS,
        EMBEDDINGS,
        metadatas=METADATAS,
        redis_url=args.redis_url,
        index_name="simple",
        #index_schema=schema # no schema specified so schema will be generated
    )
    print(yaml.dump(vector_db.schema))
    retriever = vector_db.as_retriever(
        search_kwargs={"k": args.num_results, "distance_threshold": 0.3},
        search_type="similarity_distance_threshold"
    )
    chain = make_qna_chain(retriever)
    result = chain({"query": args.content_query})
    print(result["result"])
    for doc in result["source_documents"]:
        print(doc.metadata["title"])
        print(doc.metadata["links"])
```

### What causes your error

So if I've created this index, and I'm just instantiating ``Redis`` again, to obtain the metadata, I need to pass in the schema generated for that metadata as the comment in the code above suggests. 

This will silently Error until you get to the metadata access in the bottom loop
```python
    # Existing index, no schema, won't return metadata, causes your error
    vector_db = Redis(
        args.redis_url,
        index_name="simple",
        embedding=EMBEDDINGS,
        )
    retriever = vector_db.as_retriever(
        search_kwargs={"k": args.num_results, "distance_threshold": 0.3},
        search_type="similarity_distance_threshold"
    )
    chain = make_qna_chain(retriever)
    result = chain({"query": args.content_query})
    print(result["result"])
    for doc in result["source_documents"]:
        print(doc.metadata["title"])
        print(doc.metadata["links"])

```

This was uncaught (apologies) by me as I assumed ``from_existing_index`` would be used which requires the ``schema`` argument. This, or the class methods ``from_texts``, ``from_documents``, ``from_texts_return_keys`` would be used with samples of the same texts/metadata or ``Documents``. I'll outline this below.


## Fixing your error

Ok so how do you address it?

### Option 1: Use ``from_existing_index`` and pass schema in yaml or dict

 For connecting to an existing redis db without creating any new documents you can also just use the
``from_existing_index`` method requires schema to be passed for the whole index. The generated index schema is easily obtained with the ``Redis.schema``. 

```python
vector_db.write_schema("simple-schema.yaml")
```

which for the above example will write a file with

```yaml
text:
- name: title
  no_index: false
  no_stem: false
  sortable: false
  weight: 1
  withsuffixtrie: false
- name: links
  no_index: false
  no_stem: false
  sortable: false
  weight: 1
  withsuffixtrie: false
- name: content
  no_index: false
  no_stem: false
  sortable: false
  weight: 1
  withsuffixtrie: false
vector:
- algorithm: FLAT
  block_size: 1000
  datatype: FLOAT32
  dims: 1536
  distance_metric: COSINE
  name: content_vector
```

You can pass it back in as a yaml file or dict like follows

```python
    existing_index = Redis.from_existing_index(
        EMBEDDINGS,
        redis_url=args.redis_url,
        index_name="simple",
        schema="./simple-schema.yaml",
    )
    print(yaml.dump(existing_index.schema))
    retriever = existing_index.as_retriever(
        search_kwargs={"k": args.num_results, "distance_threshold": 0.3},
        search_type="similarity_distance_threshold"
    )
    chain = make_qna_chain(retriever)
    result = chain({"query": args.content_query})
    print(result["result"])
    for doc in result["source_documents"]:
        print(doc.metadata["title"])
        print(doc.metadata["links"])

```


### Option 2: Use the ``Redis`` init only pass index (metadata) schema

Since the metadata you seem to be passing is text (hence ``str``) these will be indexed as text fields into redis which will allow for filtered text + vector search. so we list them as text here.

```python
    # Existing Index, schema defined, will work.
    schema = {
        "text": [
            {"name": "title"},
            {"name": "links"}
        ]
    }
    vector_db = Redis(
        args.redis_url,
        index_name="simple",
        embedding=EMBEDDINGS,
        index_schema=schema
        )
    retriever = vector_db.as_retriever(
        search_kwargs={"k": args.num_results, "distance_threshold": 0.3},
        search_type="similarity_distance_threshold"
    )
    chain = make_qna_chain(retriever)
    result = chain({"query": args.content_query})
    print(result["result"])
    for doc in result["source_documents"]:
        print(doc.metadata["title"])
        print(doc.metadata["links"])
```

You can only pass the fields which you need to modify, as shown below, **as long as you are not also overwriting the ``vector_schema``.** If you also modify the ``vector_schema``, you need to pass that too.


### Option 3: Use class methods: ex. ``from_texts`` with like documents

If you are always loading in new documents with the same schema, you can also just keep using the ``from_texts``, ``from_documents``, etc methods.

```python
    # will work, metadata is used to create schema
    vector_db = Redis.from_texts(
        TEXTS,
        EMBEDDINGS,
        metadatas=METADATAS,
        redis_url=args.redis_url,
        index_name="simple",
        #index_schema=schema # no schema specified so schema will be generated
    )

    retriever = vector_db.as_retriever(
        search_kwargs={"k": args.num_results, "distance_threshold": 0.3},
        search_type="similarity_distance_threshold"
    )
    chain = make_qna_chain(retriever)
    result = chain({"query": args.content_query})
    print(result["result"])
    for doc in result["source_documents"]:
        print(doc.metadata["title"])
        print(doc.metadata["links"])

```

### Option 4: Don't index the fields and use the ``extra`` schema field

If you don't want your metadata fields to be indexed at all, possibly to decrease memory consumption or because you don't need the hybrid query capabilities, you can also include extra metadata by switching the ``text`` specification to ``extra``.

```python
    schema = {
        "extra": [
            {"name": "title"},
            {"name": "links"}
        ]
    }

    # will work, documents create schema
    vector_db = Redis.from_texts(
        TEXTS,
        EMBEDDINGS,
        metadatas=METADATAS,
        redis_url=args.redis_url,
        index_name="simple-extra",
        index_schema=schema # specify schema manually on creation
    )
    vector_db.write_schema("simple-schema-extra.yaml")
    retriever = vector_db.as_retriever(
        search_kwargs={"k": args.num_results, "distance_threshold": 0.3},
        search_type="similarity_distance_threshold"
    )
    chain = make_qna_chain(retriever)
    result = chain({"query": args.content_query})
    print(result["result"])
    for doc in result["source_documents"]:
        print(doc.metadata["title"])
        print(doc.metadata["links"])

```

On init, this will warn you that the schema does not match the schema that was generated.

```text
`index_schema` does not match generated metadata schema.
If you meant to manually override the schema, please ignore this message.
index_schema: {'extra': [{'name': 'title'}, {'name': 'links'}]}
generated_schema: {'text': [{'name': 'title'}, {'name': 'links'}], 'numeric': [], 'tag': []}
```

this will create a schema file that looks like

```yaml
extra:
- name: title
- name: links
text:
- name: content
  no_index: false
  no_stem: false
  sortable: false
  weight: 1
  withsuffixtrie: false
vector:
- algorithm: FLAT
  block_size: 1000
  datatype: FLOAT32
  dims: 1536
  distance_metric: COSINE
  name: content_vector
```

which can then be used directly with ``from_existing_index``.


## Next Steps

1. I need to put in the same safegaurds I have for the classmethods and ``from_existing_index`` into the ``Redis`` constructor. This issue can stay open until then.
2. In the future, we will remove the need to manually specify the schema and return it directly from the server side which will make it so that any existing index has it's schema populated automatically.

**Comment by Spartee** [comment]
@gorkanauta @FrancescoSaverioZuppichini Hopefully this solves your issue in the meantime, please let us know.
