### ISSUE TITLE
Documents not being correctly indexed in vector database. ["redis.exceptions.ResponseError: my_docs: no such index"]

### ISSUE THREAD

**Issue by Demian143** [langchain-ai/langchain#11197]
### System Info

Following the steps of indexing from [ https://python.langchain.com/docs/modules/data_connection/indexing ](url) you'll find the following error "redis.exceptions.ResponseError: my_docs: no such index".
You'll get this exception while using redis as retriever:
![Screenshot from 2023-09-28 16-57-03](https://github.com/langchain-ai/langchain/assets/81446007/afae536e-7888-4183-93d0-bfa65a8845a2)

### Information

- [x] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

![Screenshot from 2023-09-28 16-13-18](https://github.com/langchain-ai/langchain/assets/81446007/281206ed-b7c6-4b18-a3cc-25874fec7a06)
The error is here:
![Screenshot from 2023-09-28 16-32-00](https://github.com/langchain-ai/langchain/assets/81446007/f6bf52fb-d0ef-4f38-b247-475522bdfece)
If you look for the index you'll get (empty list or set).
This line makes impossible to save in the wanted format, and there's another thing: The index is not created for some reason.
I'll try to fix, but I'm not sure if it's possible for me at the moment, so I'm reporting this, I hope it helps.

### Expected behavior

Expected behavior inside Redis: "docs:indexname_:12ss2sadd"

**Comment by a9raag** [comment]
@Demian143 the URL link you added for documentation is not working, it takes you to the issues page. The text is correct it is just not linked correctly. 
https://python.langchain.com/docs/modules/data_connection/indexing

**Comment by jmv92** [comment]
Hi, 
I have the same issue with redis vector store when I try to use a recordmanager and the index function to store vectors. 
I don't know if the issue is in the redis vector store or in the function Index. 
The fact is that when I use "redis.from_texts" the redis index is correct and the key in redis has a prefix like "doc:indexname" but when I use index function with recordmanager (https://python.langchain.com/docs/modules/data_connection/indexing) the key has no prefix ! 
It looks like to be a bug

Regards
