### ISSUE TITLE
Limit Data and Enforcing Security for SQLDatabase & Agents

### ISSUE THREAD

**Issue by doit-ceo** [langchain-ai/langchain#11243]
### Feature request

We all want to have our clients to interact with the database using LLM, langchain with create_sql_agent, are great, the only problem I see, there is no way to limit user access to the database and fence him to his data. 

For example we have table called AI_Product with many columns and one of them is storeid, for normal user, he should have limited access to this table, I also don't trust the AI to limit that, there should be a way to programmatically do that.

So let's look at AI_Product
```
id, name, price, store_id
1, water, 2, 10001
2, pepsi, 4, 10001
3, cokezero , 5, 10002
```

For the above table, the user only have rights to access storeid= 10001, for security and true data we need a way to limit what this user can see.

One solution could be is to allow include_tables to have sql
`include_tables = ['AI_Product'] 
`
to
`include_tables = ['(select * from AI_Product where store_id = '10001') AI_Product'] 
`
The other one, is allow the SQL query to come back before execution and allow me to modify it
So if I asked , "How many products do we have?"

```
agent: sql:"select count(*) from AI_Product"
Then we can modify the sql to 
protected_sql = sql.replace("AI_Product", "(select * from AI_Product where store_id = '10001') AI_Product")
#sql = "select count(*) from (select * from AI_Product where store_id = '10001') AI_Product"
agent.run (protected_sql)

```

### Motivation

Find a way to protect the data while allow end-user unlimited access to it.

### Your contribution

I'm not familiar with the internal code, but I can help if gudied

**Comment by doit-ceo** [comment]
@dosu-bot for the first part, i.e. to limit the access in database, that is impossible even with views, i.e. if you have 1000 clients, you will need to create 1000 views ! 

For the second proposal to set the use_query_checker=true , can you provide more hint to how I can modify the sql before executing ? please do that with detailed code 

Thanks

**Comment by doit-ceo** [comment]
@dosu-bot this would have been what I'm looking for, but you code is incorrect !  the use_query_checker only accept boolean value and not a class

**Comment by doit-ceo** [comment]
@dosu-bot I guess you're not showing true solution and with limited understanding of how this works !
The following is not correct 
query_checker=query_checker 
I'm getting this error 
"ValidationError: 1 validation error for SQLDatabaseChain query_checker extra fields not permitted (type=value_error.extra)"

**Comment by doit-ceo** [comment]
@dosu-bot I still getting many errors 

```
ImportError: cannot import name 'QueryChecker' 
&
ValidationError: 1 validation error for SQLDatabaseChain query_checker extra fields not permitted (type=value_error.extra)
```
Your code is totally made up and not true, you got my need but your code is not working !

I hope I can get help from human

**Comment by yangzehan** [comment]
You can customize the metadata of the table so that the AI can obtain a specific table structure so that the extra columns will not be read by the AI

**Comment by doit-ceo** [comment]
You need an SQL level control and not db level. If a user asked AI "show me all of my orders for the last week" how can you guarantee that this client will only see his orders and not other clients orders ?!

Now I managed to hack the database object and adjust the sql to this.

select * from orders 

to 

select * from (select * from orders where client-id=124)

i.e. I'm finding and replacing any table with a limited version that is allowed for that client

**Comment by eyurtsev** [comment]
The self query approach is for use cases where control at the query level is needed: https://python.langchain.com/docs/modules/data_connection/retrievers/self_query/

It doesn't have a SQL adapter right now, but should not be too difficult to add one using sqlalchemy.

Do you mind sharing what kind of primitives you're looking to accommodate (e.g, filter, sort, count, aggregate statistics, group by?)

**Comment by sud962468** [comment]
@doit-ceo Can you please share the code snippet regarding how you have made this change in create_sql_agent.
I have the same use case.

**Comment by sud962468** [comment]
@dosu-bot Please provide me a solution to limit data using create_sql_agent.
Query check does not seems to be working with create_sql_agent. May be update in langchain version has changed the implementation. Please help.

**Comment by pranitcode** [comment]
@doit-ceo can you share how you done that.

**Comment by AmreshKumarY** [comment]
Can u send some reference articles on langchain which says that while using pandas/csv agent, Data is not sent directly to api?

**Comment by ashishsinha1602** [comment]
For anyone landing here from search, since this is still the page Google returns for the question:

`include_tables` is the right lever, but it has to be built **per request** rather than once at import. Construct `SQLDatabase(engine, include_tables=<tables this caller may read>)` inside the request handler from your ACL, then build the toolkit around that instance. It is cheap once the engine is pooled, and it keeps the LLM out of the authorisation decision entirely, which is what you actually want.

The OP's subquery idea is better served by per-tenant views plus row-level security, so the predicate survives whatever SQL the model writes. Postgres RLS, MySQL views, SQL Server row-level security, Oracle VPD - same shape, and the point below applies to all of them.

One failure mode worth knowing if you lean on the database alone. The ordering is the problem: table selection happens before the query executes, so it happens before RLS can act. If the selector is not identity-aware, the model is handed a table the caller cannot read, writes perfectly correct SQL, gets zero rows back, and confidently reports "there are no orders." That reads to the user as *this data does not exist* rather than *you may not see it*. It is a support ticket instead of a permission error, and far harder to debug than a clean 403, because nothing in the pipeline logs an anomaly. Nothing went wrong.

On how much the catalog side matters: I benchmarked it on a deliberately messy 127-object, three-domain schema with about 7M rows and name collisions across domains (`member`, `account`, `event` meaning different things in each). recall@6 was 47% with bare table and column identifiers, 60% with Gemini 2.5 Pro writing the table descriptions, 80% with Sonnet. So the model you use to *describe* your schema is worth roughly as much as the one you use to write the SQL, which surprised me. Same result held on Postgres and Oracle.

Disclosure: I wrote a small Apache-2.0 library for the catalog-filtering half of this - `schemagate` (`pip install schemagate`). It is dialect-agnostic, built on SQLAlchemy reflection, and tested against Postgres, MySQL, SQL Server, SQLite and Oracle. Browser demo, no signup and no database: https://ashishsinha1602.github.io/schemagate/ - ask something as an analyst, then add the `payroll` role to the caller and watch the restricted table enter the prompt. The per-request `include_tables` advice above works with plain LangChain and needs none of that.

Longer write-up of the ordering argument, with a migration mapping for anyone arriving here after Vanna was archived in March: https://dev.to/ashish_sinha_5241c7673d93/vanna-is-archived-the-failure-mode-none-of-the-replacements-fix-4l3i
