### ISSUE TITLE
Upgrade to Pydantic V2

### ISSUE THREAD

**Issue by Luca-Blight** [langchain-ai/langchain#12265]
### Feature request

Langchain is currently using Pydantic V1, and I believe it would be good to upgrade this to V2

### Motivation

V2 is far more performant than V1 because of the python-rust binding

### Your contribution

I can create a PR here.

**Comment by mokeyish** [comment]
Langchain use v1, while Fastapi use v2. they can't work together. 😔 

Hopefully v2 will be supported soon.

**Comment by Luca-Blight** [comment]
I'm actually working on that upgrade now. Hopefully I can settle it in the next week. You'll still have to wait until the next release : /

**Comment by eyurtsev** [comment]
Please reference the discussion here: https://github.com/langchain-ai/langchain/discussions/9337

LangChain is currently cross-compatible with both versions of pydantic. When using pydantic v2, langchain relies on the v1 namespace of pydantic v2.

We cannot yet upgrade to v2 since that'll break LangChain to any users that are dependent on v1. v1 is more popular currently than v2 and is used by many of our users. (https://www.pepy.tech/projects/pydantic?versions=2.*&versions=1.*)

FWIW:  
FastAPI includes v1/v2 comaptibility on its roadmap: https://github.com/tiangolo/fastapi/issues/10370, https://github.com/tiangolo/fastapi/issues/10360

LangChain should be usable with fastapi and pydantic v2 -- as long as LangChain schema isn't used directly in the fast api request/responses (can clone the schema with pydantic v2 use that for fast api validation, and then internally convert to schema with pydantic v1 when working with LangChain).

With that said, any work you can do to bring the code base to a state that will allow us to replace v1 models with v2 models will be appreciated. 

There's some automation that's available for this: https://github.com/pydantic/bump-pydantic, but it doesn't catch all cases and in a code base like LangChain there'll be a lot of manual work likely (we've got hundreds of pydantic classes).

**Comment by mokeyish** [comment]
Can we use a variable to control which version is used?

**Comment by eyurtsev** [comment]
@mokeyish I'm not sure at which level you mean

Users can control at the level fo the dependencies and install either pydantic v1 or pydantic v2. Everything will work as long as they don't only use v1 namespaced objects with langchain primitives; otherwise they can use pydantic v2 freely in their applications.

If you mean to use a variable at the application level to configure LangChain to use the proper v2 namepace, that would be great, but I'm not sure how feasible, if you can come up with a solution let us know. LangChain is CI already runs with both pydantic v1 and v2 for unit tests so you can test out to see how well your solution works.

As best as I can tell it's a bit of an all or nothing game with the pydantic migration -- I don't know that there's a safe way to upgrade some objects, but not others. :(

**Comment by nikokaoja** [comment]
@eyurtsev , I bump into [this issue](https://github.com/langchain-ai/langchain/issues/12358) due to need of my project to use `pydantic` v2.

**Comment by eyurtsev** [comment]
@nikokaoja please follow the guidelines here: https://github.com/langchain-ai/langchain/blob/master/docs/docs/guides/pydantic_compatibility.md

**Comment by nikokaoja** [comment]
many thanks @eyurtsev ! it worked.

**Comment by Chukwuebuka-2003** [comment]
> @nikokaoja please follow the guidelines here: https://github.com/langchain-ai/langchain/blob/master/docs/docs/guides/pydantic_compatibility.md

please this page isn't showing up
