### ISSUE TITLE
Getting error while using Redistore as docstore in parent document retreival

### ISSUE THREAD

**Issue by aniketmoha9** [langchain-ai/langchain#12488]
### System Info

i am getting an error while using Redistore as docstore `A tuple item must be str, int, float or bytes.`. I do not get error when using the InMemorystore. the problem is with mset function, in redistore mset throws error when i pass a document object, but redistore works if just pass a string.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

i am getting an error while using Redistore as docstore `A tuple item must be str, int, float or bytes.`. I do not get error when using the InMemorystore. the problem is with mset function, in redistore mset throws error when i pass a document object, but redistore works if just pass a string.

### Expected behavior

i am getting an error while using Redistore as docstore `A tuple item must be str, int, float or bytes.`. I do not get error when using the InMemorystore. the problem is with mset function, in redistore mset throws error when i pass a document object, but redistore works if just pass a string.

**Comment by Spartee** [comment]
This is due to metadata schema generation. If you see the ``_generate_field_schema`` function in ``Redis`` you'll see what I'm talking about. This can be improved and we have been tracking it.

In the meantime, another approach is to manually edit the metadata of the documents before passing them into Redis where this function is called. However, this may have an impact on the retriever. 

I'll take a deeper look at this soon.
