### ISSUE TITLE
Retrieval extraction of Tabular data 

### ISSUE THREAD

**Issue by Ajaypawar02** [langchain-ai/langchain#12515]
### Issue you'd like to raise.

hello everyone 
I have a website which needs to pe scrapped and the 
website has the tabular data 
so when I scrap the data using web loaders in langchain and build a llm  on top of it 
it is not able to answer the query.
So what can be the suitable approach to solve this issue

**Comment by Ajaypawar02** [comment]
here i need to get live results from website

**Comment by keenborder786** [comment]
@Ajaypawar02, you need to contextualize your results as a tool. For example, in the code below, I have created an agent that will provide us with the latest news updates from ESPN. The tool itself makes use of the WebBaseLoader to fetch live data from ESPN:

```python
from langchain.document_loaders import WebBaseLoader
from langchain.agents import AgentExecutor, OpenAIFunctionsAgent
from langchain.tools import BaseTool
from langchain.chat_models.openai import ChatOpenAI
from langchain.schema.messages import (
    SystemMessage,
)
import os
os.environ['OPENAI_API_KEY'] = ''

class GetESPNUpdate(BaseTool):
    name = "espn_news"
    description = "useful when you need to retrieve the latest news updates from ESPN"

    def _run(self, query: str) -> str:
        """Use the tool."""
        loader = WebBaseLoader("https://www.espn.com/")
        data = loader.load()
        all_page_content = "/n/n".join([doc.page_content for doc in data])
        return all_page_content

llm = ChatOpenAI()
prompt = OpenAIFunctionsAgent.create_prompt(system_message=SystemMessage(content="You are an agent useful for getting news updates from ESPN"))
agent = OpenAIFunctionsAgent(
    llm=llm,
    tools=[GetESPNUpdate()],
    prompt=prompt

)
executor = AgentExecutor.from_agent_and_tools(
    agent=agent,
    tools=[GetESPNUpdate()],
    verbose=True
)
print(executor.run("Get me the summary of news updates from ESPN"))
```

Therefore, in your use case, you would create a tool to extract the tabular dataset and utilize it. However, since your use case is not entirely clear, I can't provide more specific assistance. WebBaseLoader needs to be used as a tool if you want to dynamically answer user queries.

**Comment by keenborder786** [comment]
I hope this helps.
