### ISSUE TITLE
`ChatAnyscale` not working because of OpenAI API Key

### ISSUE THREAD

**Issue by baniasbaabe** [langchain-ai/langchain#12841]
### System Info

Langchain 0.0.329
Python 3.9
Windows 10

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python

import os 
from langchain.chat_models import ChatAnyscale

os.environ['OPENAI_API_KEY'] = "mykey"
os.environ['ANYSCALE_API_KEY'] = "mykey"

ChatAnyscale()

```

```
     95 
     96     def __init__(self, **kwargs: Any) -> None:
---> 97         super().__init__(**kwargs)
     98         self._lc_kwargs = kwargs
     99 

/usr/local/lib/python3.10/dist-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for ChatAnyscale
openai_api_key
  str type expected (type=type_error.str)
```

### Expected behavior

It shouldn't return an error because my Keys are both correct. For example, `ChatOpenAI` works fine.

**Comment by nndnha** [comment]
I had the same issue and resolved it by downgrading to v0.0.327 
@aidoskanapyanov Can you please recheck your [last PR](https://github.com/langchain-ai/langchain/pull/12406)?

**Comment by aidoskanapyanov** [comment]
Hi @nndnha! Unfortunately, I'm unable to reproduce this issue on both 0.0.329 and 0.0.330. It seems to send api request as expected. Do you get the same behavior?

![image](https://github.com/langchain-ai/langchain/assets/65722512/75c5b0d4-f35d-4bd9-87ad-d8ba27bae878)

**Comment by nndnha** [comment]
@aidoskanapyanov You need to test with a real API key to bypass your 401 error first because the issue occurred after this API request succeeded.

Here on my machine:

v0.0.327 worked!

![327](https://github.com/langchain-ai/langchain/assets/12961516/a36c7169-811d-4522-9787-5e43ee1d4200)


0.0.330 error!

![330](https://github.com/langchain-ai/langchain/assets/12961516/625f88f5-6af6-4ffb-8d85-44d87556f132)


And my pydantic version is 1.10.13

**Comment by aidoskanapyanov** [comment]
Thanks @nndnha ! I managed to reproduce it. The issue seems to originate from ChatOpenAI, it expects openai_api_key to be a string, while we're passing down a SecretStr. openai_api_key should probably be a Union[str, SecretStr]. I guess the masking of the api key in chat models of openai hasn't been added yet.

**Comment by kylehh** [comment]
I see errors with 0.0.333
I am looking for a fix

os.environ["ANYSCALE_API_KEY"] = "my_api_ke"
```
--> 150     values["openai_api_key"].get_secret_value(),
    151     values["openai_api_base"],
    152 )
    154 if model_name not in available_models:
    155     raise ValueError(
    156         f"Model name {model_name} not found in available models: "
    157         f"{available_models}.",
    158     )

AttributeError: 'str' object has no attribute 'get_secret_value'
```

**Comment by kylehh** [comment]
I create a #13237  to fix the bug with call `get_secret_value` on a str value (values["openai_api_key"])
and added OpenAI v1 support
