### ISSUE TITLE
ImportError: cannot import name 'Row' from 'sqlalchemy'

### ISSUE THREAD

**Issue by GabeDottl** [langchain-ai/langchain#13464]
### System Info

Version: langchain 0.0.336
Version: sqlalchemy  2.0.1

  File "/Users/anonymous/code/anon/anon/utils/cache.py", line 40, in set_cache
    from langchain.cache import SQLiteCache
  File "/Users/anonymous/dotfiles/virtualenvs/aiproject/lib/python3.11/site-packages/langchain/cache.py", line 45, in <module>
    from sqlalchemy import Column, Integer, Row, String, create_engine, select
ImportError: cannot import name 'Row' from 'sqlalchemy' (/Users/anonymous/dotfiles/virtualenvs/aiproject/lib/python3.11/site-packages/sqlalchemy/__init__.py)

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.cache import SQLiteCache

### Expected behavior

Doesn't throw exception

**Comment by thiswillbeyourgithub** [comment]
Still hapenning in version 0.339

**Comment by playermanny2** [comment]
same here, is there a fix being planned?

**Comment by thiswillbeyourgithub** [comment]
I mean a simple try except when importing Row would be a good workaround until the dependency mare is dealt with. Is it okay to do a quick PR for that?

**Comment by ChrisHowlin** [comment]
The problem is that Row is only defined as part of SQLAlchemy 2+, whereas langchain at the time of writing has a [dependency on sqlalchemy ">=1.4,<3"](https://github.com/langchain-ai/langchain/blob/9b59bde93d0fc90966383d575d09c2627c558d41/libs/langchain/pyproject.toml#L17). I think in the this change to [add SQLAlchemyMd5Cache](https://github.com/langchain-ai/langchain/pull/11660) the dependency needed to be updated to >=2.0.0.

Although OP reports having 2.0.1 installed, the fix for me was to specify sqlalchemy above 2.0.0 (I have tested with 2.0.0 and 2.0.1)
