### ISSUE TITLE
Agent as tool gives wrong result ( pandas agent)

### ISSUE THREAD

**Issue by Chetan8000** [langchain-ai/langchain#13711]
### Issue you'd like to raise.

I'm using 
```python 
from langchain.agents import create_pandas_dataframe_agent

pd_agent = create_pandas_dataframe_agent(OpenAI(temperature=0), 
                         df, 
                         verbose=True)

pd_agent.run('some question on dataframe')
```
```python
english_tools = [

        Tool(name="SomeNAME_1",
             func=lambda q: app.finance_chain.run(q),
             description=" Some app related description ",
             return_direct=True,
             coroutine=lambda q: app.finance_chain.arun(q),
             ),
        Tool(name="SomeNAME_2",
             func=lambda q: app.rqa(q),
             description=" Some app related description ",
             coroutine=lambda q: app.rqa_english.arun(q),
             return_direct=True
             ),
        Tool.from_function(
            name="SomeNAME_3",
            func=lambda q: app.pd_agent(q),
            description=" Some app related description",
            coroutine=lambda q: app.pd_agent.arun(q),
        )
    ]
```

when we call this agent seperatly it's gives me a good result
but when i use this agent as a tool along with other tools it's not gives consistent results, mostly wrong answer

**Comment by Chetan8000** [comment]
how i manage this agent as tool, it's gives me wrong result but when i run pd_agent seperatly it's work well

```python
from langchain.agents import create_pandas_dataframe_agent

pd_agent = create_pandas_dataframe_agent(OpenAI(temperature=0), 
                         df, 
                         verbose=True)

pd_agent.run('some question on dataframe')
```

**Comment by ikouchiha47** [comment]
Hi, since you are using the OpenAI as your llm you might want to try this instead.

```
TEMPLATE = """
You are working with a pandas dataframe in Python. The name of the dataframe is `df`.

Summary of the whole conversation:
{chat_history_summary}

Last few messages between you and user:
{chat_history_buffer}

Your answer should produce valid python code, without any syntax errors \
and should be executable by python_repl_ast.
You should use the tools below to answer the question posed of you:
"""

 self.agent = create_pandas_dataframe_agent(
            llm=_model,
            df=self.df,
            # suffix=SUFFIX_WITH_DF,
            include_df_in_prompt=True,
            agent_type=AgentType.OPENAI_FUNCTIONS,
            prefix=TEMPLATE,
            early_stopping_method='generate',
            max_iterations=5,
            agent_executor_kwargs={
                'handling_parsing_errors': "Check your output and make sure it conforms!",
                # 'memory': chat_memory, # this can be found in examples, but you can skip for one shot run.
            },
            verbose=True, # for debugging
```

The main change here is `include_df_in_prompt=True` and adding the [prefix template](https://github.com/langchain-ai/langchain/blob/master/libs/experimental/langchain_experimental/agents/agent_toolkits/pandas/prompt.py) . These should help you overall. I have used a custom __TEMPALTE__ here, because none of the base templates use chat history and I also need to ask the model to provide valid python code.


Its pretty hard to get a valid factual result everytime from an LLM that has been trained on huge corpus of text. You can try OpenAI and TAPEX or TAPAS models, which are better suited for understanding table reading.

But most RAG's that give you factual information, I believe has to be hand-built, otherwise there is no way of knowing if the data is have you factual with respect to context or not.


So I would say, maybe learn some nltk and tensorflow. You can use WikiSQL or OpenWikiSQL etc to train your model. You might also like to look at sweetviz . But yeah I think how LLMs can actually be used is to agument your results.

So, lets say, you have your own indexing layer (TF-IDF) on your company documents or pdfs, and you allow users searches on it. (Think elastic search) and then , if people want some other information or explanation based on the text, (Think citation numbers), Then they can use a pre trained LLM model. Where not everything will be 100% accurate, but it will give you an idea.
