### ISSUE TITLE
Changing Model Param after Initialization VLLM Model

### ISSUE THREAD

**Issue by zhuofan-16** [langchain-ai/langchain#13762]
### Feature request

Introduce a more flexible method to specify model parameters directly within the LLMChain or VLLM method, allowing users to modify these parameters without creating a new model instance each time.

### Motivation

Currently, when utilizing the Langchain library's VLLM class, modifying model parameters (such as temperature, top_k, top_p, etc.) requires creating a new instance of the VLLM class. This process becomes cumbersome, especially when frequent adjustments to model parameters are necessary.
Current Situation:
`
from langchain.llms import VLLM

llm = VLLM(
    model="mosaicml/mpt-7b",
    trust_remote_code=True,  # mandatory for hf models
    max_new_tokens=128,
    top_k=10,
    top_p=0.95,
    temperature=0.8,
)

template = """Question: {question}

Answer: Let's think step by step."""
prompt = PromptTemplate(template=template, input_variables=["question"])

llm_chain = LLMChain(prompt=prompt, llm=llm)

question = "Who was the US president in the year the first Pokemon game was released?"

print(llm_chain.run(question))

`

It is very tedious to keep creating new model when i want to change model params like (temperature and etc) .

In naive VLLM, this can be done so easily:
llm = LLM(model="qwen/Qwen-7B-Chat", revision="v1.1.8", trust_remote_code=True)
outputs = llm.generate(prompts, model_params)
outputs = llm.generate(prompts, model_params)

### Your contribution

NA

**Comment by shahrin014** [comment]
Other LLM integrations may differ, but from my experience using `Ollama` integration, you can pass parameters to the `generate` function using `bind`.

For example:
```
model = Ollama(model='mixtral')
chain1 = prompt1 | model.bind(model='llama2') | StrOutputParser()
```
So instead of the chain using the 'mixtral' model, it will use 'llama2' model. This is because bind will pass any parameters to the generate function via kwargs parameter. It will then use that to format the post request payload:
https://github.com/langchain-ai/langchain/blob/v0.1.0/libs/community/langchain_community/llms/ollama.py#L176

Can you give more information on which LLM integration you are working with?
