### ISSUE TITLE
Issue: I'd like to use Hugging Face's Chat UI frontend with LangChain.

### ISSUE THREAD

**Issue by haje01** [langchain-ai/langchain#14207]
### Issue you'd like to raise.

I'd like to use Hugging Face's Chat UI frontend with LangChain.

https://github.com/huggingface/chat-ui

But it looks like the Chat UI is only available through Hugginf Face's Text Generation Inference endpoint. 

https://github.com/huggingface/chat-ui/issues/466

How can I serve the chain I have configured with LangChain in TGI format so I can use Chat UI?

Thank you in advance.

**Comment by rahermur** [comment]
I also find this functionality very useful. We are pushing for having an integration between HuggingFace ChatUI and endpoints built using LangServe. But I think this is something that needs to be contributed to HuggingFace project instead of here. We already open a MR for this: https://github.com/huggingface/chat-ui/pull/1009 take a look if you are interested on this
