### ISSUE TITLE
Issue: Recently, the DuckduckGo search tool seems not working. VQDExtractionException: Could not extract vqd. keywords="keywords"

### ISSUE THREAD

**Issue by Suroras** [langchain-ai/langchain#14233]
### Issue you'd like to raise.

from langchain.agents import AgentType, initialize_agent
from langchain.chat_models import ChatOpenAI
from langchain.tools import DuckDuckGoSearchRun

llm = ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo-16k")

web_search = DuckDuckGoSearchRun() 
tools = [
    web_search,
    # other tools
]

agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
 
agent.run("<Some question>")

VQDExtractionException: Could not extract vqd. keywords="blah blah blah"

---
The code above worked fine several weeks ago, but it is not working any more. I tried every version of LangChain released after September.

Maybe there is a change in DuckDuckGo's API. Please help me, thanks.

**Comment by robertoshimizu** [comment]
The issue seems to be in `duckduckgo-search`, as I have tried the api directly from the pypackage, without through langchain, and I have got the same error message:

```
VQDExtractionException: Could not extract vqd.
```

**Comment by zimpstar** [comment]
@robertoshimizu did you manage to solve it somehow?

**Comment by dmitryvostryakov** [comment]
> The issue seems to be in `duckduckgo-search`, as I have tried the api directly from the pypackage, without going through langchain, and I have got the same error message:
> 
> ```
> VQDExtractionException: Could not extract vqd.
> ```

In my case I usually got VQD errors when I tried to send a really large query to duckduckgo-search, try with shorter versions.
Also, double check if your requirements packages are up to date, especially for langchain and duckduckgo-search.

**Comment by deedy5** [comment]
Since some time `duckduckgo.com` started blocking ip by tls-fingerprint, which caused constant troubles. 
But since version v4.0.0 `duckduckgo_search` uses `curl-cffi` and there are no more problems.

**Comment by kyjones03** [comment]
> Since some time `duckduckgo.com` started blocking ip by tls-fingerprint, which caused constant troubles. But since version v4.0.0 `duckduckgo_search` uses `curl-cffi` and there are no more problems.

This helped fix the problem for me!

`pip install --upgrade duckduckgo_search`

**Comment by trotsky1997** [comment]
> > Since some time `duckduckgo.com` started blocking ip by tls-fingerprint, which caused constant troubles. But since version v4.0.0 `duckduckgo_search` uses `curl-cffi` and there are no more problems.
> 
> This helped fix the problem for me!
> 
> `pip install --upgrade duckduckgo_search`

You're Amazing!

**Comment by takimdigital** [comment]
hi i come up with the same issue, its not realted with the upgrade . this is my solution 

# instead of using  :

#search online using duckduckgo
#search_tool = DuckDuckGoSearchRun()

# do this :


@tool('DuckDuckGoSearch')
def search(search_query: str):
    """Search the web for informations """
    return DuckDuckGoSearchRun().run(search_query)

# here is an example with crewai  + ollama  + web search :

#import 
from crewai import Agent, Task, Crew, Process
from langchain_openai import ChatOpenAI
from langchain_community.llms import Ollama
from langchain.agents import tool
from langchain.agents import load_tools
from langchain_community.tools import DuckDuckGoSearchRun


llm_ollama_dolphin = Ollama(model="dolphin-mistral")
#llm_ollama_mistral = Ollama(model="mistral")

@tool('DuckDuckGoSearch')
def search(search_query: str):
    """Search the web for informations """
    return DuckDuckGoSearchRun().run(search_query)

researcher = Agent(
  role='Senior Researcher',
  goal='Discover groundbreaking technologies',
  backstory='A curious mind fascinated by cutting-edge innovation and the potential to change the world, you know everything about tech.',
  verbose=True,
  tools=[search],
  allow_delegation=False,
  llm=llm_ollama_dolphin 
)

.... etc 



# output :

![image](https://github.com/langchain-ai/langchain/assets/118310733/0d479a40-acbe-4a41-a15d-b55381e8c620)

**Comment by YanSte** [comment]
**Update the library to the latest version.**

Many times this solved my case.

(It's possible that certain versions were blocked due to security reasons.)
