### ISSUE TITLE
Ability to set ollama serve url

### ISSUE THREAD

**Issue by thawkins** [langchain-ai/langchain#15365]
### Feature request

The ollama integration assumes that all models are served on "localhost:11434",  if the ollama service is hosted on a different machine, the integration will fail. 

Can we add an environment variable that if present overrides this url, so the correct url for the ollama server can be set. 

### Motivation

In My setup ollama sits on a separate machine that is resourced for serving  LLMs. 

### Your contribution

I'm afraid I don't have any knowledge of python, go, cpp and rust only.

**Comment by chyroc** [comment]
try:
```
ChatOllama(base_url='your ollama server host')
```

**Comment by NatEvory** [comment]
You can use the base_url parameter when instantiating the model, something like this
`ollama_llm = Ollama(
        model="llama2",
        base_url="http://OLLAMA_HOST:PORT"
    )`

It's not documented but I found it in the code and tried it out, it worked for me. There are a bunch of other undocumented parameters in that file as well (top_k, temperature, etc)
https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/llms/ollama.py

**Comment by mfreeman451** [comment]
this should be closed/resolved..

**Comment by tdimitch** [comment]
I'm using
`
from langchain_community.llms.ollama import Ollama
Ollama(model="llama3.1", base_url="http://localhost:11436")
`
But I'm getting:
`
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=11436): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EDB6ACBE30>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'))
`

When I try to serve ollama from PowerShell in Windows, if I want to modify the host i have to:
`
> $env:OLLAMA_HOST="0.0.0.0:11436"
> ollama serve
`
In order to modify the default host, since I see no way of modify it with flags.

I'm trying to see if I can set the OLLAMA_HOST variable from the Python script itself, but with no luck so far. Nor I'm able to check how langchain is serving the api.
