### ISSUE TITLE
text_splitter module not found in  langchain version 0.0.353.

### ISSUE THREAD

**Issue by arijitr** [langchain-ai/langchain#15520]
### System Info

langchain version 0.0.353.
python : 3.9

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

<img width="685" alt="image" src="https://github.com/langchain-ai/langchain/assets/66120014/8ae76db3-ee47-4994-81a1-d587d75e27f7">

<img width="643" alt="image" src="https://github.com/langchain-ai/langchain/assets/66120014/726640b5-b7b6-4734-b6eb-5b5c50a7106c">

<img width="622" alt="image" src="https://github.com/langchain-ai/langchain/assets/66120014/011d05f2-1a6f-4fc1-abd1-08a8241c4a49">

### Expected behavior

Should be able to load the module

**Comment by HazSyl1** [comment]
Hey I'm currently facing the same issue. I'll update you soon .

**Comment by HazSyl1** [comment]
![Screenshot 2024-01-21 164414](https://github.com/langchain-ai/langchain/assets/106075510/c66d4643-92b9-490c-b545-8dc5a30f6490)
 
Hey, so it turns out your file name is also 'langchain.py' , so instead of importing text_splitter from the library it's trying to import text_splitter from your file itself. Just change the name of your file and it'll work . 
In case this also does not work , try to verify the directory in which your langchain library is installed.
