### ISSUE TITLE
When configuring with `chroma_setting=Settings(anonymized_telemetry=False)`, the `Chroma.from_documents(persist_directory="./chroma.db")` parameter is not taking effect.

### ISSUE THREAD

**Issue by leos-code** [langchain-ai/langchain#16259]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

persist_directory = './chroma.db'
chroma_setting = Settings(anonymized_telemetry=False,persist_directory=persist_directory)

# model_name = "intfloat/multilingual-e5-base"
model_name = "shibing624/text2vec-base-chinese"
model_kwargs = {'device': 'cpu'}
encode_kwargs = {'normalize_embeddings': True}

embed_impl = HuggingFaceEmbeddings(model_name=model_name, model_kwargs=model_kwargs, encode_kwargs=encode_kwargs)

def generate_text_embedding():
    loader = CSVLoader("./drug.csv")
    documents = loader.load()
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    split_docs = text_splitter.split_documents(documents)
    vectorstore = Chroma.from_documents(documents=split_docs, persist_directory=persist_directory, embedding=embed_impl, client_settings=chroma_setting) 

### Description

When employing Chroma VectorStore, the specified configuration of `chroma_setting=Settings(anonymized_telemetry=False)` does not result in the desired functionality of `persist_directory`.

---

I discovered in the source code that when configuring the `chroma_setting` parameter, solely specifying the `persist_directory` parameter does not suffice for vector persistence. It is imperative to additionally set `is_persistent=True` to ensure proper vector storage.

```python
chroma_setting = Settings(anonymized_telemetry=False, is_persistent=True, persist_directory=persist_directory)
```

### System Info

Python 3.10.13
langchain                                0.1.0
langchain-community                      0.0.13
langchain-core                           0.1.10
langchain-openai                         0.0.2.post1

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by evisong** [comment]
I've run into the same issue. It took me a whole afternoon to troubleshoot this, my first guess was some unnotified changes were made in the remote embedding model, I didn't find the root cause until I ran a test with pure Chroma API.

I guess if the fix is made in LangChain, adding the following line:

```python
client_settings.is_persistent = True
```

to:

https://github.com/langchain-ai/langchain/blob/2813e8640703b8066d8dd6c739829bb4f4aa634e/libs/partners/chroma/langchain_chroma/vectorstores.py#L313-L317

would be enough.

However this may add more implicitness. Maybe it's better to give a warning saying "persist_directory would not be honored when client_settings specified, please set it in client_settings by yourself"?
