### ISSUE TITLE
FileNotFoundError: soffice command was not found. Please install libreoffice on your system and try again.

### ISSUE THREAD

**Issue by KaifAhmad1** [langchain-ai/langchain#16973]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

``` Python
# Load Directory that contains all the documents related to RAG: 
from langchain_community.document_loaders import DirectoryLoader
directory = '/content/drive/MyDrive/QnA Pair Documents'
```

``` Python
def load_docs(directory):
    loader = DirectoryLoader(directory)
    documents = loader.load()
    return documents
```

```  Python
documents = load_docs(directory)
``` 

### Error Message and Stack Trace (if applicable)

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/unstructured/partition/common.py](https://localhost:8080/#) in convert_office_doc(input_filename, output_directory, target_format, target_filter)
    406     try:
--> 407         process = subprocess.Popen(
    408             command,

15 frames
FileNotFoundError: [Errno 2] No such file or directory: 'soffice'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/unstructured/partition/common.py](https://localhost:8080/#) in convert_office_doc(input_filename, output_directory, target_format, target_filter)
    412         output, error = process.communicate()
    413     except FileNotFoundError:
--> 414         raise FileNotFoundError(
    415             """soffice command was not found. Please install libreoffice
    416 on your system and try again.

FileNotFoundError: soffice command was not found. Please install libreoffice
on your system and try again.

- Install instructions: https://www.libreoffice.org/get-help/install-howto/
- Mac: https://formulae.brew.sh/cask/libreoffice
- Debian: https://wiki.debian.org/LibreOffice
```

### Description

I have downloaded and installed the `libreoffice` from provided link but I am still getting this error. 

### System Info

Python version: 3.10.10
Operating System: Windows 11
Windows: 11
pip == 23.3.1
python == 3.10.10
long-chain == 0.1.0
transformers == 4.36.2
sentence_transformers == 2.2.2
unstructured == 0.12.0

**Comment by AdithiyaG** [comment]
so need to install Libreoffice to resolve this error? @KaifAhmad1. how did you resolve this error?

**Comment by omairi** [comment]
I have this issue, as I have installed all pre-requisites, libreoffice is installed and in the system path. I have run the command on on cmd promt to convert a ppt file to pptx and it all works fine. but when I call partition_ppt function from unstructured library I get this error "Error processing <file_name_path.ppt>: soffice command was not found. Please install libreoffice
on your system and try again.
- Install instructions: https://www.libreoffice.org/get-help/install-howto/
- Mac: https://formulae.brew.sh/cask/libreoffice
- Debian: https://wiki.debian.org/LibreOffice"
I have checked in the common.py in unstructured partion folder this is  FileNotFoundError Exception, look like python subprocess can not find soffice which is hard to believe because, soffice in the system path. I have tested the following command on cmd prompt "soffice --headless --convert-to "pptx" --outdir "local_folder_name"  "local ppt file name with path"  "
Any help from @KaifAhmad1 or @dosubot
