### ISSUE TITLE
Can we also update the pricing information for the latest OpenAI models (released  0125)?

### ISSUE THREAD

**Issue by lucasmtz** [langchain-ai/langchain#17173]
Can we also update the pricing information for the latest OpenAI models (released  0125)?

_Originally posted by @huanvo88 in https://github.com/langchain-ai/langchain/issues/12994#issuecomment-1923687183_

**Comment by IsakNyberg** [comment]
This should be solved as of #17349

**Comment by huanvo88** [comment]
Please also update the pricing for OpenAI's latest [gpt-4-turbo](https://platform.openai.com/docs/models/continuous-model-upgrades) models: `gpt-4-turbo` and `gpt-4-turbo-2024-04-09` in [openai callback](https://api.python.langchain.com/en/latest/_modules/langchain_community/callbacks/openai_info.html#OpenAICallbackHandler).

We should probably keep this issue open since OpenAI continually updates its models, or have some automated way to fetch the pricing information from OpenAI.
