### ISSUE TITLE
Error when pushing PGVector embeddings to Vercel

### ISSUE THREAD

**Issue by lud-hu** [langchain-ai/langchain#17428]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```json
{"page_content": "hallo test", "metadata": {"source": "mysource", "seq_num": 244 }, "type": "Document"}
```

```py
chunked_documents = load_docs_from_jsonl("test.jsonl")
embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)
collection_name = "test_embeddings_cs" + str(CHUNK_SIZE)

db = PGVector.from_documents(
    embedding=embeddings,
    documents=chunked_documents,
    collection_name=collection_name,
    connection_string=POSTGRES_URL,
    pre_delete_collection=False,
)
```

```
DETAIL:  Missing "]" after array dimensions.

[SQL: INSERT INTO langchain_pg_embedding (collection_id, embedding, document, cmetadata, custom_id, uuid) VALUES (%(collection_id)s::UUID, %(embedding)s, %(document)s, %(cmetadata)s, %(custom_id)s, %(uuid)s::UUID)]
[parameters: {'collection_id': UUID('f35bcca7-c797-4e57-a31a-8d82da54542b'), 'embedding': '[-0.02666512080169465,0.0014875975490676566,0.003841705348754905,-0.025984670417264277,-0.01976139198263224,-0.005496757382752562,-0.0229651753288143 ... (32576 characters truncated) ... .016387495109019937,-0.02728886667698162,-0.011532203877076985,-0.013332560400847324,-0.006326055473869786,0.015182533137287487,0.012971071250534016]', 'document': 'hallo test', 'cmetadata': '{"source": "mysource", "seq_num": 244}', 'custom_id': 'ab97f376-c9cf-11ee-88a9-1eae5cf5b7d5', 'uuid': UUID('f21bf17b-07b2-40f2-a33f-16c50f682e7f')}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
```

### Description

I have a very simple code that creates embeddings from my previously prepared documents with PGVector and tries to push it to the PostgreSQL in Vercel. Unfortunately it complains with an `DETAIL:  Missing "]" after array dimensions.`

### System Info

langchain==0.1.6
langchain-community==0.0.19
langchain-core==0.1.22
langchain-openai==0.0.5
mac
Python 3.12.1

**Comment by Vignesh-95** [comment]
I might be wrong but seems like the response from the bot is with reference to the PGEmbedding Vector store - based on the code and explanations it has provided. @lud-hu do you think the same?

While in your code, you are using the PGVector vector store. PGVector is different from PGEmbedding - they use different underlying postgres extensions, namely, vector and embedding. Your issue is with PGVector.

I too am experiencing the same issue.

`DataError: (psycopg2.errors.InvalidTextRepresentation) malformed array literal: "[0.008705009690435386,-0.009318782930954644,0.049814570604271115,-0.027692358890312824,-0.02364014084794179,0.020155496858537934,-1.0440938221157862e-05,-0.00815063527229415,-0.03936063863605954,0.003910324994790527,0.03408087411264999,0.029065098560468978,0.007154079606741888,-0.01928433586118697,0.010341736469174929,-0.007840448976158678,0.03587599464665569,0.007107881816173667,0.014083769146733064,-0.027111586133842278,0.012011461869318039,0.006956088343981773,-0.0002701753978344534,0.034265663412277735,0.01474373971215926,0.006177323393428539,0.015390510642759512,-0.0025227370160237268,-0.005626248185501859,-0.01681604605825171,0.005263264281385195,0.017726806891403074,-0.020432684533269838,-0.02274258058093894,-0.00211190548340092,-0.029038699290817094,-0.0038212288566992817,-0.0101437456720761,0.00422381096680184,-0.004728688384160298,0.026623208027185603,0.0024468405127584234,0.008084638029487015,-0.007088082363934755,0.01141748854669898,-0.0004454800501719558,-0.03196896979340229,-0.002329695732738661,-0.018927952240144562,0.0023676438679559914,0.009991952199884207,0.012328247517205196,-0.05860537652409126,0.008540017514740124,-0.013021216704034956,-0.010064548794443025,0.004705589256045544,0.04994656136459509,0.007338871234676063,-0.005438156416030556,0.01948232758960837,0.005388658483925206,0.0011607230386938847,0.008421222663951797,-0.011437287533276604,0.0053160618893663...
LINE 1: ...56e5cc9-aefb-4740-8a46-302bb354d9c0'::uuid::UUID, '[0.008705...
                                                             ^
DETAIL:  Missing "]" after array dimensions.`

**Comment by Vignesh-95** [comment]
@dosu-bot I might be wrong but seems like the response from the bot is with reference to the PGEmbedding Vector store - based on the code and explanations it has provided. @lud-hu do you think the same?

While in your code, you are using the PGVector vector store. PGVector is different from PGEmbedding - they use different underlying postgres extensions, namely, vector and embedding. Your issue is with PGVector.

I too am experiencing the same issue.

`DataError: (psycopg2.errors.InvalidTextRepresentation) malformed array literal: "[0.008705009690435386,-0.009318782930954644,0.049814570604271115,-0.027692358890312824,-0.02364014084794179,0.020155496858537934,-1.0440938221157862e-05,-0.00815063527229415,-0.03936063863605954,0.003910324994790527,0.03408087411264999,0.029065098560468978,0.007154079606741888,-0.01928433586118697,0.010341736469174929,-0.007840448976158678,0.03587599464665569,0.007107881816173667,0.014083769146733064,-0.027111586133842278,0.012011461869318039,0.006956088343981773,-0.0002701753978344534,0.034265663412277735,0.01474373971215926,0.006177323393428539,0.015390510642759512,-0.0025227370160237268,-0.005626248185501859,-0.01681604605825171,0.005263264281385195,0.017726806891403074,-0.020432684533269838,-0.02274258058093894,-0.00211190548340092,-0.029038699290817094,-0.0038212288566992817,-0.0101437456720761,0.00422381096680184,-0.004728688384160298,0.026623208027185603,0.0024468405127584234,0.008084638029487015,-0.007088082363934755,0.01141748854669898,-0.0004454800501719558,-0.03196896979340229,-0.002329695732738661,-0.018927952240144562,0.0023676438679559914,0.009991952199884207,0.012328247517205196,-0.05860537652409126,0.008540017514740124,-0.013021216704034956,-0.010064548794443025,0.004705589256045544,0.04994656136459509,0.007338871234676063,-0.005438156416030556,0.01948232758960837,0.005388658483925206,0.0011607230386938847,0.008421222663951797,-0.011437287533276604,0.0053160618893663...
LINE 1: ...56e5cc9-aefb-4740-8a46-302bb354d9c0'::uuid::UUID, '[0.008705...
                                                             ^
DETAIL:  Missing "]" after array dimensions.`

**Comment by Pieeer1** [comment]
For anyone coming in the future, this is because the vector gets truncated with the default size.

Increasing the size of the vector column fixes this issue:

```sql
alter table langchain_pg_embedding alter column embedding type vector;
```

**Comment by Pieeer1** [comment]
Why was this closed? This is an open bug. Was this resolved in a PR? This seems like this should still be open.
