### ISSUE TITLE
convert_to_openai_function drop some (nested?) properties

### ISSUE THREAD

**Issue by yoch** [langchain-ai/langchain#17531]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
from typing import Set, Literal
from langchain_core.utils.function_calling import convert_to_openai_function

class UserInfos(BaseModel):
    "general information about a user"
    gender: Literal["male", "female", "other"]
    preferences: Set[Literal["games", "books"]]
```

### Description

The resulting function is not well defined and missing some properties.

## Output
```json
{
  "name": "UserInfos",
  "description": "general information about a user",
  "parameters": {
    "type": "object",
    "properties": {
      "gender": {
        "enum": [
          "male",
          "female",
          "other"
        ],
        "type": "string"
      }
    },
    "required": [
      "gender",
      "preferences"
    ]
  }
}
```

## Excepted

**NOTE**: This is produced by the deprecated `convert_pydantic_to_openai_function` function.

```json
{
  "name": "UserInfos",
  "description": "general information about a user",
  "parameters": {
    "properties": {
      "gender": {
        "enum": [
          "male",
          "female",
          "other"
        ],
        "type": "string"
      },
      "preferences": {
        "items": {
          "enum": [
            "games",
            "books"
          ],
          "type": "string"
        },
        "type": "array",
        "uniqueItems": true
      }
    },
    "required":[
      "gender",
      "preferences"
    ],
    "type":"object"
  }
}
```

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2
> Python Version:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.23
> langchain: 0.1.7
> langchain_community: 0.0.20
> langsmith: 0.0.87
> langchain_openai: 0.0.6

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by francisc0garcia** [comment]
Related: https://github.com/langchain-ai/langchain/issues/14899

**Comment by baskaryan** [comment]
@francisc0garcia I believe this happens if you have pydantic v2 installed and aren't using `langchain_core.pydantic_v1`. If you change your pydantic imports from `langchain_core.pydantic_v1`, should work:

![Screenshot 2024-02-14 at 11 32 39 AM](https://github.com/langchain-ai/langchain/assets/22008038/6a6ec6d8-239f-4758-8662-5fe872e64328)

**Comment by yoch** [comment]
@baskaryan I can confirm this point, but that's a bit problematic in my case because I use some features of v2.

Are there plans to upgrade pydantic to v2 soon? In the meantime I can use the `convert_pydantic_to_openai_function` function.

**Comment by baskaryan** [comment]
> @baskaryan I can confirm this point, but that's a bit problematic in my case because I use some features of v2.
> 
> Are there plans to upgrade pydantic to v2 soon? In the meantime I can use the `convert_pydantic_to_openai_function` function.

Note you can have pydantic v2 installed and use `langchain_core.pydantic_v1`, but yea under the hood it'll use `pydantic.v1` classes so it won't have all the pydantic v2 features.

A lot of our community still runs on pydantic v1 so we definitely want to continue supporting it for the moment. Hard to estimate when we'll fully switch to v2 since that depends on factors outside of our control (ie what % of our users need pydantic v1 support).
