### ISSUE TITLE
Progress on Custom Agent Class?

### ISSUE THREAD

**Issue by mathematicsofpaul** [langchain-ai/langchain#1840]
Hey there, just asking on what the progress is on the "Custom Agent Class" for langchain? 🙂

https://langchain.readthedocs.io/en/latest/modules/agents/examples/custom_agent.html#custom-agent-class

**Comment by awesome-gpt4** [comment]
This would be such a powerful tool if available!

**Comment by RyzorBent** [comment]
I'm also keen, as I'm looking for a way to create a **n8n** custom agent.

**Comment by wt-ai** [comment]
Also interested in this. I need to write an agent class which has capabilities beyond what the current agents support.

**Comment by BishopCrypto** [comment]
Guys?  There's a giant hole in the documentation.

**Comment by chat-guy** [comment]
Custom agents would be super valuable. I thought it was implemented already.

Is there any progress on this? I want to contribute my help on the relevant implementation but would feel more confident if one of the core members leads the effort, since the internals of the overall project are a bit obscure to me still.
