### ISSUE TITLE
Getting an error InvalidRequestError: Resource not found  in VectorDBQA

### ISSUE THREAD

**Issue by srivatsanv1** [langchain-ai/langchain#1923]
HI,
I am getting an error "InvalidRequestError: Resource not found" while using Chat model using VectorDBQA chain. 
This issue is coming up after v0.0.120 release and I was not getting this in the previous version which I used which was v0.0.118.
I am using Chatmodel from Azure through AzureChatOpenAI and embeddings through Azure`s model.

**Comment by Fanchouille** [comment]
Hi, same here ("InvalidRequestError: Resource not found"), it's working when using v0.0.119 but not with next versions (0.0.120 & 0.0121).
Not using gpt 35 though, but davinci003.

**Comment by Rammstein-1994** [comment]
I have the same problem

**Comment by srivatsanv1** [comment]
Getting the same error with ConversationalRetrievalChain also.  Is this some issue with AzureOpenAI?

**Comment by devmart10** [comment]
What worked for me was removing the import of `openai` when using the `langchain.llms.AzureOpenAI` module.

Try removing `import openai` even if none of your code appears to be using it.

I'm using version 2022-12-01.

**Comment by domalbert** [comment]
You should put in the deployment name into AzureOpenAI:

> llm = AzureOpenAI(model_name=deployment_name, deployment_id=deployment_name,deployment_name=deployment_name)

However for me this depends a lot if I take chatGPTs ```gpt35-turbo``` or ```gpt-4``` version.


Here are the versions of my dependencies.

langchain: 0.0.118
openai: 0.27.4

**Comment by nickwong64** [comment]
I have this "Resource Not Found" error using Azure OpenAI, OpenAIEmbeddings and ConversationalRetrievalChain.
I found that when using OpenAIEmbeddings the api_version would be changed to "2022-12-01" and after that, using ConversationalRetrievalChain, the api_version will keep as "2022-12-01" and cause the "Resource Not Found" error.
The workaround is to set the api_version back to "2023-03-15-preview" after calling OpenAIEmbeddings but before calling ConversationalRetrievalChain.

Enable the openai.log = "debug" so that you can trace all the endpoints and parameters to help you debugging.

**Comment by vahidzangenehc** [comment]
I have this issue and non of the solution works for me! 
In the debug logs I see the api_version is None although I already have set `os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview"`.

**Comment by truedat101** [comment]
commenting on this issue, yes, I verified this is still a problem.
