### ISSUE TITLE
Document on_retriever_x callbacks

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#19361]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Callbacks are a bit out of date: https://python.langchain.com/docs/modules/callbacks/

We need to document updates in the supported callbacks

**Comment by sepiatone** [comment]
@eyurtsev I could take up some (or all) of this.

I see that the list of events for which a callbacks can be sent must be updated (include events from retrievers) and update the examples to use lcel instead of chains (for all the callbacks pages).

Perhaps use a table for the events with an explanation (rather than a pseudo-code listing).

**Comment by eyurtsev** [comment]
That sounds great!!
