### ISSUE TITLE
ValueError: Self query retriever with Vector Store type <class 'langchain_chroma.vectorstores.Chroma'> not supported.

### ISSUE THREAD

**Issue by anusonawane** [langchain-ai/langchain#22272]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code
from langchain_community.vectorstores import Chroma
vectorstore = Chroma.from_documents(docs, embeddings)

retriever = SelfQueryRetriever.from_llm(
    llm,
    vectorstore,
    document_content_description,
    metadata_field_info,
)

### Description

I'm trying to use chroma as a vectorstore but langchain says its not supported 

### System Info

langchain=0.1.20
python=3.11

**Comment by bhardwaj-vipul** [comment]
I was trying SelfQueryRetriever with [MongoDBAtlasVectorSearch](https://python.langchain.com/v0.1/docs/integrations/retrievers/self_query/mongodb_atlas/) and also faced the same issue. Upon debugging a little bit, I found out that the issue is because the [builtin translators ](https://github.com/langchain-ai/langchain/blob/8cbce684d4ec861cfd45edc4585365db81b93afd/libs/langchain/langchain/retrievers/self_query/base.py#L92) are pointing to the [deprecated](https://github.com/langchain-ai/langchain/blob/8cbce684d4ec861cfd45edc4585365db81b93afd/libs/langchain/langchain/retrievers/self_query/base.py#L65) imports. 

@anusonawane You can try this import `from langchain.vectorstores import Chroma` and it should work.

Not sure if someone is working on updating the imports.

**Comment by bhardwaj-vipul** [comment]
@anusonawane Could you please check the code you shared above? It is working fine for me. However when following the Chroma self retriever [documentation](https://python.langchain.com/v0.1/docs/integrations/retrievers/self_query/chroma_self_query/), I found the import in the doc is wrong that I also shared in my previous comment.
