### ISSUE TITLE
Issues with conversational_chat and LLM chains responding with a multi-line markdown code block

### ISSUE THREAD

**Issue by surfkansas** [langchain-ai/langchain#2241]
When using the `conversational_chat` agent, an issue occurs when the LLM returns a markdown result that has a code block included. My use case is an agent that reads from an internal database using an agent to get information that will be used to build a block of code. The agent correctly uses the tools, but fails to return an answer. 

The exhibited behavior is that the triple apostrophe used to offset the code block interferes with the json in a code block that the agent is expecting. It tries to parse the document, but stops when it finds the second triple apostrophe that starts the code block. This is because we end up with nested code blocks (the outer code block being the agent response JSON in a code block)

**Comment by krlng** [comment]
Same problem if you just try to run the router-chain example (using AzureOpenAI): https://python.langchain.com/en/latest/modules/chains/generic/router.html

**Comment by wnmurphy** [comment]
One solution would be to modify [this prompt](https://github.com/langchain-ai/langchain/blob/a28eea57674a99c6d3a20b4423d0c0e967715f00/libs/langchain/langchain/agents/conversational_chat/prompt.py#L10) so that all of the examples use quadruple backticks.

That should be transparent to any existing use case, yet preserve the use case you describe where the response contains a nested code block.

Opened a PR for this: https://github.com/langchain-ai/langchain/pull/9781
