### ISSUE TITLE
Tool `return_direct` doesn't work

### ISSUE THREAD

**Issue by BlakeQG** [langchain-ai/langchain#22441]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python

from langgraph.prebuilt import create_react_agent
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI

class CalculatorInput(BaseModel):
    a: int = Field(description="first number")
    b: int = Field(description="second number")

@tool("multiplication-tool", args_schema=CalculatorInput, return_direct=True)
def multiply(a: int, b: int) -> int:
    """Multiply two numbers."""
    return a * b

tools = [multiply]
llm_gpt4 = ChatOpenAI(model="gpt-4o", temperature=0)

app = create_react_agent(llm_gpt4, tools)

query="what's the result of 5 * 6"
messages = app.invoke({"messages": [("human", query)]})

messages

```

### Error Message and Stack Trace (if applicable)

N/A

### Description

I am following the example of https://python.langchain.com/v0.2/docs/how_to/custom_tools/ , setting `return_direct` as True, and invoke the multiplication tool with a simple agent. 

As `return_direct`  is True, I expect the tool msg is not send to LLM. But in the output (below), I still see the ToolMessage sent to the LLM, with AIMessage as `The result of \\(5 \\times 6\\) is 30.`

```
{'messages': [HumanMessage(content="what's the result of 5 * 6", id='1ac32371-4b2a-4aec-9147-bf30b6eb0f60'),
  AIMessage(content='', additional_kwargs={'tool_calls': [{'id': 'call_AslDg6NVGehW4W712neAw5xs', 'function': {'arguments': '{"a":5,"b":6}', 'name': 'multiplication-tool'}, 'type': 'function'}]}, response_metadata={'token_usage': {'completion_tokens': 20, 'prompt_tokens': 62, 'total_tokens': 82}, 'model_name': 'gpt-4o', 'system_fingerprint': 'fp_319be4768e', 'finish_reason': 'tool_calls', 'logprobs': None}, id='run-5285f886-c8b5-4ed1-a17c-ea72b4363c35-0', tool_calls=[{'name': 'multiplication-tool', 'args': {'a': 5, 'b': 6}, 'id': 'call_AslDg6NVGehW4W712neAw5xs'}]),
  ToolMessage(content='30', name='multiplication-tool', id='76d68dc3-f808-4a7c-90bc-5ae6867f141d', tool_call_id='call_AslDg6NVGehW4W712neAw5xs'),
  AIMessage(content='The result of \\(5 \\times 6\\) is 30.', response_metadata={'token_usage': {'completion_tokens': 16, 'prompt_tokens': 92, 'total_tokens': 108}, 'model_name': 'gpt-4o', 'system_fingerprint': 'fp_319be4768e', 'finish_reason': 'stop', 'logprobs': None}, id='run-5e0aaba7-dd05-45f5-9998-23b5bf77f40d-0')]}
```

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2
> Python Version:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.2.1
> langchain: 0.2.1
> langchain_community: 0.2.1
> langsmith: 0.1.63
> langchain_chroma: 0.1.1
> langchain_cli: 0.0.23
> langchain_openai: 0.1.7
> langchain_text_splitters: 0.2.0
> langchainhub: 0.1.16
> langgraph: 0.0.55
> langserve: 0.2.1

**Comment by pooriaPoorsarvi** [comment]
I have seen this problem as well. return_direct is currently supported only for single action agents, and it is used only in _get_tool_return (https://github.com/langchain-ai/langchain/blob/c01467b1f4f9beae8f1edb105b17aa4f36bf6573/libs/langchain/langchain/agents/agent.py#L1534) and not the tools them selves. and since that is a langchain package and not a langchain_core package, this would not take affect on langgraph.  


Also because it's part of the agent package, it will not cause any errors or warnings, letting the user know this will not take effect.


I have a suggestion (https://github.com/langchain-ai/langchain/pull/22327) on how to support chain (agent) termination that would work both on langchain and langsmith through callbacks, but whether that solution is used or not; a proper termination method is really needed that works with both (langchian and langgraph)I packages and works similarly for both packages.

**Comment by chaliy** [comment]
May be this issue should be migrated to langgraph repo?

**Comment by pooriaPoorsarvi** [comment]
@chaliy yea makes sense to me. it can be moved there, the sister ticket to this (which focuses on langchain) has been stale. Although I ended up fixing my issue through the use of langgraph graphs instead of langchain agents.  

@BlakeQG In case this might help, I ended up copying the source code for the vanilla react prebuilt agent of langgraph and modifying it for my own needs. I think that's the way to go because langgraph is made around graphs so you should be able to create your own custom lifecycle for an agent without having to modify the source code. so you can add in return_direct functionality by keeping track of that flag yourself (through a wrapper or something else). and then in your conditional branch "should_continue" make the graph finish. I'm sure there are other ways to implement it as well .

**Comment by chaliy** [comment]
@pooriaPoorsarvi , yep, I am also thinking that we will probably need to switch to a custom graph instead of `create_react_agent`.

**Comment by BlakeQG** [comment]
A late update, I started to use lang graph and NOT `create_react_agent`, so for me the problem is solved.

**Comment by BennisonDevadoss** [comment]
@BlakeQG , I'm using LangGraph and facing the same issue—return_direct isn't working.

Could anyone help with this?

**Comment by BlakeQG** [comment]
> [@BlakeQG](https://github.com/BlakeQG) , I'm using LangGraph and facing the same issue—return_direct isn't working.
> 
> Could anyone help with this?

I suspect the `return_direct` parameter is just working any more (deprecated?) . If you use LangGraph, just ensure the the tool is called is good enough, don't use `return_direct` thing.
