### ISSUE TITLE
Toolkits - Pandas Dataframe Agent failed to call "python_repl_ast" consistently

### ISSUE THREAD

**Issue by zhangjw71** [langchain-ai/langchain#2252]
Please ask: how many rows

> Entering new AgentExecutor chain...
Thought: I need to find the number of rows in the dataframe
**Action: python_repl_ast**
Action Input: len(df)
Observation: 45
Thought:I have the number of rows
Final Answer: 45

> Finished chain.
45

Please ask: does fg-40f support local report

> Entering new AgentExecutor chain...
Thought: We need to check if the "FG-40F Series" row has "Yes" in the "Local Reporting" column.
**Action: Use pandas boolean indexing to filter the dataframe to only the "FG-40F Series" row and check the value in the "Local Reporting" column.**
Action Input: `df[df['Product'] == 'FG-40F Series']['Local Reporting']`
Observation: Use pandas boolean indexing to filter the dataframe to only the "FG-40F Series" row and check the value in the "Local Reporting" column. is not a valid tool, try another one.
Thought:I made a mistake, I should use python_repl_ast instead of Observation.
Action: Use python_repl_ast to execute the previous input.
Action Input: `python_repl_ast(df[df['Product'] == 'FG-40F Series']['Local Reporting'])`
Observation: Use python_repl_ast to execute the previous input. is not a valid tool, try another one.
Thought:I made another mistake, I should use print() to display the result.
Action: Use python_repl_ast to execute the previous input with print().
Action Input: `python_repl_ast(print(df[df['Product'] == 'FG-40F Series']['Local Reporting']))`

**Comment by MohammedAlhajji** [comment]
are you using ChatGPT-3.5-turbo? I had this problem with this model but davinci and gpt-4 did well. it's quite odd. Quite often it'll add backticks and it'll cause a syntax error as well

**Comment by zhangjw71** [comment]
@MohammedAlhajji  Thanks for your comment. Yes, I am using ChatGPT-3.5-turbo. I will try davinci and gpt-4 as you suggested.

**Comment by MohammedAlhajji** [comment]
@zhangjw71 If you ever get ChatGPT-3.5-turbo working, let me know. I am trying with the prompt, prefix, and suffix to fix this since gpt-3.5 is 10 times cheaper, but I haven't managed to fix it. I'll let you know/make a pull request if I manage too

**Comment by zhangjw71** [comment]
@MohammedAlhajji I am kind of making a hardcode solution working with ChatGPT-3.5-turbo. It is not good for general purposes but just want to share some ideas with you.

1. I had to make a clone of 'create_pandas_dataframe_agent' function in my own code so I can pass my **FORMAT_INSTRUCTIONS** to **ZeroShotAgent.create_prompt**
2. My FORMAT_INSTRUCTIONS is set as

```
FORMAT_INSTRUCTIONS = """Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do, what action to take
Action: python_repl_ast
Action Input: the input to the action, never add backticks "`" around the action input
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question"""
```
**Action: python_repl_ast** to force LLM to pick python_repl_ast as the tool
Action Input: the input to the action, **never add backticks "`" around the action input** to tell LLM NOT to add backticks

**Comment by MohammedAlhajji** [comment]
@zhangjw71 I have tried this but I wasn't able to get consistent results. Are you getting consistent results?

**Comment by zhangjw71** [comment]
By changing 
Action: python_repl_ast
to
Action: the tool name which should be "python_repl_ast"

And clone my own **PythonAstREPLTool** to ignore surrounded backticks if any.

I can get the Python tool running quite stably. However, ChatGPT3.5-turbo failed to generate good python code consistently.

**Comment by gattaloukik123** [comment]
>    def _run(self, query: str) -> str:
        """Use the tool."""
        try:
            **query = query.replace("```","")**
            tree = ast.parse(query)
            module = ast.Module(tree.body[:-1], type_ignores=[])
            exec(ast.unparse(module), self.globals, self.locals)  # type: ignore
            module_end = ast.Module(tree.body[-1:], type_ignores=[])
            module_end_str = ast.unparse(module_end)  # type: ignore
            try:
                return eval(module_end_str, self.globals, self.locals)
            except Exception:
                exec(module_end_str, self.globals, self.locals)
                return ""
        except Exception as e:
            return str(e)

I added a query = query.replace("```", "") in the tool. This seemed to do the trick for me. Can this be added to the tool in the repo? @hwchase17

**Comment by satwikide** [comment]
Hi! Any update on the fix? The agent (using llm gpt-35-turbo) goes into a loop until max iterations is reached and throws error "Agent stopped due to iteration limit or time limit". 
![image](https://github.com/langchain-ai/langchain/assets/94559048/1a2a0d5a-f536-44df-a64a-036fec4291d3)

**Comment by aronweiler** [comment]
Yeah, this is super annoying.. because whoever wrote the `create_pandas_dataframe_agent` (as @zhangjw71 mentioned) did not do a good job, and left out the ability to pass in a prompt to override the default FORMAT_INSTRUCTIONS prompt (which is also not very good, because it is using the older [MRKL prompt here](https://github.com/aronweiler/langchain/blob/master/libs/langchain/langchain/agents/mrkl/prompt.py)).

Your choices right now are to either create your own pandas agent from scratch, or just copy and re-write the agent found in langchain.  Hopefully you do the latter and contribute back ;)

**Comment by the13thdev** [comment]
Using `agent_type=AgentType.OPENAI_FUNCTIONS` with  gpt-3.5-turbo might fix the issue

**Comment by xxm1668** [comment]
return_direct = True，response就可以获取大模型回答的结果了

**Comment by ReformedMike** [comment]
@satwikide did you come up with a solution to that problem? I have experiencing the same issue. 

I see that they are moving this to a langchain-experimental so I might be wasting my time as I am trying to work on a production solution.

**Comment by zhuofan-16** [comment]
> @satwikide did you come up with a solution to that problem? I have experiencing the same issue.
> 
> I see that they are moving this to a langchain-experimental so I might be wasting my time as I am trying to work on a production solution.

I am trying to find a solution for this as well.  Tried a few other pandas agent solution, all didnt work well unfortunately.

**Comment by RT-codes** [comment]
I ran into the same issue. It worked for me after changing the back ticks inside of the template that instructs the agent for coming up with the action from " ` " to ' . this way it picked up on the pattern and completed the response including any code examples based on that correctly. so instead of `df["Purchase"].max()` it came up with 'df["Purchase"].max()'  in my case on it's own and ran the code correctly. new to langchain  though so i'm not sure if it's that consistent. hope it helps :)

**Comment by hoan006** [comment]
Part of the problem is training data, which contains lots of code snippets surrounded with backticks. The other part is the description of PythonAstREPLTool, which does not sanitize backticks by default. I’ve managed to work around by patching langchain.agents.agent_toolkits.pandas.base._get_single_prompt to initialize PythonAstREPLTool with custom description like
“A Python shell. Use this to execute python commands. “
“Input should be a valid python command. “
“Input should be sanatized by removing any leading or trailing backticks. “
“After that, if the input starts with \”python\”, remove that word as well. “
“When using this tool, sometimes output is abbreviated - “
“make sure it does not look abbreviated before using it in your answer.”

Using gpt-4-0613, before the patch, the error loop happens 3-4 out of 10 times. But now it seems completely gone (even though the Action Input still contains leading/trailing backticks)

**Comment by calls9-amirbraham** [comment]
Having the same issue with gpt-4o , any solutions ?

**Comment by vishuhumanliai** [comment]
Yes, I'm also facing the issue with gpt-4o. It is not selecting the python_repl_ast tool even though I tried multiple good prompts from across langchain.

**Comment by mkiourlappou** [comment]
I have exactly the same issue too! Any help would be very useful :)

**Comment by HarpreetBaathTR** [comment]
I am also facing the same issue with gpt-4o.

**Comment by denisenkoaj** [comment]
same with gpt-4o, 
with what models does it work well?

**Comment by denisenkoaj** [comment]
works fine with gpt-4 (simple one without o)

**Comment by youngathpark1** [comment]
I found a quick fix. When you invoke, add this clause at the end of your query. 

Query + "Use python_repl_ast NOT [python_repl_ast]."

It works for me using GPT-4o. I'm not sure if it will work with other LLM instances.

**Comment by thomasjacob04** [comment]
> By changing Action: python_repl_ast to Action: the tool name which should be "python_repl_ast"
> 
> And clone my own **PythonAstREPLTool** to ignore surrounded backticks if any.
> 
> I can get the Python tool running quite stably. However, ChatGPT3.5-turbo failed to generate good python code consistently.

This seems to do the trick! Thank you! I'm using Groq - model Mixtral 8x7b

**Comment by teddythinh** [comment]
I'm using the Ollama model and getting this issue too. 😢
