### ISSUE TITLE
MongoDB Atlas Search Support

### ISSUE THREAD

**Issue by nathanclevenger** [langchain-ai/langchain#2274]
It appears that MongoDB Atlas Search supports Vector Search via the `kNNBeta` operator:

- https://github.com/esteininger/vector-search/blob/master/foundations/atlas-vector-search/Atlas_Vector_Search_Demonstration.ipynb
- https://www.mongodb.com/docs/atlas/atlas-search/knn-beta/

Is there anyone else that is working with or exploring MongoDB as a Vectorstore?   

If not, @hwchase17, would you be open to a pull-request?

cc: @sam-lippert and @AggressivelyMeows

**Comment by floomby** [comment]
I started working on this for in [langchainjs](https://github.com/hwchase17/langchainjs/pull/655). Ran into a couple of issues, hopefully I can get them worked out. Once these issues are addressed I will be glad to bring the python version up to parity.

It would sure be nice to be able to use existing mongodb instances as opposed to having to use something else in addition.

**Comment by Pliman** [comment]
Hi, guys，I'm using MongoDBAtlasVectorSearch(from langchain.vectorstores) to store my docs and embeddings，does anyone know how to retrieve docs and embeddings from MongoDBAtlasVectorSearch? @nathanclevenger @floomby 

I have tried
```vectorStore = MongoDBAtlasVectorSearch(collection, embedding)
    retriever = vectorStore.as_retriever()````

but I can't get any docs using `docs = retriever.get_relevant_documents(query)`, while I can get docs thought Altas UI search using a same query, I think it retrieved nothing.

**Comment by floomby** [comment]
Ok, I looked back and I think I know what the problem is. Does it work if you add metadata to the docs?

**Comment by floomby** [comment]
It sounds like it could be a problem with the index. When you ran a search query manually did you use the knnBeta operator? Also double check that there are no errors with the index and that it shows that your documents are indeed indexed (i.e. it didn't get stuck on the indexing state).

**Comment by Pliman** [comment]
Thanks @floomby 

My bad, the constructor of MongoDBAtlasVectorSearch using 3 default params:
index_name: str = "default",
text_key: str = "text",
embedding_key: str = "embedding",

In my case, index_name is not 'default'，so I should do
vectorStore = MongoDBAtlasVectorSearch(collection, embedding, index_name=index_name)

then you can using
`retriever = vectorStore.as_retriever()`
`docs = retriever.get_relevant_documents(query)`
or
`docs = docsearch.similarity_search(query)`

both works fine, because retriever.get_relevant_documents invoked similarity_search in it's implementation.

P.S. using 1536 of dimensionality is fine.

**Comment by nathanclevenger** [comment]
@Pliman it seems that MongoDB Atlas just recently raised the 1024 dimension limit to 2048, so 1536 from ada-002 now works in Mongo!

**Comment by Pliman** [comment]
Good to know.
