### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/tutorials/rag/>

### ISSUE THREAD

**Issue by speths** [langchain-ai/langchain#22826]
### URL

https://python.langchain.com/v0.2/docs/tutorials/rag/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

In section **5. Retrieval and Generation: Generate** under [Built-in chains](https://python.langchain.com/v0.2/docs/tutorials/rag/#built-in-chains) there is an error in the code example:

from **langchain.chains** import create_retrieval_chain 

should be changed to

from **langchain.chains.retrieval** import create_retrieval_chain

**Comment by baskargopinath** [comment]
@speths can u check my fix if its satisfactory for you?

**Comment by speths** [comment]
Error has been fixed.

**Comment by baskargopinath** [comment]
@speths the code and website still says

langchain.chains tho

**Comment by speths** [comment]
@baskargopinath That is true. When will your change be applied?

**Comment by baskargopinath** [comment]
i sent pull request @speths waiting for it to be reviwed u can tag the maintainers on my issue for faster reply

**Comment by speths** [comment]
Can you please write me who ist the maintainner and how can I tag them? With @ mentions?

**Comment by baskargopinath** [comment]
@speths If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, ccurme, vbarda, hwchase17.

**Comment by speths** [comment]
@baskargopinath Error has been fixed by @baskargopinath

**Comment by baskargopinath** [comment]
https://github.com/langchain-ai/langchain/pull/22843
@speths go here and tag them

**Comment by ccurme** [comment]
Can you clarify what error you get with `from langchain.chains import create_retrieval_chain`?

**Comment by baskargopinath** [comment]
@ccurme when i try it also i dont get any error. maybe i just thought it would be clearer to see where create_retrieval_chain function is if we changed the import statement

**Comment by ccurme** [comment]
Thanks, that makes sense.

The re-export is done as a convenience for developers, so people don't need to remember precisely where things are implemented in order to import and use. It also lets us move things around without requiring people to update their import statements.

The trade-off as you say is that it's less clear where things are implemented. But if a developer is interested in that they can consult the API reference or trace the import themselves.

Will close this issue for now but let me know if I've misunderstood anything.
