### ISSUE TITLE
Allow agent to choose its toolset 

### ISSUE THREAD

**Issue by jasondotparse** [langchain-ai/langchain#2374]
Currently we provide agents with a predefined list of tools that we would like to place at its disposal before it embarks on its effort to complete the task at hand. 

It might be preferable to allow the Agent to query the langchain hub / Huggingface hub repeatedly and traverse the directory of agents / tools until it finds all the tools and agents it needs to complete its mission, and then dynamically pull them in as needed. 

In the future I can imagine we have more specialized agents, perhaps some that are medical experts, business consultants, or software engineers. If we allow our "manager" agent the ability to pull in their expertise and place them on their "team" or "toolbelt" before it sets out to accomplish a task, we can leverage the LLMs ability to understand what resources will be required to accomplish some abstract task, and allow it to get what it needs before any attempt is made.

**Comment by blob42** [comment]
@jasondotparse I was trying to find a way to inject tools dynamically into agents and given the current architecture of agents in langchain it would be a bit complicated to achieve wihout chaning a bit the current implementation of agents. 

The problem lies in the fact that once and agent instance is created, the prompt including the toolset is hardcoded inside the agents' instance and adding tools does not modify the prompt. 

I started a small prototype which I might  propose as a PR which could allow dynamically injecting tools into agent instances. 

In the meantime the only solution is to regenerate the agent with the new toolset and restore the history/memory but this way seems way convuluted for this simple task.
