### ISSUE TITLE
How to customize chat model

### ISSUE THREAD

**Issue by zainabalthafeeri1** [langchain-ai/langchain#2430]
I have a use case in which I want to customize my own chat model; how can I do that?
there is a way to customize [LLM](https://python.langchain.com/en/latest/modules/models/llms/examples/custom_llm.html), but I did not find anything regarding customizing the chat model

**Comment by Tanmay3132** [comment]
can you elaborate more on that ?

**Comment by floomby** [comment]
Setting up something like `class CustomLLM(LLM):` is for when you want to get specific results and/or mocking.

I think what you are after is probably [indexes/embedding](https://docs.langchain.com/docs/components/indexing/). Which is a way to provide your data to a language model.

There is also [fine tuning](https://platform.openai.com/docs/guides/fine-tuning) which is another option.

**Comment by kikoncuo** [comment]
I think he meant just telling the framework if it should use gpt-3.5-turbo model or gpt-4 etc.

That's how I found this thread and there is nothing in the documentation:
https://python.langchain.com/en/latest/getting_started/getting_started.html
https://python.langchain.com/en/latest/modules/models/chat/integrations/openai.html

It just says do:
`chat = ChatOpenAI(temperature=0)`

To get a chat instance, it's great to have docs based on examples for newcomers, but having full docs would be nice.

I found in the code for that instantiation hoping it would be a param just like temperature and good news, it is and is called modelName !

By default it uses "gpt-3.5-turbo", but you could specify otherwise by doing 

chat = ChatOpenAI(temperature=0, modelName="gpt-4")

I don't have access yet, so if anyone could confirm that'd be great
