### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/integrations/vectorstores/google_cloud_sql_pg/> SyntaxError: 'await' outside function

### ISSUE THREAD

**Issue by ejstembler** [langchain-ai/langchain#24319]
### URL

https://python.langchain.com/v0.2/docs/integrations/vectorstores/google_cloud_sql_pg/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The code examples generate this error:

```console
 File "main.py", line 18
    engine = await PostgresEngine.afrom_instance(project_id=config.google_project_id, region=config.region, instance=config.cloud_sql_connection_name, database=config.db_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside function
```

**Comment by eyurtsev** [comment]
Run it from a notebook environment which has an event loop in it if you're trying to follow the documentation.

If you're running from `python` or `ipython`, wrap the code in an async function and execute it in an event loop. I suggest looking into resources on how to work with async code in python.

I'll close the issue since the documentation is OK.
