### ISSUE TITLE
How we can use Streaming with ChatGoogleGenerativeAI along with message history

### ISSUE THREAD

**Issue by DimensionZer0** [langchain-ai/langchain#24706]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Description

In below code i am not getting any option to use stream , So kindly suggest how i can implement Streaming 

this code is in a Node of State Agent 

model = ChatGoogleGenerativeAI(model="gemini-pro", convert_system_message_to_human=True,temperature=.20)         runnable = chat_message_prompt | model
        with_message_history = RunnableWithMessageHistory(
            runnable,
            get_session_history,
            input_messages_key="input",
            history_messages_key="history"
        )
        print("********PROMPT TEST********", chat_message_prompt, "*******************")
        response = with_message_history.invoke(
              {"ability": "teaching", "input": prompt},
                config={"configurable": {"session_id": phone_number}},
            )
        print("******* RESPONSE FROM GEMINI PRO = ", response.content, "*******")
        answer = [response.content]

**Comment by mikhailocampo** [comment]
@DimensionZer0 

For implementing Streaming, I believe you can [follow the example described here in the docs](https://api.python.langchain.com/en/latest/chat_models/langchain_google_genai.chat_models.ChatGoogleGenerativeAI.html)
^^ In this case, I am invoking the LLM itself and pass messages rather than the runnable

If you want to use the runnable like how you've instantiated the `RunnableWithMessageHistory`, I believe you can use the `stream` [method as mentioned here.](https://api.python.langchain.com/en/latest/runnables/langchain_core.runnables.history.RunnableWithMessageHistory.html#langchain_core.runnables.history.RunnableWithMessageHistory)
^^ Then in this case, you would need to consume the stream differently since you are simply setting a response to equal the output of `invoke` in your current code, it would need to loop through the stream to "consume" the iterator and see the streamed output.

**Comment by DimensionZer0** [comment]
Thanks I am able to solve issue by below code 

model = ChatGoogleGenerativeAI(model="gemini-pro", convert_system_message_to_human=True,temperature=.20,stream=True) #gemini-1.5-pro-latest
        from langchain_core.output_parsers import StrOutputParser

        runnable = chat_message_prompt | model | StrOutputParser()
        with_message_history = RunnableWithMessageHistory(
            runnable,
            get_session_history,
            input_messages_key="input",
            history_messages_key="history"
        )
        print("***PROMPT TEST**", chat_message_prompt, "******")
        #response = await model.ainvoke(messages, config)
        response=await with_message_history.ainvoke(
              {"ability": "teaching", "input": prompt},
                config={"configurable": {"session_id": phone_number}},
            )
        print("Output ",response)
