### ISSUE TITLE
Incorrect Import Statement DOC: <Issue related to /v0.2/docs/integrations/tools/tavily_search/>

### ISSUE THREAD

**Issue by tapaswi-v-s** [langchain-ai/langchain#25256]
### URL

https://python.langchain.com/v0.2/docs/integrations/tools/tavily_search/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

In the [installation](https://python.langchain.com/v0.2/docs/integrations/tools/tavily_search/#instantiation) part of the TavilySearch the import of the TavilySearchResults is wrong. 

### Idea or request for content:

The import should be ```from langchain_community.tools.tavily_search import TavilySearchResults``` instead of ```from langchain_community.tools import TavilySearchResults``` (missing ```.tavily_search``` after **tools**)

**Comment by ccurme** [comment]
Thanks for this. This was fixed in https://github.com/langchain-ai/langchain/pull/24736 and will be released in the next version of langchain-community.

After release the existing import in the docs will work as TavilySearchResults is properly exported from `tools.__init__`: https://github.com/langchain-ai/langchain/blob/a82c0533f206548e0ebbdb1a8603e0d9a2eac370/libs/community/langchain_community/tools/__init__.py#L470
