### ISSUE TITLE
add in method for getting confidence

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langchain#266]
https://arxiv.org/pdf/2207.05221.pdf

should be a separate LLMchain with a prompt that people can add on at the end

**Comment by JohnNay** [comment]
Basic prompt/chain:

```
Question: Who was the first president of the United States?
Answer:
```

```
Question: Who was the first president of the United States?
Proposed Answer: George Washington was the first president.
```

```
Is the proposed answer:
(A) True
(B) False
The proposed answer is:
```

**Comment by JohnNay** [comment]
"improve performance further by showing the model other T = 1 samples, for comparison"

```
Question: Who was the third president of the United States?
Here are some brainstormed ideas: James Monroe
Thomas Jefferson
John Adams
Thomas Jefferson
George Washington
Possible Answer: James Monroe
Is the possible answer:
(A) True
(B) False
The possible answer is:
```

"Overall, if given a few examples from a given distribution, models can generate samples and then self-evaluate
them to productively differentiate correct and incorrect samples, with reasonably calibrated confidence."

**Comment by JohnNay** [comment]
We should have this play nicely with the self-ask-search agent because that is a key use case here is tying together (1) ability to ask one itself questions and search the web for facts with (2) ability to provide well-calibrated responses. 

Probabilistically calibrated confidence levels of the model in answers to questions + drawing information for the answer from trusted sources like key websites/databases, will be a combined major unlock in making Agents more usable for important tasks.
