### ISSUE TITLE
BadRequestError: Error code: 400 - {'error': {'message': 'Input required: specify "prompt"', 'code': 400}, 'user_id': 'user_2egJVLT61dw0Z9NPjilqjNjFkh9'}

### ISSUE THREAD

**Issue by phpmac** [langchain-ai/langchain#28467]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_openai import OpenAI

llm = OpenAI()

response = llm.invoke(input="Hello how are you?")  # 正确

### Description

from langchain_openai import OpenAI

llm = OpenAI()

response = llm.invoke(input="Hello how are you?")  # 正确

### System Info

from langchain_openai import OpenAI

llm = OpenAI()

response = llm.invoke(input="Hello how are you?")  # 正确

**Comment by ccurme** [comment]
Instead of specifying `input=`, you should just pass the string as a positional arg to `invoke`. See documentation [here](https://python.langchain.com/docs/integrations/llms/openai/). Let me know if this does not solve your problem.

Note also the warning at the top of that page regarding the use of legacy text-completion models (`OpenAI`) vs. modern chat models (`ChatOpenAI`). In most cases you want to use `ChatOpenAI`.
