### ISSUE TITLE
DOC: current doc about MLX-LM is wrong

### ISSUE THREAD

**Issue by svnv-svsv-jm** [langchain-ai/langchain#28532]
### URL

https://python.langchain.com/docs/integrations/chat/mlx/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Ran all cells in the notebook and the very last one got me an error:

`TemplateError: System role not supported`

### Idea or request for content:

Provide a working example.

**Comment by asdkfjsd** [comment]
Hello, are you working on this? If not, I am happy to take this task!

**Comment by ZhangShenao** [comment]
Try to fix this in https://github.com/langchain-ai/langchain/pull/28884

**Comment by lilyTokens** [comment]
I ran into the same issue on a project last week. The root cause in our case was missing a clear quality target in the original brief -- once we defined what working correctly actually meant with a specific metric, the path forward became much clearer. Wrote up the approach here if it is useful: https://agentskills-app.surge.sh/ai-requirements-writing.html
