### ISSUE TITLE
Add support for memory selection by length or other features (e.g. semantic similarity)

### ISSUE THREAD

**Issue by sjwhitmore** [langchain-ai/langchain#287]
We need an analogous structure to LengthBasedExampleSelector but for Memory. MemorySelector? This would provide an interface which would allow some mutation of the Memory if max context window is reached (& perhaps upon other conditions as well)

**Comment by sjwhitmore** [comment]
Addressed to some extent w/ ConversationBufferWindowMemory PR... not sure if we need more abstraction here. thoughts?

**Comment by hwchase17** [comment]
i think adding a buffer window not based on a fixed N conversations but rather on the length of the conversations is a pretty natural/easy extension. after that, should be good!

**Comment by shoelsch** [comment]
This might be related to a new issue I created: https://github.com/hwchase17/langchain/issues/296

**Comment by hwchase17** [comment]
> This might be related to a new issue I created: #296

hah i think your issue is much more comprehensive solution than what i was suggesting! i think yours is a great combination of multiple different memory methods, i was thinking just a last N line approach (no summarization or anything) but N varies depending on the length. 

i think your issue is a much more comprehesnive solution, but i can see value in both
