### ISSUE TITLE
AnalyzeDocumentChain cannot work with "text-ada-001" model or any 2k tokens model

### ISSUE THREAD

**Issue by skittoo** [langchain-ai/langchain#2930]
In "combine_docs" in "MapReduceDocumentsChain" class in "langchain/chains/combine_documents/map_reduce.py"

num_tokens is defaulted to 3000 not flexible to the model type.

**Comment by timothyasp** [comment]
I ran into this problem as well - ideally we could extract the LLM used as part of `BaseCombineDocumentsChain`, and use the `get_num_tokens` method plus a new `max_tokens` method on `BaseLanguageModel`.  `OpenAI` has this with `modelname_to_contextsize`, but not others as far as I can tell, so it should be straight forward to abstract this bit out.


One thought - It'd make things a lot simpler to just make `BaseCombineDocumentsChain` inherit from LLMChain, that way we wouldn't have to do any type checking and fallback in the combine_docs code and it'd clean up things quite a bit.

Is there a lot of known use cases around using non-llm chains with combining documents?

**Comment by timothyasp** [comment]
Happy to throw this change together since this is broken with what i'm working on, and i've got a fork maintained with this hacked together work around.

@hwchase17  - Since it'd be a breaking change making `BaseCombineDocumentsChain` depend on `LLMChain`, i'm interested in your thoughts before I go down this path.
