### ISSUE TITLE
Add support for naming the AI entity differently (other than "AI", which seems to be hardcoded)

### ISSUE THREAD

**Issue by shobith** [langchain-ai/langchain#295]
This will allow the LLMs to hold on to previous commands.

**Comment by hwchase17** [comment]
sorry im not sure i see the connection... how does this relate to holding onto previous commands?

**Comment by hwchase17** [comment]
Ah i see. So you are using the name "Jeeves" in the prompt? like instead of using the default of 
```
"""The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.
Current conversation:
{history}
Human: {input}
AI:"""
```
you used something like
```
"""The following is a friendly conversation between a human and Jeeves. Jeeves is talkative and provides lots of specific details from its context. If Jeeves does not know the answer to a question, it truthfully says it does not know.
Current conversation:
{history}
Human: {input}
Jeeves:"""
```

If that is the case, then yes i think this makes a ton of sense! Can probably expose some optional params like "llm_output_name" and "input_name" which default to "AI" and "Human" respectively (to maintain current functionality)

If this isnt what you meant though please let me know, I'd love to know for sure
