### ISSUE TITLE
Difference between "Question Answering with Sources" and "Question Answering"

### ISSUE THREAD

**Issue by 19245222** [langchain-ai/langchain#3073]
I notice they use different API, but what's the difference between these 2 apis?

Question Answering:
docs = docsearch.get_relevant_documents(query)

Question Answering with Sources:
docs = docsearch.similarity_search(query)

**Comment by tsclausing** [comment]
(I am new to LangChain so please forgive any mistakes, just trying to help and learn at the same time. 😄)

Is this question about the subtle difference in "Prepare Data" section of these two notebooks?

- https://github.com/hwchase17/langchain/blob/master/docs/modules/chains/index_examples/question_answering.ipynb
- https://github.com/hwchase17/langchain/blob/master/docs/modules/chains/index_examples/qa_with_sources.ipynb

In the "question_answering" notebook, `docsearch` is a `VectorStoreRetriever`: 
- `docsearch = Chroma.from_texts(...).as_retriever()`
 
In the "qa_with_sources" notebook, `docsearch` is a `VectorStore`
- `docsearch = Chroma.from_texts(...)`

In these specific examples there is no difference, as the Chroma `VectorStoreRetriever#get_relevant_documents()` method simply proxies to `self.vectorstore.similarity_search()` unless the default `search_type` is overridden.


In general, it appears the intent may be for `VectorStore`s which support multiple retrieval methods (in addition to vector similarity) to override `as_retriever()` in order to provide an implementation of `get_relevant_documents()` with all supported `search_type`s.

Redis, for example: https://github.com/hwchase17/langchain/blob/e3cf00b/langchain/vectorstores/redis.py#L424-L457

**Comment by Lukangkang123** [comment]
> (I am new to LangChain so please forgive any mistakes, just trying to help and learn at the same time. 😄)
> 
> Is this question about the subtle difference in "Prepare Data" section of these two notebooks?
> 
> * https://github.com/hwchase17/langchain/blob/master/docs/modules/chains/index_examples/question_answering.ipynb
> * https://github.com/hwchase17/langchain/blob/master/docs/modules/chains/index_examples/qa_with_sources.ipynb
> 
> In the "question_answering" notebook, `docsearch` is a `VectorStoreRetriever`:
> 
> * `docsearch = Chroma.from_texts(...).as_retriever()`
> 
> In the "qa_with_sources" notebook, `docsearch` is a `VectorStore`
> 
> * `docsearch = Chroma.from_texts(...)`
> 
> In these specific examples there is no difference, as the Chroma `VectorStoreRetriever#get_relevant_documents()` method simply proxies to `self.vectorstore.similarity_search()` unless the default `search_type` is overridden.
> 
> In general, it appears the intent may be for `VectorStore`s which support multiple retrieval methods (in addition to vector similarity) to override `as_retriever()` in order to provide an implementation of `get_relevant_documents()` with all supported `search_type`s.
> 
> Redis, for example: https://github.com/hwchase17/langchain/blob/e3cf00b/langchain/vectorstores/redis.py#L424-L457

I noticed that "Question Answering with Sources" and "Retrieval Question Answering with Sources" use different chains: "load_qa_with_sources_chain" and "RetrievalQAWithSourcesChain". So, what's the difference between them?
[https://python.langchain.com/en/latest/modules/chains/index_examples/vector_db_qa_with_sources.html](https://python.langchain.com/en/latest/modules/chains/index_examples/vector_db_qa_with_sources.html)
[https://python.langchain.com/en/latest/modules/chains/index_examples/qa_with_sources.html](https://python.langchain.com/en/latest/modules/chains/index_examples/qa_with_sources.html)

**Comment by ehsanmok** [comment]
* To use `chain = load_qa_with_sources_chain(...)`, first you need to have an index/docsearch and for `query` get the `docs = docsearch.similarity_search(query)` to use `chain({"input_documents": docs, "question": query}`.
* `RetrievalQAWithSourcesChain` is more compact version that does the `docsearch.similarity_search` etc. under the hood and has extra parameters like `reduce_k_below_max_tokens` and `max_tokens_limit` to better control the token usage when doing retrieval.

**Comment by Qualzz** [comment]
is there any reason why the default prompt for QA with source is soooo huuuuge ? 
https://github.com/hwchase17/langchain/blob/master/langchain/chains/qa_with_sources/stuff_prompt.py

Or are we supposed to change it for our use case in any case ?

**Comment by annjawn** [comment]
I am equally confused at this as well the default prompt seems quite large for `load_qa_with_sources_chain`. I tried my own prompt template to override the prompt and at the very basic, it works, but I am looking to use [Structured Output Parser](https://python.langchain.com/en/latest/modules/prompts/output_parsers/examples/structured.html) with the `load_qa_with_sources_chain`, and the output is unreliable i.e. most of the time it just responds back with the default `{'output_text': 'This is a response'}` and a few other times it uses the `ResponseSchema`. I just can't make these two work together.

**Comment by LoveFishoO** [comment]
Actually, I also confused at this. The default prompt of `load_qa_with_sources_chain` is very different with `load_qa_chain`. In my task, I found the performance of `load_qa_chain` is better than `load_qa_with_sources_chain`. I guess the default prompt of `load_qa_with_sources_chain`  make model consider more than one document. I am not sure😂
