### ISSUE TITLE
Error using TimeWeightedVectorStoreRetriever.get_relevant_documents with FAISS: 'FAISS' object has no attribute 'similarity_search_with_relevance_scores'

### ISSUE THREAD

**Issue by nomeyer** [langchain-ai/langchain#3167]
I'm exploring [this great notebook](https://python.langchain.com/en/latest/use_cases/agent_simulations/characters.html) and trying to produce something similar, however I get an error when `fetch_memories` calls `self.memory_retriever.get_relevant_documents(observation)`:

```
AttributeError: 'FAISS' object has no attribute 'similarity_search_with_relevance_scores'
```

I'm running `langchain` `0.0.144` and I've installed `faiss` using `conda install -c conda-forge faiss-cpu` (as indicated [here](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md)) which installed version `1.7.2`. Also running python `3.10`.

Poking inside `faiss.py` I indeed can't find a method called `similarity_search_with_relevance_scores`, only one called `_similarity_search_with_relevance_scores`.

Which version(s) of `langchain` and `faiss` should I be running for this to work?

Any help would be greatly appreciated, thanks 🙏

**Comment by Ryangr0** [comment]
Same here using Weaviate. And that's not all. The example for "vectorstores" and babyagi for example flat out does not work because the core of langchain isn't keeping track of the new features put in and make sure the old functionality still works. PRs without a single automated test are getting merged to master. The ones that do have tests don't cover the example code in the notebook. I like jupyter but it's getting way overused by everyone at the moment. It's not a substitute for documentation or a real life functioning example. At this moment the dev experience at the moment is not great, because with every error I get I don't know if it's my code, or langchain that's causing the issue.

**Comment by nomeyer** [comment]
Hey @Ryangr0 for what it's worth I managed to resolve my issue by re-installing all my dependencies in a fresh conda environment 😅

**Comment by Ryangr0** [comment]
This is actually still not working for me, and I know why. Weaviate doesn't have this implemented either. Is there any way for me to get this under attention?

**Comment by nomeyer** [comment]
I'm no longer facing this issue, thanks. Not sure about @Ryangr0.
