### ISSUE TITLE
Model's maximum context length exceeded when building agent

### ISSUE THREAD

**Issue by kingcharlezz** [langchain-ai/langchain#3838]
I'm trying to use the GPT model to interact with the Google Calendar API, but I'm receiving the following error message:

"This model's maximum context length is 4097 tokens. However, your messages resulted in 4392 tokens. Please reduce the length of the messages."

https://gist.github.com/kingcharlezz/e820bc60febef084402cb2a68f3aeeb0

Could someone please help me find a way to avoid exceeding the model's maximum context length, or suggest alternative approaches to achieve the same functionality without encountering this issue? Any help would be greatly appreciated.

**Comment by clemlesne** [comment]
Seems related to https://github.com/langchain-ai/langchain/issues/1349.

**Comment by dmyoung9** [comment]
Send less tokens or use a model with a larger context limit. This is more of a prompt engineering issue than a `langchain` issue.

You could use summarize chains to reduce the number of tokens in your context down to something manageable, but this is also tricky, because the summarize chain still needs to load the full context into its window at least once, and the more summaries need to be done, the larger the final context will be anyways.
