### ISSUE TITLE
[Feature Request] Fallback to run from arun

### ISSUE THREAD

**Issue by whitead** [langchain-ai/langchain#4025]
I prefer async LLM calls in my code, but need fallbacks for LLMs that do not support. My code lets users supply their own LLMs. 

It would be nice to automatically do this fallback to `run` if `arun` will not work with the given LLM. Something like `mychain.arun(..., fallback=True)`. 

The work around I use is below:
```py
class FallbackLLMChain(LLMChain):
    """Chain that falls back to synchronous generation if the async generation fails."""
    async def agenerate(
        self,
        input_list: List[Dict[str, Any]],
        run_manager: Optional[AsyncCallbackManagerForChainRun] = None,
    ) -> LLMResult:
        """Generate LLM result from inputs."""
        try:
            return await super().agenerate(input_list, run_manager=run_manager)
        except NotImplementedError as e:
            return self.generate(input_list, run_manager=run_manager)

```

It might be useful in repo though.

**Comment by hwchase17** [comment]
@agola11 @nfcampos thoughts on adding something like this base chain class? could raise a specific AsyncNotImplementedError or something?

**Comment by agola11** [comment]
We really should not be doing blocking calls in async coroutines as it blocks the main runloop. A better approach would be `loop.run_in_executor`. I think instead of having a dedicated fallback chain, we can just make the default implementation of `agenerate` use run_in_executor to call the sync method. This is what I did with vector stores for example: https://github.com/hwchase17/langchain/blob/f3ec6d2449f3fe0660e4452bd4ce98c694dc0638/langchain/vectorstores/base.py#L145

Ideally, all most LLMs/blocking stuff move towards having actual async implementations as that is usually way better than awaiting `run_in_executor` (no worries about thread safety, easer to debug, better error propagation, etc).

**Comment by hwchase17** [comment]
lets make that the default method then! better than breaking
