### ISSUE TITLE
Prompt Stress Testing

### ISSUE THREAD

**Issue by paperMoose** [langchain-ai/langchain#4119]
How confident are you in your prompts? Since LLM's are non deterministic there's always a chance of failure, even using the same prompt template and input variables. How do we stress test prompt templates and their input variables to understand how often they complete successfully? There's no easy way atm. Let's change that.

This feature set will help us ensure that our prompts work well in various situations (like unit test cases) and can transform inputs to some criteria, like output to a JSON spec. In this context, a confidence score refers to the measure`prompt_success/total_llm_executions` where success is defined by an objective measure like output format or values within the output.

For instance, we could expect a prompt to produce a parsable JSON output, or certain structured values, and use that test for calculating its confidence score. The confidence score will enable us to easily show the success/number of runs ratio for a given prompt, which will help us identify which prompts are most effective and prioritize their use in production. The scores would then be displayed in a similar manner to coverage.py in a local html file, with saved files for the prompt in question and it's score. 

This would also be extendable for use in agents as well, but that will be a separate issue.

**Comment by glide-the** [comment]
I feel like I can use this to rewrite the langchain to the act structure, and wrapping it with the JSON structure would be more accurate
https://github.com/1rgs/jsonformer

**Comment by ju-bezdek** [comment]
BTW... this is exactly the thing that [PromptWatch](www.promptwatch.io) is doing... you can define a set of test cases for a particular prompt OR a whole session (define on your own or label historical trace logs) and run unit tests against them ... measuring cosine similarity and the overall drift...
[Unit Testing for LangChain🦜🔗 using PromptWatch (in just 3 lines of code)](https://medium.com/@juraj.bezdek/unit-testing-for-langchain-using-promptwatch-in-just-3-lines-of-code-921b43b3e746)

Although it doesn't particularly cover JSON parsability (didn't have many problems with this one... most of the problems can be fixed by simple regex and if not just ask GPT to fix it) but it's very easy to add your own evaluator there.

... just for the record, I'm the creator of PromptWatch... but I've built it to solve my own problems and decided to share it for free with others...

**Comment by willmoik** [comment]
@ju-bezdek so promptwatch is completely free? Quickly looking at the docs, it looks like the prompts and responses are stored and hosted elsewhere. How can this be free?

**Comment by ju-bezdek** [comment]
Yes, currently its free for general use. We are planning to introduce paid plans for more intense loads, SLA etc, but we always want to have a free plan with limited retention and load. But for now, it's completely free.
