### ISSUE TITLE
How to reduce prompt with too many tools

### ISSUE THREAD

**Issue by lixincheng4026** [langchain-ai/langchain#4217]
### Issue you'd like to raise.

I am using chain wiht ConversationBufferMemory. I have defined about 50+ tools with detailed description。So the prompt to GPT is likely over 4096 tokens within 4 loops. How can i reduce my prompts or increase the max tokens of GPT. Is there any ideas?

**Comment by amogkam** [comment]
Perhaps try out compress gpt: https://github.com/yasyf/compress-gpt

It seems to be built for exactly this use case.

**Comment by sd1219** [comment]
You can use ConversationBufferWindowMemory, but this will essentially reduce your short-term memory, given the large number of tools. You can also use VectorStoreRetrieverMemory so that the agent only accesses the previous information from the conversation as required. I think the second option is more useful in your case.

https://python.langchain.com/en/latest/modules/memory/types/vectorstore_retriever_memory.html

**Comment by vnktsh** [comment]
@lixincheng4026 Don't load all the 50+ tools into the prompt. Use ToolRetriever and let it load only relevant tools into the main prompt. This way you'll leave more room for conversation history.

**Comment by dmyoung9** [comment]
@lixincheng4026 The docs for @vnktsh's answer are here: https://python.langchain.com/docs/modules/agents/how_to/custom_agent_with_tool_retrieval

This issue can probably be closed.
