### ISSUE TITLE
AzureOpenAI can't support other model like text-davinci-003

### ISSUE THREAD

**Issue by jacobjiangwei** [langchain-ai/langchain#4453]
### System Info

    llm = AzureChatOpenAI(deployment_name="JacobTextDavinci03", model_name="text-davinci-003", max_tokens=1500)

  File "C:\Users\jwei\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found

It works well if I use gpt-3.5-turbo model. So I'm guessing it's something wrong with openai library that can't support text-davinci-003 ?

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

It's quite easy to reproduce.
Just use follow example here : https://python.langchain.com/en/latest/modules/models/llms/integrations/azure_openai_example.html

And it just won't work for other model except 3.5 gpt turbo.

### Expected behavior

it should support azure all kinds of model there.

**Comment by zioproto** [comment]
Only the `gpt-3.5-turbo` and `gpt-4` models are chat models and support using the Chat API via `llm = AzureChatOpenAI(......)`.

The other models are completion models, you should use the Completion API with `llm = AzureOpenAI(....)`

Review the python examples here:

* https://learn.microsoft.com/en-us/azure/cognitive-services/openai/quickstart?pivots=programming-language-python&tabs=command-line
* https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?pivots=programming-language-python&tabs=command-line

Please check closely the difference between `openai.Completion.create` and `openai.ChatCompletion.create` in the 2 documentation pages 

Please let me know if you have questions.

**Comment by vincentteyssier** [comment]
I use gpt-35-turbo and I still have the issue

**Comment by zioproto** [comment]
@vincentteyssier if you get the error `openai.error.InvalidRequestError: Resource not found` it means that the API call is returning a HTTP 404.

Please double check the model_name and deployment_name and the `api_base` if you configured a custom DNS.

You want to make sure you are making the HTTP request to the correct API endpoint.

**Comment by vincentteyssier** [comment]
Thanks, I found out what the issue is.
On Azure Portal, the API version mentioned is 0301. With that settings it does not work.
If I use '2023-03-15-preview' instead, then it works.
Funny I get this issue only with AzureChatOpenAI, but not with AzureOpenAI

**Comment by zioproto** [comment]
> Funny I get this issue only with AzureChatOpenAI, but not with AzureOpenAI

It is because only `AzureChatOpenAI` requires `openai_api_version`.
https://github.com/hwchase17/langchain/blob/5cfa72a130f675c8da5963a11d416f553f692e72/langchain/chat_models/azure_openai.py#L46

Look at `AzureOpenAI`, it wants only the `deployment_name`:
https://github.com/hwchase17/langchain/blob/5cfa72a130f675c8da5963a11d416f553f692e72/langchain/llms/openai.py#L571-L588

This is because `AzureOpenAI` extends the class `BaseOpenAI`:
https://github.com/hwchase17/langchain/blob/5cfa72a130f675c8da5963a11d416f553f692e72/langchain/llms/openai.py#L123
that is never setting the API version when using the OpenAI python module:

https://github.com/hwchase17/langchain/blob/5cfa72a130f675c8da5963a11d416f553f692e72/langchain/llms/openai.py#L227-L235

so when you use `AzureOpenAI` you are reading the API version from the environment variable `OPENAI_API_VERSION`
