### ISSUE TITLE
The scores of `similarity_search_with_score` are not standardized across Vector Stores

### ISSUE THREAD

**Issue by acalatrava** [langchain-ai/langchain#4517]
### System Info

LangChain 0.0.165 on Google Colab

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Just try to use FAISS and the Pinecone with the same data. After query with `similarity_search_with_score` the score is reversed.

FAISS
```
docs = faiss_index.similarity_search_with_score("text to search", k=5)
for doc in docs:
    score = doc[1]
    page_num = doc[0].metadata['page']
    print(str(score) + " - " + page_num)

0.31319273 - 58
0.34054485 - 61
0.39556867 - 36
0.40675405 - 60
0.40916008 - 33
```

Pinecone
```
docs = faiss_index.similarity_search_with_score("text to search", k=5)
for doc in docs:
    score = doc[1]
    page_num = doc[0].metadata['page']
    print(str(score) + " - " + page_num)

0.843403578 - 58.0
0.82972753 - 61.0
0.80216819 - 36.0
0.79670471 - 60.0
0.795202613 - 33.0
```

### Expected behavior

All Vector Stores should use the same scoring

**Comment by acalatrava** [comment]
related to #2845

**Comment by sergedc** [comment]
For Chroma, the scores are numbers above 1. In ascending order: 
1.21817
1.225833
1.227054

**Comment by guofenging** [comment]
> For Chroma, the scores are numbers above 1. In ascending order: 1.21817 1.225833 1.227054

same problem with faiss

**Comment by AndreaArmx** [comment]
Unfortunately, the issue remains unresolved. When employing Pinecone with the 'cosine' distance strategy, the following scenario unfolds:

Upon invoking the _select_relevance_score_fn method, we enter the initial if condition, as follows:


```
if self.distance_strategy == DistanceStrategy.COSINE:
     return self._cosine_relevance_score_fn
```


The definition of _cosine_relevance_score_fn is as follows:

```
@staticmethod
def _cosine_relevance_score_fn(distance: float) -> float:
    """Normalize the distance to a score on a scale [0, 1]."""
    return 1.0 - distance
```
    
However, since Pinecone interprets higher scores as indicating greater similarity, this function reverses the values, causing the highest similarities to become the lowest.

The core issue arises from the subsequent comparison involving the similarity_threshold:

```
if score_threshold is not None:
    docs_and_similarities = [
        (doc, similarity)
        for doc, similarity in docs_and_similarities
        if similarity >= score_threshold
    ]
```

As a result, the valid matches, now having the lowest similarity values, get filtered out, while the less similar ones are retained and returned.
