### ISSUE TITLE
Add permission model to tools (simple sudo like at first)

### ISSUE THREAD

**Issue by thompsonson** [langchain-ai/langchain#4912]
### Feature request

# Example

I have a tool that has access to my email. This tool is used by a long running agent. I'd like the tool to have long standing Read permissions but only have short lived Write permissions. 

Like Githubs sudo permission, I'd like a message sent to a designated device, email, or similar, asking for authorization. 

# Reality

Some of these actions maybe outside the design scope of LangChain. However, my mind goes towards a refining of the _run method within a tool. The _run method could accept an object which is responsible for getting approval or simply returning true. 

As a pattern I think of dependency injection more than callbacks but wonder if that could work or it is just semantic difference. 

### Motivation

Motivation is simply to secure the use of tools. After regulation of the underlying LLMs I think this is the next largest risk.  

I think it talks to ~~Ben (sorry I forget his surname)~~ EDIT: got the gents name wrong, his name is Simon Wilson ( https://simonwillison.net/2023/May/2/prompt-injection-explained/)  recent concerns and suggestion to have two LLMs, one freely accessible the other privileged and has input sanitized.

There is a lot of value in the thought and pattern, it feels more practical to start with permissions, especially in a "zero trust world".

### Your contribution

Happy to help in multiple ways, time based.

Immediately to discuss and document the risks, threats, and previous solutions.

Immediately to peer review MRs. 

Mid-Longer term (i.e. on the back of a decent to do list) start to code a solution.

**Comment by thompsonson** [comment]
Hello Dosu,

Yes, this is still relevant for me. I have two use cases:

1. A personal AI assisstant: I give the AI assistant access to my email (e.g. permissions to read and send email), however I wish to mitigate the risk that it sends emails I do not wish to be sent. This is to avoid simple mistakes in the intent of my query to the AI assistant and the more serious issue of my AI assistant being compromised (directly or jailbroken). If it is the later, yes my email content is compromised, however they are not able to send any emails (further exasberating the indicent).

2. I have some data that is very private, e.g. health records or legal documents, this is stored in a place where the agent can get access to a one time token and read the files. I'd like to be able to authorise the agent to get a temporary access to these documents.

What do you think?

Best wishes,
Matt

**Comment by thompsonson** [comment]
I'm not looking to re-open this specific issue, however Ive had time to look into the work I believe is required for me to start on.

here is my initial 1Pager: https://docs.google.com/document/d/1PTPDrWyEwogZh_qO_6d6ZUPM2t82Fzj9c5D_UZZHL7s/edit?usp=sharing

If feedback/review is possible please do share 😁

**Comment by uchibeke** [comment]
This issue is still very much relevant — the permission model for tools problem has only gotten more urgent as LangChain agents get deployed in production with access to email, databases, and external APIs.

For anyone landing here: a LangChain integration for this exact pattern now exists.

**[APort Agent Guardrails](https://github.com/aporthq/aport-agent-guardrails)** implements a pre-action authorization layer for LangChain tools. The integration lives at [`packages/langchain/`](https://github.com/aporthq/aport-agent-guardrails/tree/main/packages/langchain) in the repo. It wraps LangChain tool calls with a `before_tool_call` hook that evaluates a YAML policy before any tool executes — the pattern @thompsonson described (long-lived read permissions, short-lived write permissions, out-of-band approval for sensitive operations) is exactly what OAP policy supports.

The underlying spec — the [Open Agent Protocol (OAP)](https://github.com/aporthq/aport-spec) — is a DOI-archived open standard ([doi.org/10.5281/zenodo.18901596](https://doi.org/10.5281/zenodo.18901596)), so this isn't a proprietary lock-in: it's a portable permission model that works the same way across LangChain, CrewAI, n8n, Claude Code, Cursor, and OpenClaw.

The key design decision that makes this different from prompt-level "ask before acting" instructions: enforcement runs at the runtime/framework level, not in the model response. Prompt injection can instruct an agent to skip a prompt-layer confirmation step. A `before_tool_call` hook at the framework level cannot be bypassed by model output — the platform calls it for every tool invocation regardless of what the model says.

We'd be happy to submit a PR adding the LangChain integration to LangChain's contrib packages. The implementation is already built and tested — it would just be a matter of packaging it in a way that fits LangChain's contribution guidelines.

Guardrails repo (incl. LangChain package): https://github.com/aporthq/aport-agent-guardrails  
OAP spec: https://github.com/aporthq/aport-spec  
DOI: https://doi.org/10.5281/zenodo.18901596

**Comment by uchibeke** [comment]
Hi all, I opened an issue to unify this and allow users pick their own guardrail provider https://github.com/openclaw/openclaw/issues/46441

**Comment by maxsnow651-dev** [comment]
Alright thank u for the information
