### ISSUE TITLE
FLARE | Add CombineChain to handle long context

### ISSUE THREAD

**Issue by jordanparker6** [langchain-ai/langchain#4943]
### Feature request

FLARE is providing some more accurate output when it works. I would love to switch to it. However, I do find that it often breaches the 4k context length. 

I still don't have GPT4 access because I am a pleb (approve me plz OpenAI).

The stuff / map-reduce / refine chains used in the retrieval QandA would be great here. The FLARE chain looks like it is doing something akin to the "stuff" chain by just concatenating all the documents it found. 

It would be nice if the LLMCombine chain was optional and defaulted to "stuff" like the retrieval chains do. This could be an option to handle context window issues when using FLARE. Ideally the same API followed, were users just pass the "chain_type" kwarg. 

The 4k context window is unfortunately making FLARE unworkable.

P.S. also interested in seeing if sources could be added to FLARE.

### Motivation

I want to switch my retreival chain to be FLARE based (ideally with sources in the future). However, the context window limitations are making it unworkable at the moment. I am not even using chat_history.

### Your contribution

Happy to work with someone on this to raise a PR.

**Comment by dev2049** [comment]
hey @jordanparker6, could def see context size being an issue. Two quickest fixes / improvements i can think of would be:
1. whatever retriever you're using, trying wrapping it in a ContextualCompressionRetriever. this wouldn't require checking in any changes. more on compression retriever here: https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/contextual-compression.html
2. we should probably add some check on the length of the docs. simplest thing would be to just chop off the docs string beyond some token limit. for certain models (mostly thinking of OpenAI here) we can explicitly check the model context size and compare that to prompt size. but since we don't have that for all models maybe we just add a max_prompt_size parameter to FlareChain and if that's specified then we use it to enforce that context size isn't exceeded
