### ISSUE TITLE
Weaviate: Add support for other vectorizers in hybrid search

### ISSUE THREAD

**Issue by hsm207** [langchain-ai/langchain#5300]
### Feature request

We should add support for the following vectorizers in the [weaviate hybrid search](https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/weaviate-hybrid.html):

1. [cohere](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-cohere)
2. [palm](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-cohere)
3. [huggingface](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-cohere)

### Motivation

more flexibility to users

### Your contribution

code review

**Comment by imeckr** [comment]
I suppose, you can use the vectorizer in the following way. Is that what you were asking ?

```
import weaviate
import os
from langchain.retrievers.weaviate_hybrid_search import WeaviateHybridSearchRetriever
from langchain.schema import Document

WEAVIATE_URL = os.getenv("WEAVIATE_URL")
client = weaviate.Client(
    url=WEAVIATE_URL,
    auth_client_secret=weaviate.AuthApiKey(api_key=os.getenv("WEAVIATE_API_KEY")),
    additional_headers={
        "X-Cohere-Api-Key": os.getenv("COHERE_API_KEY"),
    },
)

class_obj = {
    "class": "Document",
    "vectorizer": "text2vec-cohere"
}
client.schema.create_class(class_obj)

retriever = WeaviateHybridSearchRetriever(
    client, index_name="Document", text_key="text"
)

docs = [] # define docs here

retriever.add_documents(docs)
retriever.get_relevant_documents("the ethical implications of AI")
```

**Comment by hsm207** [comment]
@imeckr yes, that's the way to do it now. But I think a better user experience would be something like:

```python
retriever = WeaviateHybridSearchRetriever(
    client, index_name="Document", text_key="text", vectorizer="cohere"
)

```

i.e. user does not have to create the schema themselves.

**Comment by jacobhutchinson** [comment]
On a similar note, users should have the option to pass an embedding as well, similar to the [Weaviate.from_texts()](https://python.langchain.com/en/latest/_modules/langchain/vectorstores/weaviate.html#Weaviate.from_texts) method. I run Weaviate locally with no embedding modules and generate embeddings myself, and this is currently not an option with Weaviate Hybrid Search Retriever. So in my mind, satisfying this issues entails 2 new variables, `vectorizer` (or similar) and `embedding`.

**Comment by hsm207** [comment]
@jacobhutchinson agree. could you open a separate feature request to we it is easier to keep track of the areas that need to be improved in the hybrid search

**Comment by jacobhutchinson** [comment]
@hsm207 agreed, new issue for local embeddings here.

**Comment by jacobhutchinson** [comment]
Quick follow up thought: I was digging through the Weaviate vectorstore code a bit and noticed the default embedding that is used there does not even specify a vectorizer (https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/weaviate.py#L17). I don't use Weaviate vectorizer modules locally, so is anyone else able to confirm if we actually need to embed this data in the schema, or does Weaviate automatically utilize the module on the backend if it's set up for that? I imagine so, otherwise the Weaviate vectorstore class would be breaking for users utilizing vectorizer modules without explicity defining the schema first. If that's true, we could potentially just delete the line of code specifying the vectorizer to solve this issue.

**Comment by jacobhutchinson** [comment]
Thanks for the info @hsm207, I agree that the default being no vectorizer seems more sane than any alternatives. +1 on figuring out the reason for deviation here.
