### ISSUE TITLE
RFC: Use wasm-exec package to sandbox code execution by the Python REPL tool

### ISSUE THREAD

**Issue by Jflick58** [langchain-ai/langchain#5388]
### Issue you'd like to raise.

Issues #1026  and #5294 raise legitimate concerns with the security of executing LLM-generated code via the `exec()` function. Out of that discussion came a link to [this blog](https://til.simonwillison.net/webassembly/python-in-a-wasm-sandbox) that demonstrated a way to use Wasm to execute Python code in an isolated interpreter. 

I have developed a library based on that code called [wasm-exec](https://github.com/Jflick58/wasm_exec) to provide a clean interface to this solution. I’d like to next make a PR in LangChain replacing instances of `exec()` with `wasm_exec()` but wanted to get some feedback on this solution before doing so. 

Right now, the largest unknown is the extent of support for arbitrary packages, which may make running something like Pandas in the sandbox untenable until a solution is found. I believe I have a path forward on that (via installing when configuring the wasm runtime), but will need to continue to experiment.

**Comment by Jflick58** [comment]
@uogbuji I considered that, but I was initially going for a drop-in replacement to `exec()` so I kept it all in a single function. I suppose a second line of a call to the constructor isn't too onerous... I'll likely refactor it.

**Comment by congwang-mk** [comment]
Coming back to this old thread with a different approach to the same problem.

The Wasm path had the package compatibility issue you mentioned (Pandas, etc.). sandlock (https://github.com/multikernel/sandlock) takes the opposite approach: run native Python with full package support, but confine it with Landlock + seccomp at the kernel level. No Docker, no root, about 1ms startup.

So `exec(llm_code)` runs in a fork with only the permissions you specify (e.g. filesystem read-only, no network). All packages work since it's native CPython.

Curious if this would have addressed the original use case here.
