### ISSUE TITLE
Allow users to pass local embeddings to Weaviate Hybrid Search Retriever

### ISSUE THREAD

**Issue by jacobhutchinson** [langchain-ai/langchain#5539]
### Feature request

Fork off from this issue: https://github.com/hwchase17/langchain/issues/5300

The idea is to provide the WeaviateHybridSearchRetriever with the ability to use local embeddings similar to the Weaviate vectorstore. Specifically, for the `WeaviateHybridSearchRetriever.add_documents()` and `WeaviateHybridSearchRetriever.get_relevant_documents()` functions to work similar to the `Weviate.from_texts()` function where there is the option to use local embeddings if passed during creation. Additionally, the `WeaviateHybridSearchRetriever._create_schema_if_missing()` function likely needs to remove the default addition of a vectorizer in the schema object (related issue here: https://github.com/hwchase17/langchain/issues/5300).

### Motivation

This will allow those of us running Weaviate without embedding modules (like myself) to use the Weaviate Hybrid Search Retriever.

### Your contribution

I am planning on working to get a fix locally, I can potentially submit this as a PR down the line. Busy this week so others would probably beat me to it. I can review though.

**Comment by navicstein** [comment]
I'm here too for a similar issue, 
we should allow using Weaviate without embeddings, see: https://weaviate.io/developers/weaviate/quickstart#option-1-vectorizer

it seems Weaviate has the option to handle vectorization internally which sounds cheaper on a large scale than using `openAIEmbeddings` i often run into rate limit errors because of large documents (on the free plan)
