### ISSUE TITLE
Batch generation from API

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [langchain-ai/langchain#5892]
Hi there,

I am running LLM through custom API and have the possibility to run batch inference. However, the generate method from langchain only runs iteratively the LLM on the list of prompts. 

Would there be an existing method that I could use to allow batch generation on my API?

**Comment by rsbohn** [comment]
`[llm('nothing to see here') for _ in range(25)]`

transformers\pipelines\base.py:1081: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

`llm(['one','two','three'])`

ValueError: Argument `prompt` is expected to be a string. Instead found <class 'list'>. If you want to run the LLM on multiple prompts, use `generate` instead.

(...so I use llm.generate() and get the UserWarning again.)

**Comment by ycjcl868** [comment]
same issue with `llama2`(the model supports `prompts` inputs)

**Comment by eaubin** [comment]
Still needed with v0.1.0

**Comment by sqrt676** [comment]
ValueError: Argument `prompt` is expected to be a string. Instead found <class 'list'>. If you want to run the LLM on multiple prompts, use `generate` instead.
