### ISSUE TITLE
Impossible to connect PowerBI Dataset Agent to Azure services

### ISSUE THREAD

**Issue by JRlis** [langchain-ai/langchain#6157]
### System Info

Hi, 
I'm trying to reproduce this example https://python.langchain.com/en/latest/modules/agents/toolkits/examples/powerbi.html

When i launch this part of the code : 
toolkit = PowerBIToolkit(
    powerbi=PowerBIDataset.update_forward_refs(dataset_id=dataset-id, table_names=['Tables'], credential=DefaultAzureCredential()), 
    llm=smart_llm
)

I have this error : NameError: name 'TokenCredential' is not defined

What am I doing wrong ? Do i have to specify things with Azure credentials first ? 
Thanks for your help

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

example here : https://python.langchain.com/en/latest/modules/agents/toolkits/examples/powerbi.html

I just modified powerbi=PowerBIDataset() to powerbi=PowerBIDataset.update_forward_refs() because of an error i had. 

### Expected behavior

Connect the agent to powerbi rest API

**Comment by NishantSrivastava81** [comment]
I am facing the similar issue, even after importing TokenCredential it is still not working

**Comment by JRlis** [comment]
I forgot to precise but i tried to import TokenCredential too already, and i got the same error

**Comment by lmazuel** [comment]
`TokenCredentials` is defined in the `azure-core` package, that is a dependency of `azure-identity` used to get `DefaultAzureCredential()`. Since `azure-core` 1.23.0, `TokenCredentials` is available to be imported (before it was typed only). You would get error like this if `azure-core` is therefore less than 1.23.0.

Upgrading to at least 1.23.0 would solve the problem. I'm not familiar enough with langchain to be sure where this should be done though.

(I work in the Azure Python team at MS, responsible for `azure-core`)

**Comment by sawdeepa** [comment]
I am still facing this issue
