### ISSUE TITLE
Pinecone add_texts function does not populate vector store as expected, repeats first text in iterable

### ISSUE THREAD

**Issue by yahiakala** [langchain-ai/langchain#6485]
### System Info

I am running this code on my Mac and on a linux server

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
embeddings = OpenAIEmbeddings()
pinecone.init(
        api_key=PINECONE_API_KEY,
        environment=PINECONE_ENV
)
pineconedb = Pinecone.from_existing_index(index_name, embeddings)
pineconedb.add_texts(
            texts=['Hello', 'my name is Steve', 'I am 20 years old']
)
```

### Expected behavior

Three new entries in the Pinecone vector store: ['Hello', 'my name is Steve', 'I am 20 years old']

Instead, I get three new entires: ['Hello', 'Hello', 'Hello']

**Comment by devstein** [comment]
_Generated by a 🤖_


### Answer
It seems like the issue is caused by the way the `to_upsert` variable is being created. The `zip` function is used to combine `ids_batch`, `embeds`, and `metadata`, but it's not being converted to a list before being passed to the `pinecone.upsert` function. This might cause the same first element to be repeated.
To fix this issue, you can modify the `to_upsert` line to convert the zipped object to a list:
```python
to_upsert = list(zip(ids_batch, embeds, metadata))
```
Then, pass the `to_upsert` variable to the `pinecone.upsert` function. This should correctly populate the Pinecone vector store with the provided texts.

### Sources
- [langchain/vectorstores/pinecone.py](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/pinecone.py)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by yahiakala** [comment]
The code in the add_texts function (the function in question) passes a list of tuples (populated with a loop) to the `upsert` function. Here's the code:

```python
def add_texts(
        self,
        texts: Iterable[str],
        metadatas: Optional[List[dict]] = None,
        ids: Optional[List[str]] = None,
        namespace: Optional[str] = None,
        batch_size: int = 32,
        **kwargs: Any,
    ) -> List[str]:
        """Run more texts through the embeddings and add to the vectorstore.

        Args:
            texts: Iterable of strings to add to the vectorstore.
            metadatas: Optional list of metadatas associated with the texts.
            ids: Optional list of ids to associate with the texts.
            namespace: Optional pinecone namespace to add the texts to.

        Returns:
            List of ids from adding the texts into the vectorstore.

        """
        if namespace is None:
            namespace = self._namespace
        # Embed and create the documents
        docs = []
        ids = ids or [str(uuid.uuid4()) for _ in texts]
        for i, text in enumerate(texts):
            embedding = self._embedding_function(text)
            metadata = metadatas[i] if metadatas else {}
            metadata[self._text_key] = text
            docs.append((ids[i], embedding, metadata))
        # upsert to Pinecone
        self._index.upsert(vectors=docs, namespace=namespace, batch_size=batch_size)
        return ids

```
