### ISSUE TITLE
unable to use matching engine

### ISSUE THREAD

**Issue by dbg-raghulkrishna** [langchain-ai/langchain#6577]
### System Info

langchain 0.0.207
platform ubuntu
python 3.9

### Who can help?

@hwaking @eyurtsev @tomaspiaggio 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

python script
```
from langchain.embeddings import VertexAIEmbeddings
embeddings = VertexAIEmbeddings()
llm = VertexAI(model_name='text-bison')

from langchain.vectorstores import MatchingEngine

texts = ['The cat sat on', 'the mat.', 'I like to', 'eat pizza for', 'dinner.', 'The sun sets', 'in the west.']

vector_store = MatchingEngine.from_components(
    project_id=project,
    region=location,
    gcs_bucket_name='bucket_name',
    index_id="index_id",
    endpoint_id="endpoint_id",
    embedding=embeddings
)
```

error message
[error.txt](https://github.com/hwchase17/langchain/files/11830103/error.txt)

### Expected behavior

expected behavior is pushing the vectors to vectorstore

**Comment by nishantguvvada** [comment]
"expected behavior is pushing the vectors to vectorstore" - **use MatchingEngine.add_documents or add_texts() to update the vector store.**

Looking at the error it seems that **you missed mentioning the index_id. index_name needs to be the actual id**  :

InvalidArgument                           Traceback (most recent call last)
Cell In[19], line 3
      1 from google.cloud import aiplatform
----> 3 my_index = aiplatform.MatchingEngineIndex(
      4      project='dbg-bigdata-dev-0c21106d',
      5             location='europe-west3',
      6         index_name=**'my_index_id'**
      7     )
