### ISSUE TITLE
Chromadb only returns the first document from persistent db

### ISSUE THREAD

**Issue by GarmischWg** [langchain-ai/langchain#6657]
### System Info

|software|Version|
|:---:|:---:|
|python|3.10.11|
|LangChain|0.0.209|
|Chroma|0.3.26|
|Windows|11|
|Ubuntu|22.06|

I have tried on both windows and ubuntu

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

i am having trouble adding multiple documents into a vectordb. I am using chromadb here.
The following loads, split and embed 2 text files and store them in a persistant vector database. Then it queries the database.

```python
from langchain.document_loaders import TextLoader
from langchain.vectorstores import Chroma
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
import os
from getpass import getpass

OPENAI_API_KEY = getpass()

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

embeddings = OpenAIEmbeddings()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
persist_directory = "db"
db = Chroma(persist_directory=persist_directory, embedding_function=embeddings)

# -------------------------- Adding spacex_wiki.txt -------------------------- #
loader = TextLoader("this_has_to_work/spacex_wiki.txt", encoding="utf8")
documents = loader.load()
docs = text_splitter.split_documents(documents)
db.add_documents(docs)

# ------------------------- Adding imploson_wiki.txt ------------------------- #
loader = TextLoader("this_has_to_work/implosion_wiki.txt", encoding="utf8")
documents = loader.load()
docs = text_splitter.split_documents(documents)
db.add_documents(docs)

db.persist()

# --------------------------- querying the vectordb -------------------------- #
db = None

db = Chroma(persist_directory=persist_directory, embedding_function=embeddings)

retriever = db.as_retriever(search_type="mmr")

query = "What is implosion?"
print(query)
print(retriever.get_relevant_documents(query)[0])
print("\n\n")

query = "Who is elon?"
print(query)
print(retriever.get_relevant_documents(query)[0])
print("\n\n")
```
The above code runs without a problem and is able to retreive from both text file. The problem starts with the following code.

The following code only loads the vectordb from the persistant location.
```python
from langchain.document_loaders import TextLoader
from langchain.vectorstores import Chroma
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
import os
from getpass import getpass

OPENAI_API_KEY = getpass()

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

embeddings = OpenAIEmbeddings()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
persist_directory = "db"
db = Chroma(persist_directory=persist_directory, embedding_function=embeddings)

# --------------------------- querying the vectordb -------------------------- #
retriever = db.as_retriever(search_type="mmr")

query = "What is implosion?"
print(query)
print(retriever.get_relevant_documents(query)[0])
print("\n\n")

query = "Who is elon?"
print(query)
print(retriever.get_relevant_documents(query)[0])
print("\n\n")
```
The above code will only return from the first document stored in the vectordb (spacex_wiki.txt), no matter what the prompt is.
The following are the text files used.

[implosion_wiki.txt](https://github.com/hwchase17/langchain/files/11850301/implosion_wiki.txt)
[spacex_wiki.txt](https://github.com/hwchase17/langchain/files/11850303/spacex_wiki.txt)

### Expected behavior

It is expected that information from both documents can be retreived when the vectordb is loaded from persistant location.
However, only the first embedded document can be retreived.

**Comment by catbears** [comment]
Similar problem here. The last 30 hrs I calculated embeddings and stored everything in Chroma, was able to query/ask questions. Today I wanted to pick up working on that point, and it seems like stuff is just gone. Only 200 documents are left, no source when I query, too.

**Comment by b11706020** [comment]
based on the your question:
I can suggest you some steps to check for the root cause of the issue:
1a.Check for collections in the vectordb and check whether the both files you added are in the same collection(when you create chromadb without mentioning any collection, it will automatically goes to the default collection named "langchain")
1b.Check the page_content of each documented stored in the vectordb

2.from the above step you get the idea in which collection the both files are stored , now call the same collection inside the retrival method like db = Chroma(persist_directory=persist_directory, embedding_function=embeddings,collection_name=collection_name_where_both_files_reside)

3.If above steps doesnot help then you have to start looking at the embeddings function you used
always mention the embedding model you want to use inside the  openai embeddings() like embeddings = OpenAIEmbeddings(model="text-embeddings-ada-002") to make sure the embeddings of the all documents of the vectordb have same embedding model , it even helps you to maintain the consistent embeddings system across your RAG method .
Hope your issue resolves.
