### ISSUE TITLE
https://python.langchain.com/docs/use_cases/question_answering/document-context-aware-QA code is not working,

### ISSUE THREAD

**Issue by WaelAbou** [langchain-ai/langchain#6723]
### System Info

colab

### Who can help?

@hwchase17 hi i am trying to use Context aware text splitting and QA / Chat

the code doesnt work starting the vectore indes

# Build vectorstore and keep the metadata
from langchain.vectorstores import Chroma
vectorstore = Chroma.from_documents(texts=all_splits,metadatas=all_metadatas,embedding=OpenAIEmbeddings())

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

i am only following the notebood 

### Expected behavior

it should work

**Comment by WaelAbou** [comment]
# Define self query retriver
llm = OpenAI(temperature=0)
retriever = SelfQueryRetriever.from_llm(llm, vectorstore, document_content_description, metadata_field_info, verbose=True)


TypeError: 'NoneType' object is not callable

**Comment by HashemAlsaket** [comment]
The notebook/lab needs some updating- I'm working on that now. A few things need to be updated:

1. `all_metadatas` is not defined
2. `from langchain.embeddings import OpenAIEmbeddings` needs to be added
3. `lark` package should be added to requirements during installation. It looks like the TypeError you're seeing was due to this:

`try:
    import lark
    from packaging import version

    if version.parse(lark.__version__) < version.parse("1.1.5"):
        raise ValueError(
            f"Lark should be at least version 1.1.5, got {lark.__version__}"
        )
    from lark import Lark, Transformer, v_args
except ImportError:

    def v_args(*args: Any, **kwargs: Any) -> Any:  # type: ignore
        return lambda _: None

    Transformer = object  # type: ignore
    Lark = object  # type: ignore`

Also, a relevant `.md` file should be placed in the generated Notion folder. For now, feel free to use this notebook code for your personal learning:

`from langchain.agents import create_csv_agent
from langchain.llms import OpenAI
from langchain.chat_models import ChatOpenAI
from langchain.agents.agent_types import AgentType

# Load Notion page as a markdownfile file
from langchain.document_loaders import NotionDirectoryLoader
path='Notion__files/'
loader = NotionDirectoryLoader(path)
docs = loader.load()
md_file=docs[0].page_content

# Let's create groups based on the section headers in our page
from langchain.text_splitter import MarkdownHeaderTextSplitter
headers_to_split_on = [
    ("###", "Section"),
]
markdown_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)
md_header_splits = markdown_splitter.split_text(md_file)

# Define our text splitter
from langchain.text_splitter import RecursiveCharacterTextSplitter
chunk_size = 500
chunk_overlap = 0
text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
all_splits = text_splitter.split_documents(md_header_splits)
all_metadatas = []

# Build vectorstore and keep the metadata
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma
vectorstore = Chroma.from_documents(documents=all_splits,
                                    metadatas=all_metadatas,
                                    embedding=OpenAIEmbeddings())

# Create retriever 
from langchain.llms import OpenAI
from langchain.retrievers.self_query.base import SelfQueryRetriever
from langchain.chains.query_constructor.base import AttributeInfo

# Define our metadata
metadata_field_info = [
    AttributeInfo(
        name="Section",
        description="Part of the document that the text comes from",
        type="string or list[string]",
    ),
]
document_content_description = "Major sections of the document"

# Define self query retriver
llm = OpenAI(temperature=0)
retriever = SelfQueryRetriever.from_llm(llm,
                                        vectorstore,
                                        document_content_description,
                                        metadata_field_info,
                                        verbose=True)

# Test
retriever.get_relevant_documents("Summarize the Introduction section of the document")

retriever.get_relevant_documents("Summarize the Testing section of the document")

from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)
qa_chain = RetrievalQA.from_chain_type(llm,retriever=retriever)
qa_chain.run("Summarize the Testing section of the document")
`

**Comment by TechnicolorGUO** [comment]
sample code is still not working.
same error:  TypeError: 'NoneType' object is not callable

**Comment by HashemAlsaket** [comment]
@TechnicolorGUO hmm, did you make sure to download the `Notion_DB/` files?

**Comment by TechnicolorGUO** [comment]
sorry for bothering, it's the "pip install lark' problem
BTW, I was trying to replace openai with huggingface, yet error occurred

'OutputParserException: Parsing text
 Structured Request Schema:  
 raised following error:
Got invalid JSON object. Error: Expecting value: line 1 column 1 (char 0)'

does this mean the SCHEMA is incompatible with most of the open source LLMs and up till now this module only supports openai?
sorry for that trivial problem again!

**Comment by rlancemartin** [comment]
Hmm.

1/ run notebook exactly as it is on master. Does that work for you?

2/ once that works, try modifying embeddings (use HF, etc).

**Comment by TechnicolorGUO** [comment]
I guess the issue was about the retriever, for the original code

# Define self query retriver
retriever = SelfQueryRetriever.from_llm(OpenAI(temperature=0),
                                        vectorstore,
                                        document_content_description,
                                        metadata_field_info,
                                        verbose=True)



The above retriever works well and I made the following change:

tokenizer = AutoTokenizer.from_pretrained("declare-lab/flan-alpaca-large")
model = AutoModelForSeq2SeqLM.from_pretrained("declare-lab/flan-alpaca-large")
pipe = pipeline(
"text2text-generation",
model=model,
tokenizer=tokenizer,
max_length=512,
temperature=0,
top_p=0.95,
repetition_penalty=1.15
)
llm = HuggingFacePipeline(pipeline=pipe)
retriever = SelfQueryRetriever.from_llm(llm,
                                        vectorstore,
                                        document_content_description,
                                        metadata_field_info,
                                        verbose=True)
         
         
                                       
And when I retrieved splitter texts with query, following error raised:

OutputParserException: Parsing text
json  "query": "What is the 4 Why Self-Attention section of the document?"  
 raised following error:
Got invalid JSON object. Error: Expecting value: line 1 column 1 (char 0)

         
                                      
I guess the Openai() wrapper is strong enough to handle json input while the llm in hugging face hub does not support such schema?
