### ISSUE TITLE
Issue: Large observation handling limit

### ISSUE THREAD

**Issue by haifengwu-msft** [langchain-ai/langchain#6836]
### Large observation handling limit.

Hey langchain community,

I have a tool which takes a database query as input and does database query. This is similar to what `QuerySQLDataBaseTool` does. The problem is the output of the query is out of control, it can be large and the agent exceeded the token limit.

The solution I have tried:
1. Do pagination:
    - Chunk the large output, summarize each chunk according to the target question
    - Combine all chunks' summarization, which is much smaller than the original output.

    Problems: 
    - Even though I did the summarization according to the target question, the summarization will still lose information.
    - The pagination can be slow.

2. Vectorization:
    - Chunk the large output
    - Embed each chunk and put them into a Vector DB.
    - Do a similarity search based on the target question, and take number of chunks within the token limit.

    Problems:
    - The embedding take times, so it can be slow for a single thought.
    - The output of the query is semantic continuously as a a whole, the chunks can break the semantic meaning.

Does anyone have a solution for this problem? I appreciated any idea!

**Comment by sdelgadoc** [comment]
There's no way around the token limit, so we need to get creative. Two potential solutions are to truncate or summarize the data. 

An example of how to concatenate can be found in the [O365SearchEmails tool](https://github.com/hwchase17/langchain/blob/master/langchain/tools/office365/messages_search.py), where truncation is an input parameter, which limits the size of the return data. Because LangChain knows that the data isn't complete, it can start with truncated results, and then query for a smaller subset.

Summarizing is a little more complex. In this case, you would send the data to ChatGPT, and have it summarize it in prose with one function, and then use another function to use that prose summary to run a smaller query.

Hope that helps!

**Comment by haifengwu-msft** [comment]
> Because LangChain knows that the data isn't complete, it can start with truncated results, and then query for a smaller subset.
Hey sdelgadoc, thank you for replying!
I understand the implementation of O365SearchEmails tool, that's based on body already have a short version: body_preview.
But my data I got from DB with the query is raw data.

How does LangChain(agent) know the data isn't complete?
`then query for a smaller subset` does that mean the following thoughts continuously re-trigger the tool and craft a new query which will get a smaller output?

**Comment by rachaelsingleton** [comment]
Did you have any breakthroughs on this? Did his workaround work? Curious if it took a substantial amount of time to run through all the truncated results.
