### ISSUE TITLE
Chroma (duckdb+parquet) DB isn't saving the parquet files for persisted DB until application is killed

### ISSUE THREAD

**Issue by JackLeick** [langchain-ai/langchain#6938]
### System Info

Chroma v0.2.36, python 3.9

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`
            settings = Settings(
                chroma_db_impl='duckdb+parquet',
                persist_directory="db",
                anonymized_telemetry=False
            )

            pages = self._load_single_document(file_path=file_path)
            docs = text_splitter.split_documents(pages)
            db = Chroma.from_documents(docs, embedding_function, client_settings=settings)
`

### Expected behavior

All files for the database should be created in the db directory. However, the parquet files are not being created when db.from_documents() is called.
However, this is not happening. All the files in the index directory are created at this time.

Later, when the application is killed (flask application, so in between requests the DB is torn down and thus should be persisited), then the parquet files show up.

**Comment by rjarun8** [comment]
It is a good practice to explicitly persist

```
# Explicitl persist
db.persist()
```

**Comment by JackLeick** [comment]
Thank you. I added an explicit persist. Here's what I have debugging through the code:
db = Chroma.from_documents(...)   # After this line, I see the index folder created, but no parquet files.
db.persist() gives the following error: ValueError: You must specify a persist_directory oncreation to persist the collection.
But everything is being added to my persist directory, 'db'.

That seems like a bug, definitely not expected behaviour

**Comment by JackLeick** [comment]
Okay, seemingly, I need to call out a persist directory regardless if it is in the client Settings object or not. The following does NOT produce the error, and works as expected:

`        
settings = Settings(
  chroma_db_impl='duckdb+parquet',
  persist_directory=os.path.join(directory, 'db'),
  anonymized_telemetry=False
)
db = Chroma(embedding_function=embedding_function, client_settings=settings, persist_directory='db')

Sounds like a bug with Chroma, I'll post over on that project. Closing this

**Comment by JackLeick** [comment]
On second look, it appears the issue is in the Chroma wrapper. The following code in langchain/vectorstores/chroma.py seems to be the problem:

```python
    def __init__(
        self,
        collection_name: str = _LANGCHAIN_DEFAULT_COLLECTION_NAME,
        embedding_function: Optional[Embeddings] = None,
        persist_directory: Optional[str] = None,
        client_settings: Optional[chromadb.config.Settings] = None,
        collection_metadata: Optional[Dict] = None,
        client: Optional[chromadb.Client] = None,
    ) -> None:
        """Initialize with Chroma client."""
        try:
            import chromadb
            import chromadb.config
        except ImportError:
            raise ValueError(
                "Could not import chromadb python package. "
                "Please install it with `pip install chromadb`."
            )

        if client is not None:
            self._client = client
        else:
            if client_settings:
                self._client_settings = client_settings
            else:
                self._client_settings = chromadb.config.Settings()
                if persist_directory is not None:
                    self._client_settings = chromadb.config.Settings(
                        chroma_db_impl="duckdb+parquet",
                        persist_directory=persist_directory,
                    )
            self._client = chromadb.Client(self._client_settings)

        self._embedding_function = embedding_function
        **self._persist_directory = persist_directory**
        self._collection = self._client.get_or_create_collection(
            name=collection_name,
            embedding_function=self._embedding_function.embed_documents
            if self._embedding_function is not None
            else None,
            metadata=collection_metadata,
        )
```

The bolded line indicates that the persist directory is only being set if that is in fact passed in, where as if it is used in the client.Settings object, I'd expect it to get unpacked and used. Is this expected behaviour?

**Comment by rjarun8** [comment]
> 
@JackLeick 
I did some investigation around this and feel your issue is valid. Following is the summary. Do let me know if it addresses your problem statement.


_**Issue**_
 the persist_directory is not being set when it's passed in the client_settings object. This is likely because the persist_directory is only being set if it's passed as a separate argument to the Chroma constructor, and not when it's included in the client_settings object.

**_Code Fix_**


```
def __init__(
    self,
    collection_name: str = _LANGCHAIN_DEFAULT_COLLECTION_NAME,
    embedding_function: Optional[Embeddings] = None,
    persist_directory: Optional[str] = None,
    client_settings: Optional[chromadb.config.Settings] = None,
    collection_metadata: Optional[Dict] = None,
    client: Optional[chromadb.Client] = None,
) -> None:
    """Initialize with Chroma client."""
    try:
        import chromadb
        import chromadb.config
    except ImportError:
        raise ValueError(
            "Could not import chromadb python package. "
            "Please install it with `pip install chromadb`."
        )

    if client is not None:
        self._client = client
    else:
        if client_settings:
            self._client_settings = client_settings
            self._persist_directory = client_settings.persist_directory if client_settings.persist_directory else persist_directory 
			#updated to set _persist_directory either from client_settings.persist_directory or #persist_directory(inp args). if persist_directory(inp args) as per "def persist()" must specify a #persist_directory which still holds good as per the original design
        else:
            self._client_settings = chromadb.config.Settings()
            if persist_directory is not None:
                self._client_settings = chromadb.config.Settings(
                    chroma_db_impl="duckdb+parquet",
                    persist_directory=persist_directory,
                )
                self._persist_directory = persist_directory
        self._client = chromadb.Client(self._client_settings)

    self._embedding_function = embedding_function
    self._collection = self._client.get_or_create_collection(
        name=collection_name,
        embedding_function=self._embedding_function.embed_documents
        if self._embedding_function is not None
        else None,
        metadata=collection_metadata,
    )

```

**_Change Summary:_**
The __init__ method of the Chroma class has been updated to correctly handle the persist_directory parameter. Previously, persist_directory was only being set if it was passed as a separate argument to the Chroma constructor, and not when it was included in the client_settings object. The updated code now correctly sets persist_directory in all scenarios.

**_Addressed Scenarios:_**

1. persist_directory is provided in client_settings: If client_settings is provided and it includes persist_directory, then self._persist_directory is set to client_settings.persist_directory.

2. persist_directory is not provided in client_settings but is passed as an argument: If client_settings is provided but it does not include persist_directory, and persist_directory is passed as a separate argument, then self._persist_directory is set to the persist_directory argument.

3. client_settings is not provided, but persist_directory is passed as an argument: If client_settings is not provided and persist_directory is passed as a separate argument, then self._persist_directory is set to the persist_directory argument.

4. Neither client_settings nor persist_directory is provided: If neither client_settings nor persist_directory is provided, then self._persist_directory remains unset.

**Comment by JackLeick** [comment]
Thank you! This looks like a great fix. That will address my issue.

**Comment by rjarun8** [comment]
Issue has been addressed via commit : https://github.com/hwchase17/langchain/commit/a2830e3056e4e616160b150bf5ea212a97df2dc4
