### ISSUE TITLE
Loading online PDFs gives temporary file path as source in metadata

### ISSUE THREAD

**Issue by aswinshenoy** [langchain-ai/langchain#7034]
Hi, 

first up, thank you for making langchain! I was playing around a little and found a minor issue with loading online PDFs, and would like to start contributing to langchain maybe by fixing this.

### System Info

langchain 0.0.220, google collab, python 3.10

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from langchain.document_loaders import PyMuPDFLoader

loader = PyMuPDFLoader('https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf')
pages = loader.load()

pages[0].metadata
```

<img width="977" alt="image" src="https://github.com/hwchase17/langchain/assets/21276922/4ededc60-bb03-4502-a8c8-3c221ab109c4">

### Expected behavior

Instead of giving the temporary file path, which is not useful and deleted shortly after, it could be more helpful if the source is set to be the URL passed to it. This would require some fixes in the `langchain/document_loaders/pdf.py` file.

**Comment by jannikjw** [comment]
This only happens in Jupyter Notebooks. Try running the same code in a script and it should show the correct source.

**Comment by 123-fake-st** [comment]
I believe this issue is unresolved and I plan to submit a PR with a proposed update:  when loading from an online pdf, I see a temporary, local path in the document metadata regardless of whether or not the code is run in a jupyter notebook.

There are multiple pdf loaders that exhibit similar behavior with online pdfs that could use an update.  I will evaluate whether it's reasonable to include `PyPDFium2Loader`, `PDFMinerLoader`, `PDFMinerPDFasHTMLLoader`, and `PDFPlumberLoader` updates in addition to a `PyMuPDFLoader` update in a PR.  I do not plan to evaluate pdf loaders that go to services that require a key or token.
