### ISSUE TITLE
Issue: Conditioning planner with custom instructions in Plan-And-Execute models

### ISSUE THREAD

**Issue by saswat0** [langchain-ai/langchain#7041]
### Issue you'd like to raise.

Can Plan-And-Execute models be conditioned to plan in particular directions instead of doing the planning alone? Say I'd like the planning to take place differently and the LLM always decides on an exhaustive manner

**Comment by dudesparsh** [comment]
I think that is already handled with the help of tools ( guide here : https://python.langchain.com/docs/modules/agents/tools/ ) .

In case you want llm to select the tool by itself - use load_tools() method and pass these tools to initialize_agent method to automatically let llm decide the tool amongst the list. 

In case you want to define custom tools, that you can do in a similar fashion : https://python.langchain.com/docs/modules/agents/tools/how_to/custom_tools

In case you want Human-in-the-loop validation : https://python.langchain.com/docs/modules/agents/tools/how_to/human_approval

I hope that answers your issue, please let me know in case you meant something else ( do brief appropriately if that is the case ).

**Comment by PranitModak** [comment]
I have the same question and @dudesparsh I believe its not in your answer yet. As current langchain documentation shows usage of tools only for the executor. I believe what @saswat0  wants to know is if the planner also can use suppose a document present in vector db to reference what should be the next step to do to solve the original problem instead of just deciding on its own.

**Comment by DhavalThkkar** [comment]
With tools we can describe what the tool does and we let the LLM decide based on it's understanding to choose the most relevant tool to solve a problem. I have faced a problem with this almost every single time because it chooses one tool over the other. To tackle this, brute forcing by providing description helps but not always. The most ideal way would be to plan the steps and maybe have some control over what the LLM would do to solve a problem. Plan and execute is available on langchain but that too decides the next steps on it's own without any user input. I can try to contribute if guided along the right way
