### ISSUE TITLE
Conversation Summary Buffer Memory does not accept a system message 

### ISSUE THREAD

**Issue by vnandan** [langchain-ai/langchain#7327]
### System Info

I intend to use the conversation summary buffer memory with ChatOpenAI in a conversation chain. For the chat, there's a need to set the system message to instruct and give appropriate personality to the chat assistant. However, system message is not supported to be inserted in the memory either via the save_context (the documented way) or the memory.chat_memory.message.insert()

The summary of the chat itself seems to use the system message to send the summary. This makes Conversation Summary Buffer Memory incompatible with ChatOpenAI.

### Who can help?

@hwchase17  @agola11 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Using either of the two methods to use the system message

1. memory.chat_memory.messages.insert(0, system_message)
2. memory.save_context({"input": SystemMessage(content=system_message)}, {"output": ""})

### Expected behavior

We should be able to use any memory with ChatOpenAI as these need to be modular but ConversationSummaryBufferMemory seems incompatible with it due to system message.

**Comment by Llugaes** [comment]
confused about the same

**Comment by vnandan** [comment]
I think the memories should support all message types out of the box. This isn't a highly custom requirement. Both System message and memories come out of the box and are used together all the time. Their incompatibility makes the confidence in Langchain lower.

**Comment by IlyaShkurenko** [comment]
Without system messages for history no sense to use it for me. Add that support please

**Comment by jojeyh** [comment]
@IlyaShkurenko @vnandan 

I don't have any personal insight into the design decisions that the LangChain team made, but I'm assuming that there is no way to change the system message because that is not technically part the conversation history and classes like `ConversationBufferMemory` should only be handling the history of the conversation, not system messages.

I agree there should probable be a more direct way of changing the default system message that is included in `ConversationChain` but as a temporary workaround you can override the default prompt template like so
```
from langchain.chat_models import ChatOpenAI
from langchain.memory import ConversationBufferMemory # or ConversationBufferWindowMemory
from langchain.prompts.prompt import PromptTemplate
from langchain.chains import ConversationChain

llm = ChatOpenAI()
memory = ConversationBufferMemory()
template = """You are a(n) {adjective} pirate having a friendly conversation
    
Current conversation:
{history}
Human: {input}
AI:
"""
prompt_template = PromptTemplate(input_variables=["history", "input", "adjective"], template=template)

conversation = ConversationChain(
    llm=llm,
    prompt=prompt_template.partial(adjective="nasty"),
    verbose=True,
    memory=memory
)

conversation.predict(input="Hi!")
```

You should get output (in `ipython`) that looks something like 
```
> Entering new ConversationChain chain...
Prompt after formatting:
You are a nasty pirate having a friendly conversation.

Current conversation:

Human: Hi!
AI:

> Finished chain.
Out[40]: 'Arr, ahoy there! What be yer name, matey?'
```

If you don't need any extra extra variables like `adjective` above then you can just use `prompt_template` without calling `partial`.  

This is a bit hacky because you have to write out the prompt template by hand, including all `input_variables`.  I'm currently trying to include a parameter `system_message` for `ConversationChain`.  I'll submit a pull request soon hopefully.

**Comment by Nando-Mentu** [comment]
I agree with the issue and have it too. I need to save the system message to the memory or somehow be able to pass it to the ConverstationChain or LLMChain as I pass it to a ChatOpenAI model instance through the prompt.

**Comment by ROZBEH** [comment]
+1
