### ISSUE TITLE
Trying to merge a list of FAISS vectorstores without modifying the original vectorstores, but deepcopy() fails

### ISSUE THREAD

**Issue by maspotts** [langchain-ai/langchain#7402]
Hi: I'm trying to merge a list of `langchain.vectorstores.FAISS` objects to create a new (merged) vectorstore, but I still need the original (pre-merge) vectorstores intact.  I can use `x.merge_from(y)` which works great:

`merged_stores = reduce(lambda x, y: (z := x).merge_from(y) or z, stores)
`

but that modifies x in place, so my original list of vectorstores ends up with its first store containing a merge with all other elements of the list: which is not what I want.  So I tried using `deepcopy()` to make a temporary copy of the vectorstore I'm merging into:

`merged_stores = reduce(lambda x, y: (z := deepcopy(x)).merge_from(y) or z, stores)
`

which does exactly what I want.  However, I now find that when I use a Universal Sentence Encoder embedding in the original list of vectorstores I get an exception from `deepcopy()`:

`TypeError: cannot pickle '_thread.RLock' object`

Is there an obvious way for me to achieve this (non-destructive) merge without adding my own `FAISS.merge_from_as_copy()` method to the `langchain.vectorstores.FAISS` class?

**Comment by Worass** [comment]
If you want to merge the FAISS objects in a non-destructive manner without using deepcopy, you can create new instances of the FAISS objects and perform the merge on the copies. Here's an example:

**from langchain.vectorstores import FAISS
from functools import reduce

# Assuming you have a list of FAISS objects called 'stores'
stores = [...]

# Create copies of the FAISS objects
merged_stores = reduce(lambda x, y: x.merge_from(y) or x.copy(), stores)

# 'merged_stores' now contains the merged vectorstore without modifying the original vectorstores**



In the code above, x.copy() creates a new instance of the FAISS object that is a copy of x. Then, the merge operation is performed on the copied object instead of modifying the original object.

This approach should allow you to achieve the desired merge without modifying the original vectorstores and without running into the TypeError caused by deepcopy.

**Comment by Worass** [comment]
If you want to merge the FAISS objects in a non-destructive manner without using deepcopy, you can create new instances of the FAISS objects and perform the merge on the copies. Here's an example:

_from langchain.vectorstores import FAISS
from functools import reduce

# Assuming you have a list of FAISS objects called 'stores'
stores = [...]

# Create copies of the FAISS objects
merged_stores = reduce(lambda x, y: x.merge_from(y) or x.copy(), stores)

# 'merged_stores' now contains the merged vectorstore without modifying the original vectorstores_


In the code above, x.copy() creates a new instance of the FAISS object that is a copy of x. Then, the merge operation is performed on the copied object instead of modifying the original object.

This approach should allow you to achieve the desired merge without modifying the original vectorstores and without running into the TypeError caused by deepcopy.

**Comment by Worass** [comment]
If you want to merge the FAISS objects in a non-destructive manner without using deepcopy, you can create new instances of the FAISS objects and perform the merge on the copies. Here's an example:
---------
from langchain.vectorstores import FAISS
from functools import reduce

# Assuming you have a list of FAISS objects called 'stores'
stores = [...]

# Create copies of the FAISS objects
merged_stores = reduce(lambda x, y: x.merge_from(y) or x.copy(), stores)

# 'merged_stores' now contains the merged vectorstore without modifying the original vectorstores
---------

In the code above, x.copy() creates a new instance of the FAISS object that is a copy of x. Then, the merge operation is performed on the copied object instead of modifying the original object.

This approach should allow you to achieve the desired merge without modifying the original vectorstores and without running into the TypeError caused by deepcopy.

**Comment by maspotts** [comment]
Thanks for this, but I don't believe it does leave the original stores unmodified: the operation x.merge_from(y) DOES modify x; I tested it and confirmed this:

2023-07-08 11:22:41,029 INFO     Document index sizes: [13, 11, 9, 9, 17].
2023-07-08 11:22:41,030 INFO     Merging.
2023-07-08 11:22:42,414 INFO     Post-merge document index sizes: [24, 11, 9, 9, 17].

which is telling me that the first element of the list has been modified (it has been merged with all the subsequent elements).  Also: I don't see a FAISS.copy() method, so maybe I'm missing the point?

**Comment by Worass** [comment]
> 

the x.merge_from(y) operation modifies x, and FAISS does not have a built-in copy() method.

In that case, to achieve a non-destructive merge without modifying the original vectorstores, you can manually create copies of the FAISS objects. Here's an updated example:
------------------

from langchain.vectorstores import FAISS
from functools import reduce
import copy

# Assuming you have a list of FAISS objects called 'stores'
stores = [...]

# Create copies of the FAISS objects
copied_stores = [copy.deepcopy(store) for store in stores]

# Perform the merge on the copied objects
merged_store = reduce(lambda x, y: x.merge_from(y) or x, copied_stores)

# 'merged_store' now contains the merged vectorstore without modifying the original vectorstores


---------------

In the updated code, we manually create copies of the FAISS objects using copy.deepcopy() and store them in the copied_stores list. Then, the merge operation is performed on the copied objects.

By using copy.deepcopy(), we ensure that the copied objects are independent from the original ones and modifications to the copied objects won't affect the original vectorstores.

**Comment by maspotts** [comment]
OK thanks but I notice that you're using GPT (or similar) to answer the question: unfortunately the updated answer is not useful because it's back to where I started: using deepcopy().

Does anyone know how to solve this problem?

**Comment by Worass** [comment]
> OK thanks but I notice that you're using GPT (or similar) to answer the question: unfortunately the updated answer is not useful because it's back to where I started: using deepcopy().
> 
> Does anyone know how to solve this problem?

If using deepcopy() is not an option due to the TypeError you encountered, and modifying the FAISS class is not feasible, an alternative approach could be to manually create a new instance of the FAISS class and populate it with the merged data from the original vectorstores.

from langchain.vectorstores import FAISS
from functools import reduce

# Assuming you have a list of FAISS objects called 'stores'
stores = [...]

# Create a new instance of FAISS for the merged vectorstore
merged_store = FAISS()

# Merge the vectorstores into the new instance
for store in stores:
    merged_store.merge_from(store)

# 'merged_store' now contains the merged vectorstore without modifying the original vectorstores


In this approach, we manually create a new instance of the FAISS class called merged_store. Then, we iterate over the original vectorstores and merge each store into the merged_store instance using the merge_from() method.

This way, the merged_store will contain the merged vectorstore while leaving the original vectorstores intact.

**Comment by maspotts** [comment]
Do you know how to create an empty FAISS vectorstore?  I can't figure out a way to do it...

**Comment by Worass** [comment]
> Do you know how to create an empty FAISS vectorstore?  I can't figure out a way to do it...

To create an empty FAISS vectorstore, you can instantiate a new instance of the FAISS class without passing any arguments. Here's an example:

from langchain.vectorstores import FAISS

empty_store = FAISS()

# 'empty_store' is now an empty instance of the FAISS vectorstore


By creating a new instance of the FAISS class without providing any arguments, you create an empty vectorstore object that can be populated with vectors later on.

**Comment by maspotts** [comment]
Unfortunately that doesn't work: FAISS() expects arguments, including an index and a docstore.  I hate to seem paranoid but it really looks as if you're just pasting in (incorrect) responses from ChatGPT: apologies if that's not what you're doing, but the pattern (of plausible but incorrect answers) is very familiar.  If I'm off-base, then I'm sorry: please show me how to make that example work, and I'll be delighted to stand corrected :)
