### ISSUE TITLE
chain.run doesn't necessarily return a `str`

### ISSUE THREAD

**Issue by Connoropolous** [langchain-ai/langchain#7578]
https://github.com/hwchase17/langchain/blob/2667ddc6867421842fe027f1946644f452de8eb3/langchain/chains/base.py#L386-L393

when I have this:
```
chain = create_structured_output_chain(Categorization, llm, prompt, verbose=True)
response = chain.run(trx_description)
```
my `response` object is a dict not a str, but I got misled by the type assistance making me think it was a str.

**Comment by Bearnardd** [comment]
Hi @Connoropolous! Could you provide a more detailed reproducer?

**Comment by Connoropolous** [comment]
sure do you mean a complete script?

**Comment by Connoropolous** [comment]
```python
from langchain.document_loaders.csv_loader import CSVLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain import PromptTemplate, OpenAI, LLMChain
from langchain.chat_models import ChatOpenAI
from pydantic import BaseModel, Field
from typing import Optional
from langchain.chains.openai_functions import (
    create_openai_fn_chain, create_structured_output_chain
)
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate, HumanMessagePromptTemplate
from langchain.schema import HumanMessage, SystemMessage
from langchain.vectorstores import Chroma
import os

os.environ["OPENAI_API_KEY"] = ""

embeddings = OpenAIEmbeddings()
llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.5)
loader = CSVLoader(file_path="./food-flavours.csv")
food_data = loader.load()
db = Chroma.from_documents(food_data, embeddings)
retriever = db.as_retriever(search_kwargs={"k": 1})

system_message = """
You are a helpful assistant. When the user passes in a food, reply with what kind of flavour the food has.
"""

class Food(BaseModel):
    """Food."""
    flavour: str = Field(...,
                             description="The flavour profile of the food")


# STRUCTURED OUTPUT CHAIN
prompt_msgs = [
    SystemMessage(
        content=system_message,
    ),
    HumanMessagePromptTemplate.from_template("{input}"),
]
prompt = ChatPromptTemplate(messages=prompt_msgs)
chain = create_structured_output_chain(Food, llm, prompt)

def find_related_food_flavour_from_list(food: str):
    response_json = chain.run(food)
    response_string = response_json["flavour"]
    # get the similar documents using cosine similarity
    top_flavour = retriever.get_relevant_documents(response_string)
    return top_flavour[0]
```

**Comment by Connoropolous** [comment]
in the example
```
    response_json = chain.run(food)
    response_string = response_json["flavour"]
```
it is response_json that is incorrectly typed as a `str`

**Comment by Bearnardd** [comment]
Thanks! Will take a look at it :)

**Comment by Bearnardd** [comment]
Hello @baskaryan! I noticed that you added a docstring to the run method in the langchain/langchain/chains/base.py file. However, it seems that the docstring is incorrect, and the type annotation may also be inaccurate. The method doesn't always (or perhaps never) return a string. Even in the example notebook "opeanai_functions.ipynb," the output is a dictionary. I can fix that but I am wondering do we want it to return a dict (change docstrings etc.) or do we want to unpack a single string output from that dict?

**Comment by sumanthdonthula** [comment]
Hi @Connoropolous, **the create_structured_output_chain returns the output in dictionary format. Where as create_openai_fn_chain returns it in string format.**

So, for the fix if you want a **string** as return value you can use the following code:

from langchain.chains.openai_functions import create_openai_fn_chain
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate, HumanMessagePromptTemplate
from langchain.schema.messages import SystemMessage, HumanMessage

from pydantic import BaseModel, Field
from typing import Optional



class RecordDog(BaseModel):
    """Record some identifying information about a dog."""

    name: str = Field(..., description="The dog's name")
    color: str = Field(..., description="The dog's color")
    fav_food: Optional[str] = Field(None, description="The dog's favorite food")


llm = ChatOpenAI(model="gpt-3.5-turbo-0613", temperature=0,openai_api_key="Your Key")

prompt_msgs = [
    SystemMessage(content="You are a world class algorithm for recording entities"),
    HumanMessage(content="Make calls to the relevant function to record the entities in the following input:"),
    HumanMessagePromptTemplate.from_template("{input}"),
    HumanMessage(content="Tips: Make sure to answer in the correct format"),
]

prompt = ChatPromptTemplate(messages=prompt_msgs)


chain = create_openai_fn_chain([RecordDog],llm,prompt)
chain.run("Donthula Sumanth is 5 years old and loves chicken")

This outputs:
#->RecordDog(name='Donthula Sumanth', color='5 years old', fav_food='chicken')

**Moreover, as you have raised I have fixed the code** [langchain/langchain/chains/base.py](https://github.com/hwchase17/langchain/blob/2667ddc6867421842fe027f1946644f452de8eb3/langchain/chains/base.py#L386-L393) to say in comments and definition so that create_structured_output_chain will return a dict.

![image](https://github.com/hwchase17/langchain/assets/46747610/2652a065-d7ac-4d64-b74e-c2834ebfba13)

And I have updated the documentation for Examples also to eliminate confusion. 

Updated files langchain/chains/base.py and langchain/chains/openai_functions/base.py. Created a pull request #7620 to fix the code

**Comment by sumanthdonthula** [comment]
please refer to Getting structured outputs example in the link if it would be helpful. [](https://python.langchain.com/docs/modules/chains/popular/openai_functions)

**Comment by baskaryan** [comment]
seeing two issues here:

one is the structured output chain isn't actually returning pydantic objects even when initialized with one, which is a bug. opened #7622 to fix

the base chain type hints are incorrect. will update that next!

**Comment by Bearnardd** [comment]
Hi, @baskaryan! Changing the type hints should be straightforward. Based on the other issues I've observed, it seems like you have plenty of other tasks to handle :) . If @Connoropolous doesn't want or have the time to address that, I can easily take care of it in the evening.

**Comment by Connoropolous** [comment]
I am a bit too fresh with python I think, I will defer, though I’d normally contribute

**Comment by Bearnardd** [comment]
@baskaryan, I have done some further investigation today. In general, when we instantiate the chain object using `chain = create_structured_output_chain(Person, llm, prompt, verbose=False, output_parser=SomeCustomParser())`, the return value of the `run` method can vary depending on the specific `output_parser` being used. So it would be nice to update both the docstring and the type annotations. I guess it would also be beneficial to clarify that the `run` method has the potential to return either a single string or a more complex output when utilized with wrappers like `create_structured_output_chain`. What are your thoughts on this?

**Comment by stakodiak** [comment]
Output parsers can return any type `T` from `parse()`. Would updating the return type of `BaseLLM.run()` to `Any` be too crude? It seems better than keeping an incorrect type hint.

**Comment by Connoropolous** [comment]
I don't have any concern over next steps here, so I'm just going to close this.
