### ISSUE TITLE
Difference between ConversationChain and ConversationalRetrievalChain

### ISSUE THREAD

**Issue by miha-bhaskaran** [langchain-ai/langchain#7885]
### Issue you'd like to raise.

what is the difference between a conversationChain and a conversationalRetrieval chain. I had originially assumed that the conversational retrieval chain would be able to take in documents, input, and memory (which I have gotten to successfully work) and was under the assumption that the conversationChain could not take in our own documents. However, I found a demo online that suggests otherwise. So what exactly is the difference? It was natural to me to use conversationalretrieval chain becuase I had personal documents I wanted to use and I knew that the retrieval chains were made for that.

**Comment by abusufyanvu** [comment]
I am facing an issue during the testing of my chatbot, here is below i attached a screenshot which can show you the exact issue.

![image](https://github.com/langchain-ai/langchain/assets/76678681/40ecc2d1-c704-47a3-8cea-f4e6b3323700)


But when i hit the api again with first small letter 'what' instead of 'What' then it return correct response. 
![image](https://github.com/langchain-ai/langchain/assets/76678681/a10c1940-0b63-4de7-a51b-fe5473c7fdc8)


Could someone please help me identify the exact issue? thanks
