### ISSUE TITLE
DOC: Passing Context to Conversational Chain

### ISSUE THREAD

**Issue by rambabusure** [langchain-ai/langchain#7936]
### Issue with current documentation:

We don't have enough documentation Conversational chain and found only documentation relates conversational retrieval chain. We are looking for separating the  retriever functionality. Please provide some examples on passing context (lang chain documents ) to conversational chain

**Comment by guillaumedelande** [comment]
From the docs, I understand it's the opposite than what is being explained above in the text (code is correct though):
- ```combine_docs_chain```: "The chain used to combine any retrieved documents"
- ```question_generator```: "The chain used to generate a new question for the sake of retrieval. This chain will take in the current question (with variable question) and any chat history (with variable chat_history) and will produce a new standalone question to be used later on."

So the ```question_generator``` creates a standalone question, that is passed to the retriever, and then the ```combine_docs_chain``` is used to combine the returned docs/chunks using one of the methods (stuff, rerank, map_reduce,...)


Regarding the original question, it is indeed not always clear what's happening in the background. You can still find some details about the chain(s) yourself by passing ```qa.__dict__``` and looking at how it was initialized (assuming ```qa``` is the name of the ```ConversationalRetrievalChain``` object).

source: https://api.python.langchain.com/en/latest/chains/langchain.chains.conversational_retrieval.base.BaseConversationalRetrievalChain.html?highlight=combine_docs_chain#langchain.chains.conversational_retrieval.base.BaseConversationalRetrievalChain.combine_docs_chain

**Comment by maximiliancw** [comment]
Hi all,

to me, this is still unclear. Mostly, because the example provided by @dosubot and the docstrings seems to be misleading about to things:

1. The control flow should be different, as explained by @guillaumedelande 
2. The `combine_docs_chain = StuffDocumentsChain(**...**)` is very confusing. `StuffDocumentsChain.__init__` expects the `llm_chain` to be set, but if I adjust the control flow and pass `question_generator_chain` to `StuffDocumentsChain.__init__`, the following error is being raised:
```
pydantic.v1.error_wrappers.ValidationError: 1 validation error for StuffDocumentsChain
__root__
  document_variable_name must be provided if there are multiple llm_chain_variables (type=value_error)
```

I feel like the docstrings should provide a plug-and-play example. That would be great!
