### ISSUE TITLE
Issue:  Langsmith running using local docker containers, roadmap, local model support?

### ISSUE THREAD

**Issue by GMartin-dev** [langchain-ai/langchain#8052]
Hi! I have been using langmith on on local env using docker.
Is there a roadmap for continue supporting that? 
is langsmith going to be totally independent non-opensource per se?
Asking this because I can't really use the public langsmith service due to NDA, and I also have some issues that i'm happy to help fixing. Like I did with my other langchain contributions.
But since langsmith is not public I guess there is no workflow for contribution or bugfix?
Current i'm using langchain with local open source models, langsmith works great but playground won't work, my guess this is hardcoded to use OpenAI or something like that.

**Comment by hinthornw** [comment]
Hi @GMartin-dev, thanks for reaching out! And thanks for the interest. Tl;dr - email us at support@langchain.com for information on self-hosting.

The playground uses the LangChainJS package to run and we're adding more support slowly but currently only have Anthropic, OpenAI, and (in flight) Replicate support.

More expansive self-hosting support is something we are discussing on a case by case basis so we don't become too encumbered while the platform is still in early alpha. The hosted version has the most/best/earliest-access to features since we can be continuously delivering there, but we are slowly starting to offer self-hosting support for larger&faster companies with privacy concerns.

The LangSmith platform itself is not open source. We want to have a very clear distinction/separation between the open-source, community-owned LangChain packages and any other services or projects that LangChain, the company, builds to sustain the core development team so that we can continue to contribute to and grow the ecosystem in the long-term. I think this is the only way we can be good stewards of this project.

We're working to improve LangSmith's issue tracking/ticketing process, etc. to help us better prioritize issues such as this one as well

**Comment by GMartin-dev** [comment]
Thanks for your response!

**Comment by gsgalloway** [comment]
Hi! What's the latest for learning about self-hosting LangSmith? (email to support@langchain.com seems to bounce)

**Comment by hinthornw** [comment]
@gsgalloway support@langchain.dev ! 

We should set up that account too though..
