### ISSUE TITLE
Supporting Multiple Schemas for SQL Query Generation in Databricks

### ISSUE THREAD

**Issue by GuptaPurujit** [langchain-ai/langchain#8167]
### Feature request

There might be scenarios where transformations and joins will need to be applied on tables from different schemas but currently, the code only supports a single schema query structure.

### Motivation

I am working on Databricks Unity Catalog Query Assistant feature for a Product and need this change for the same, there are business scenarios where multiple schemas will need to be accessed to make complicated business rules to be applied.

### Your contribution

I can make the PR for this change, I have identified the code changes required

**Comment by hagope** [comment]
That sounds useful but may be tricky because there are `include_tables` and `ignore_tables` list parameters which may require different data structure, perhaps you could parse `schema.table` in the params and ignore the schema param? One possible workaround is the create a view layer in databricks and add the tables there.
