### ISSUE TITLE
Issue: Pinecone retriever with Cosine Similarity is treated like Cosine Distance

### ISSUE THREAD

**Issue by olegshirokikh** [langchain-ai/langchain#8207]
### Issue you'd like to raise.

When using document search from the existing Pinecone index that was created using Cosine **Similarity** in the `ConversationalRetrievalChain`,  the `score_theshold` would eliminate most relevant documents instead of least relevant ones because the _similarity_ metric will be converted to _distance_.

In [_select_relevance_score_fn](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/pinecone.py#L172) it calls the [_cosine_relevance_score_fn](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/base.py#L169) - which converts the similarity returned from Pinecone search to distance.

Then, [filtering the documents](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/base.py#L266) based on the `score_threshold` eliminates the most relevant documents instead of least relevant ones.

### Suggestion:

Pinecone subclass should override the `_cosine_relevance_score_fn` to preserve the similarity, since it is what originally comes back from the Pinecone similarity search.

**Comment by ruiramos** [comment]
I think this analysis is mostly correct - when using cosine distance pinecone returns a [-1, 1] score where higher is better [according to the docs](https://docs.pinecone.io/docs/indexes#distance-metrics) (in practice though I could never simulate negative values).
Seems that it could be enough to cap negative values at 0 and otherwise return what's returned from pinecone.
