### ISSUE TITLE
Arbitrary code execution in LLMMathChain

### ISSUE THREAD

**Issue by jan-kubena** [langchain-ai/langchain#8363]
### System Info

Langchain version: 0.0.244
Numexpr version: 2.8.4
Python version: 3.10.11

### Who can help?

@hwchase17 @vowelparrot 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Numexpr's evaluate function that Langchain uses [here](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/llm_math/base.py#L80) in the LLMMathChain is susceptible to arbitrary code execution with eval in the latest released version. See this [issue](https://github.com/pydata/numexpr/issues/442) where PoC for numexpr's evaluate is also provided.

This vulnerability allows an arbitrary code execution, that is to run code and commands on target machine, via LLMMathChain's run method with the right prompt. I'd like to ask the Langchain's maintainers to confirm if they want a full PoC with Langchain posted here publicly.

### Expected behavior

Numerical expressions should be evaluated securely so as to not allow code execution.

**Comment by montyevans** [comment]
@hinthornw As an alternative, we could use `sympy.sympify`? It's a common alternative to `eval` / `numexpr` (see this thread on vulnerabilities in [numexpr](https://stackoverflow.com/questions/10076300/python-using-sympy-sympify-to-perform-a-safe-eval-on-mathematical-functions). As well as avoiding that vulnerability, `sympy` also supports a much larger range of mathematical operations (i.e. rounding, factorials, etc.) and is about 10x as common as `numexpr` (as measured by github stars), so I'd guess its easier for an LLM to generate syntactically correct input (in fact, I spent about 10mins trying to get GPT-3 to generate a mathematical input that `sympy` *couldn't* process, and failed).

I was testing some multi-step QA workflows inspired by a Langchain multi-step agent QA [workflow](https://python.langchain.com/docs/modules/agents/how_to/intermediate_steps), and was using the `llm-math` tool in an Agent chain, with prompts like: "Who is Zoe Saldana's partner? What is their current age raised to the 0.43 power, rounded to 3sf?".

This would cause `numexpr` to throw an error, since the chain would try and fail to pass it some kind of rounding instruction.  This also happens with the factorial function in #3071.

Happy to attach some examples / create a PR to scope out the replacement if people agree. It's what I've been using locally and it works great!

**Comment by hinthornw** [comment]
That makes sense to me. I'd be happy to review a PR! Thank you for being proactive about this!

**Comment by jan-kubena** [comment]
I'd just like to point out that there still needs to be validation because sympy.sympify uses eval and shouldn't be used on unsanitized input as per official [docs](https://docs.sympy.org/latest/modules/core.html#module-sympy.core.sympify). I think it could also be worth looking at [this](https://github.com/langchain-ai/langchain/pull/1134) langchain PR that implemented sympy in RestrictedPython as an inspiration.

**Comment by montyevans** [comment]
Ah damn, yeah I missed that: was foolishly going off the StackOverflow thread and a memory of a still-unresolved effort within [Sympify](https://github.com/sympy/sympy/issues/10805) to remove eval / add a safe-mode.

`sympify` still offers a lot more functionality than `numexpr`, so I'd still be in favour of swapping anyway, but agree that there aren't any extra security benefits vs. `numexpr` on the eval front.

**Comment by montyevans** [comment]
@hinthornw [PR here](https://github.com/langchain-ai/langchain/pull/8627/files)

**Comment by tabdunabi** [comment]
Hi @hinthornw, Any ETA on resolving this issue?
Thanks

**Comment by elmegatan26** [comment]
This vulnerability is getting flagged by InfoSec teams. Any idea on when the update is being released?

**Comment by eyurtsev** [comment]
@elmegatan26 , @tabdunabi , @jan-kubena , numexpr is now an optional dependency, we've also added a constraint to specify that code only works with >=2.8.6 (which has input sanitization).

* Is this enough to address concerns flagged by InfoSec teams?
* Also do you mind sharing if you're using LLMathChain yourself and if so which mathematical operations do you rely on?

**Comment by tabdunabi** [comment]
@eyurtsev, for our use case, we do not use `LLMathChain`, but our security scans detect the `numexpr` vulnerability. This is a critical issue for us and blocker to publish our solutions, used by our customers. If making `numexpr` optional (not installed by default with `LangChian`), then this is enough for us.

**Comment by elmegatan26** [comment]
@eyurtsev We are not using LLMathChain but similar to @tabdunabi the vulnerability is automatically detected and flagged. Example: https://security.snyk.io/package/pip/langchain and https://security.snyk.io/package/pip/langchain/0.0.306

**Comment by tabdunabi** [comment]
@eyurtsev just installed `v0.0.308` (with optional `numexpr`), but `python-pipaudit` still reports the vulnerability. It seems the CVE database still has it as a dependency. Anything can be done from your side to update the database?

**Comment by eyurtsev** [comment]
@tabdunabi we're taking a look. 

@elmegatan26  @tabdunabi  Are the [other CVEs](https://security.snyk.io/package/pip/langchain/0.0.306) a blocker for you right now?

**Comment by tabdunabi** [comment]
Yes @eyurtsev they are blockers. Interestingly, `python-pipaudit` did not report https://security.snyk.io/vuln/SNYK-PYTHON-LANGCHAIN-5850009 and https://security.snyk.io/vuln/SNYK-PYTHON-LANGCHAIN-5843727. `safety` only reported https://security.snyk.io/vuln/SNYK-PYTHON-LANGCHAIN-5843727.

**Comment by elmegatan26** [comment]
@eyurtsev Yes, any CVE ranked High or Critical is a blocker. Any vulnerabilities found by most infosec teams are flagged and Devs are required to patch or prove the issue is not exploitable.

**Comment by dvirginz** [comment]
Hi everyone,

Thank you for opening the issue.

Just to clarify the status: 
Is there any version or installation of Langchain that doesn't currently contain high or critical CVEs?

**Comment by eyurtsev** [comment]
@tabdunabi Information about LLMathChain should now be reflected.

@dvirginz Not at the moment. We're working on addressing all the CVEs. 

* https://security.snyk.io/vuln/SNYK-PYTHON-LANGCHAIN-5850009 -- will be resolved next week (https://github.com/langchain-ai/langchain/discussions/11352) 
* https://security.snyk.io/vuln/SNYK-PYTHON-LANGCHAIN-5843727 -- will be resolved over the next few weeks. This CVE stems from a python ast repl tool used by some agents. You're at risk if your code uses this tool directly or else indirectlty via an agent that relies on it.

**Comment by dvirginz** [comment]
Hi!

Thank you for the update and detailed response.

We look forward to a solution, as it will help us a lot.

Message ID: ***@***.***>
>
ᐧ

**Comment by tabdunabi** [comment]
hi @eyurtsev, first apologies for pining you again. We are delaying our release for the CVEs to be patched. 

I see https://security.snyk.io/vuln/SNYK-PYTHON-LANGCHAIN-5850009  has been patched in `v0.0.312` (PR #10252 ). 

Any chance you can accelerate PR #5640, referenced in issue #7700  as providing a fix.

**Comment by dvirginz** [comment]
If we aren't using agents or LLMMathChain, is there a clear version we can already use?

**Comment by tabdunabi** [comment]
Thank you @eyurtsev for the update.

Currently, we are not using LangChain agents. However, our build pipeline fails because of any security vulnerabilities in the libraries shipped with our solutions. So, even though we are not using LangChain agents, we need to go through a formal approval process with our security team, and prove the vulnerable code is not actually used by our solutions, to be able to get an exception to release.  Additionally, once we publish our code on GitHub, GitHub Dependabot will flag these security vulnerabilities, and we need to address auto-cut tickets for our team. 

So, it would be much easier, and safer, to ship code with zero security vulnerabilities in downstream dependencies.

**Comment by eyurtsev** [comment]
Targeting end of month 10/28 (will announce in a bit with expected changes) to resolve the CVE to allow existing users to migrate. In the meantime, are you able to fork and remove affected code?

**Comment by tabdunabi** [comment]
Thank you @eyurtsev!. 
Creating a fork is not an option for us. We want our customers to be able to build our code by themselves using published libraries, available on Pypi/NPM.  We do not want to maintain forks of external libraries.

**Comment by eyurtsev** [comment]
https://github.com/langchain-ai/langchain/discussions/11680 -- announcement

**Comment by eyurtsev** [comment]
Python AST tool CVE was resolved here: https://github.com/langchain-ai/langchain/pull/12427 cc @tabdunabi / @dvirginz 

(The original CVE for LLMathChain was resolved a while back -- closing this issue.)

**Comment by tabdunabi** [comment]
Thank you @eyurtsev !. We will immediately upgrade LangChain version, used by our code,  to `v0.0.325`

**Comment by dvirginz** [comment]
Thank you. It seems that Snyk still identifies 1 high-risk CVE in
LangChain. Any thoughts? Thanks.

https://security.snyk.io/package/pip/langchain


בתאריך יום ו׳, 27 באוק׳ 2023 ב-22:18 מאת Tarek Abdunabi <
***@***.***>:

**Comment by eyurtsev** [comment]
@dvirginz that's the CVE that got patched with this release. It can take up to several days for the CVE to information to be updated in the relevant databases.

**Comment by mschirmer84** [comment]
Can this [CVE-2023-39631] (http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-39631) be closed off with the above fix?

**Comment by eyurtsev** [comment]
That CVE was resolved as well a while back: https://github.com/advisories/GHSA-f73w-4m7g-ch9x

Locking conversation
