### ISSUE TITLE
Quality of answers gets drastically bad with longer chains in Langchain

### ISSUE THREAD

**Issue by moayadeldin** [langchain-ai/langchain#8871]
I think most of the people who works with Langchain in building products or automating stuff noticed how bad the quality of answers degrades when you ask multiple of questions using the same chain (e.g: the chain gets longer). It gets to answer the first 2 or 3 questions right then it may hallucinate returning a wrong answer, it may fail to answer your question or even crash regardless of the GPT model used.

Is there a way anyone found in order to optimize this? One way I always try is to prompt engineering things but it doesn't help as much.

**Comment by wnmurphy** [comment]
I'm not seeing any degradation with a chat model + history of 100 messages, for instance. Post your prompt here?

**Comment by moayadeldin** [comment]
> I'm not seeing any degradation with a chat model + history of 100 messages, for instance. Post your prompt here?

Degradation occurs while usually using a GPT-3.5 models either being for example gpt-3.5-turbo or text-davinci-003.

The prompt I send is as follows:

        prompt = f'''

        Have a conversation with a human, Answer step by step and the history of the messages is critical and very important to use. The user is expected to ask you questions that you will need to use the information you had from the previous answers. For example if the user asked you about the name of the a person, he may asks you another question on that person based on chat history so take care.
        Consider the uploaded pandas data, Begin!
        chat history: {self.chat_history}
        \nQUESTION: {query}
        \nAI RESPONSE HERE:
            '''

**Comment by wnmurphy** [comment]
The prompt has a lot of ambiguity. If I can make some suggestions, you could try:

Delete `Have a conversation with a human`. Just start with your instruction.

`Answer step by step and the history of the messages is critical and very important to use.` >
`Check the chat history for relevant information before responding.`

`The user is expected to ask you questions that you will need to use the information you had from the previous answers.`
You can probably either delete this, since it will already see its prior answers in the history.

`For example if the user asked you about the name of the a person, he may asks you another question on that person based on chat history so take care.`
You can probably remove this entirely. Also, the model doesn't understand what "take care" means.

Maybe try:
```
# INSTRUCTION
Answer a question about the pandas data.
Check the chat history for relevant information before responding.

# CHAT HISTORY
{self.chat_history}

# QUESTION
{query}

# RESPONSE
```

If you turn on `verbose=True`, are you injecting the entire pandas file into the chat history with each query? That could make the input massive, and I imagine you'd exceed your model's context window quickly.
