### ISSUE TITLE
Add support  HuggingFace Inference Endpoint for embeddings

### ISSUE THREAD

**Issue by axiom-of-choice** [langchain-ai/langchain#9181]
### Feature request

https://huggingface.co/inference-endpoints

### Motivation

We do not have support for HuggingFace Inference endpoints for tasks like embeddings and must be easy to implement inheriting the class from Embeddings base class

`InferenceEndpointHuggingFaceEmbeddings(Embeddings):` with only 

`self.endpoint_name = endpoint_name
        self.api_token = api_token`

### Your contribution

I could submit a PR to this issue since I've created a class for this

**Comment by axiom-of-choice** [comment]
Not really. HuggingFaceEmbeddings as you said only support sentence-transformer (basically running in local the embedding model) but the idea is trying to replicate the class of HuggingFaceendpoint (That does not support embedding)
https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/huggingface_endpoint.py

I have used HF Endpoints for embeddings to be used as an API for multiple services

**Comment by kteppris** [comment]
Yes, I think we are talking about two different things. While you are referring to [`HuggingFaceEmbeddings`](https://github.com/langchain-ai/langchain/blob/6bedfdf25aed14c87e18daebcc4dee4ccb7f777c/libs/langchain/langchain/embeddings/huggingface.py#L19), I was talking about [`HuggingFaceHubEmbeddings` ](https://github.com/langchain-ai/langchain/blob/6bedfdf25aed14c87e18daebcc4dee4ccb7f777c/libs/langchain/langchain/embeddings/huggingface_hub.py#L11). This Hub class does provide the possibility to use Huggingface Inference as Embeddings, just only the sentence-transformer models. They dont run lucally than but via the HG API as imported as following:
 
[from huggingface_hub.inference_api import InferenceApi]( https://github.com/langchain-ai/langchain/blob/6bedfdf25aed14c87e18daebcc4dee4ccb7f777c/libs/langchain/langchain/embeddings/huggingface_hub.py#L52C18-L52C47)

If you are saying though that you want to replicate the [`HuggingFaceEndpoint`](https://github.com/langchain-ai/langchain/blob/9666e752b1610cd6bbd4407aef3dc52f6db60d25/libs/langchain/langchain/llms/huggingface_endpoint.py#L14) then indeed my pointing to the Hub class was not correct, as the Endpoint class is using Huggingface Endpoints instead of inference:

[`from huggingface_hub.hf_api import HfApi`](https://github.com/langchain-ai/langchain/blob/6bedfdf25aed14c87e18daebcc4dee4ccb7f777c/libs/langchain/langchain/embeddings/huggingface_hub.py#L52C18-L52C47)

That indeed is missing.

**Comment by zaddy6** [comment]
will this be implemented?

**Comment by dmitryrPlanner5D** [comment]
There is a HuggingFaceInferenceAPIEmbeddings class for using publicly available hugging face endpoints. It contains hardcoded _api_url property with public endpoints url. To support protected huggingface endpoints we need to replace this url with custom one.

I suggest to make an extra BaseModel field `api_url: Optional[str] = None` and in `embed_documents` function instead of posting to `self._api_url` post to `self.api_url or self._api_url`. That way owners of protected endpoint will be able to use it using the same class.

I would also rename `self._api_url` -> `self._default_api_url` to avoid confusion, but I am not sure, is it is ok to change protected field name.
