### ISSUE TITLE
Issue: openai.error.PermissionError: You are not allowed to generate embeddings from this model

### ISSUE THREAD

**Issue by JanHorcicka** [langchain-ai/langchain#9270]
### Issue you'd like to raise.

I have an issue when trying to set 'gpt-3.5-turbo' as a model to create embeddings.

When using the 'gpt-3.5-turbo' to create LLM, everything works fine:

`llm = OpenAI(model_name='gpt-3.5-turbo', temperature=0, openai_api_key=OPENAI_API_KEY, max_tokens=512)`

Also creating embeddings without specifying a model works fine:
`embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)`

But when I try to use 'gpt-3.5-turbo' for embeddings, I get the following error: 
`embeddings = OpenAIEmbeddings(model='gpt-3.5-turbo', openai_api_key=OPENAI_API_KEY)`

Error:
_openai.error.PermissionError: You are not allowed to generate embeddings from this model_

This seems weird to me since I have just used the same model to create LLM. So I have access to it and should be able to use it. Unless creation of embeddings and LLM differs somehow.

Can somebody please advise?

**Comment by m-movahhedinia** [comment]
I have the same issue. I have it with other openai models too. I think the issue is with langchain. I changed my langchain to version 0.0.172 and it worked fine with all the models. I'm guessing that there is a way to get around this, given how far back I had to go for it to work. But I have not been able to find it yet. The docs are of no use either. In fact, what is in the docs is lacking the details and at times adds to the confusion. I would appreciate it if someone can share a solution to this.

**Comment by JanHorcicka** [comment]
Thank you all for answers. I would just like to point out that I didn't have this issue when using `langchain==0.0.168`. This error started appearing after I updated to a higher version (I have `langchain==0.0.232`). Which is weird. :)

**Comment by JJim180730** [comment]
I have the same issue also, have you found the solution for this?  my version is 325

**Comment by m-movahhedinia** [comment]
> Thank you all for answers. I would just like to point out that I didn't have this issue when using `langchain==0.0.168`. This error started appearing after I updated to a higher version (I have `langchain==0.0.232`). Which is weird. :)

The reason you were not seeing it before is that it was hard coded in the earlier versions. Meaning it didn't matter whether you passed anything to it or not as it was not using the value you were giving it. In the newer versions this bug was fixed. So it will consider the argument you pass to it.
Again, the problem is a limitation from OpenAI. The embedding models are different from the classification or generation models. You need to either pass the name of one of their embedding models or leave it blank. In which case it will default to the best embedding model.

**Comment by lauraparra28** [comment]
I have the same issue also, `langchain==0.0.232`. Have you found the solution for this?

**Comment by JanHorcicka** [comment]
> I have the same issue also, `langchain==0.0.232`. Have you found the solution for this?

I just don't specify the model name and it works.

```
embeddings = OpenAIEmbeddings()
```

**Comment by m-movahhedinia** [comment]
@lauraparra28 @JanHorcicka 
When you don't pass the model it will default to `text-embedding-ada-002`. If it is all the same to you, I advise going with either one of the newer models. The `text-embedding-3-small` has almost similar performance but is cheaper. The `text-embedding-3-large` has better performance but is more expensive and in my experience very slightly slower.

In either case, you have to use one of the embedding models (one of the mentioned three) to avoid that issue. You can read more about the embedding models in the link I posted earlier.
