### ISSUE TITLE
add tests for notebooks

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langchain#94]
to make sure they are up to date

**Comment by ccurme** [comment]
I looked into a couple ways of doing this. Let me know if you had a preferred method in mind.

One is to add a dependency [nbmake](https://github.com/treebeardtech/nbmake), which is a pytest plugin that lets you execute notebooks. You can see an implementation here: https://github.com/hwchase17/langchain/compare/master...ccurme:langchain:cc/test_notebooks

The pro is that this is a simple solution built for this use-case. You can list all the notebooks you want to test, or use `--ignore` to exclude certain notebooks.

One con is that the error handling looked cumbersome to me. If you expect a specific error to be raised, for example, you need to add metadata to cells in the notebook JSON, which can get overwritten. I added an example on that branch.

Another option is to use [nbclient](https://github.com/jupyter/nbclient), which is already included in dependencies. I added an example here: https://github.com/hwchase17/langchain/compare/master...ccurme:langchain:cc/test_notebooks_nbclient

This is neat because you can write the tests in python and work with errors programmatically. But it's arguably more complicated than just passing `--nbmake` to pytest.

Let me know if you have thoughts or if I should open a PR.

**Comment by ccurme** [comment]
It doesn't look like many. I think the simplest thing to do is just to use `nbmake` and opt-in to including notebooks in the test. So we'd need to maintain a separate list of notebooks to test; we wouldn't discover them. Does this sound good, or is it important to discover notebooks so that we don't need to maintain a list?

**Comment by hwchase17** [comment]
that sounds perfect!

**Comment by ccurme** [comment]
We can enumerate directories, we can also go the other way and maintain a list of notebooks we *don't* test.
