### ISSUE TITLE
Issue: How can I load text embeddings from a local model?

### ISSUE THREAD

**Issue by dm-2111** [langchain-ai/langchain#9421]
### Issue you'd like to raise.

I do not have access to huggingface.co in my environment, but I do have the Instructor model (hkunlp/instructor-large) saved locally. How do I utilize the langchain function HuggingFaceInstructEmbeddings to point to a local model?

I tried the below code but received an error:

```
from langchain.embeddings import HuggingFaceInstructEmbeddings

model_name = "<local_filepath>/hkunlp/instructor-large"
model_kwargs = {'device': 'cpu'}
encode_kwargs = {'normalize_embeddings': True}
hf = HuggingFaceInstructEmbeddings(
    model_name=model_name,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)

embeddings = HuggingFaceInstructEmbeddings(
    query_instruction="Represent the query for retrieval: "
)


```
Error:
HfHubHTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/models/hkunlp/instructor-large

**Comment by dmyoung9** [comment]
Based on #2667 (thanks @dosu-beta[bot] 🙏), it looks like in order for it to recognize that you're using a local model, you just need to give it the local *path*, extension and all.

**Comment by MiCodes2** [comment]
I am facing similar issue. I am using LangChain 0.15. I can't upgrade it to latest version due to compatibility issues with other libraries.
I am using following code:
# Load the locally saved SentenceTransformer model
modelPath = r"******\MiniLM"
model = SentenceTransformer(modelPath)

# Set the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Initialize the embeddings
embeddings = HuggingFaceEmbeddings(model=model, model_kwargs={'device': device})
