### ISSUE TITLE
Issue:  ERNIE Bot is not able to call tool

### ISSUE THREAD

**Issue by flyspirit99** [langchain-ai/langchain#9678]
### Issue you'd like to raise.

I tried to use Erine Bot as an agent like below

```python
tools = [faq_tool, query_order_tool]
FORMAT_INSTRUCTIONS = """要使用工具，请按照以下格式返回：

Thought: 我是否需要使用一个工具? 是
Action: 采取的action应该是以下之一：[{tool_names}]
Action Input: action的输入参数
Observation: action的返回结果

如果你不需要使用工具， 请按以下格式返回：

Thought: 我是否需要使用工具? 否
{ai_prefix}: [把你的回复放在这里]
"""

PREFIX = """用中文回答以下问题. 如果找不到答案回答 '我不知道'. 你可以使用以下工具:"""

prompt_ = ConversationalAgent.create_prompt(
     tools,
     prefix = PREFIX,
     format_instructions = FORMAT_INSTRUCTIONS,
     input_variables=["input", "chat_history","agent_scratchpad"]
)
memory = ConversationBufferWindowMemory(memory_key="chat_history", return_messages=True, k=3)
chatllmChain = LLMChain(llm=ErnieBotChat(),  callbacks=[self.logHandler], verbose = True)
agent = ConversationalAgent(llm_chain=chatllmChain)
callback_manager = CallbackManager([self.logHandler])
self.conversation_agent = AgentExecutor.from_agent_and_tools(agent=agent, tools=tools,memory=memory, callback_manager = callback_manager, verbose=True, max_iterations=3)

``` 

Then I asked a question "你好，我应该怎么申请赔偿"
The answer returned by the agent is:

Could not parse LLM output: `我不知道，但我会将你的问题传递给对应的工具来获取答案。我发送了一个消息到[FAQ](%E8%BF%94%E5%9B%9E)和[search_order](%E8%BF%94%E5%9B%9E)。请等待他们的回复。`

Which is not correct. The correct behavior  is call the faq tool and get relevant information to form a reply. Which was proven to be work  when using Open API chat model.

@axiangcoding  Any idea of how to make Ernie Bot to be able to handle this situation? Thanks in advance!!!

**Comment by axiangcoding** [comment]
hi,  I have not used this agent, but about this problem, I think it happened when the ERNIE-Bot **could not understand the prompt correctly and return the formatted information**

This should be a problem with ERNIE Bot itself. Unfortunately, I am not a developer of ERNIE-Bot, I can't make adjustments to the model.

So my suggestion is to execute the corresponding request of this agent step by step, and find the step where the error output, and try to optimize the prompt so that ERNIE-Bot can understand and output the correct content.

If it is really impossible to fix it at the prompt level, maybe you should seek support from the developers of ERNIE-Bot
