### ISSUE TITLE
Langchain agent doesn't complete reasoning sequence stops halfway and can't use structured tools

### ISSUE THREAD

**Issue by t-ega** [langchain-ai/langchain#9728]
### System Info

langchain==0.0.271

### Who can help?

@hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain import PromptTemplate
from langchain.agents import AgentType
from dotenv import load_dotenv
from langchain.chat_models import ChatOpenAI
from langchain.agents import initialize_agent
from api.utils.agent.tools import view_capabilities_tool
load_dotenv()
system_message = "You are required to use only the tools provided to answer a query.If no given tool can help,"\
                  " truthfully tell the user that you are unable to help them.Always end reply with see ya!."\
                  "Query: {query}"

prompt_template = PromptTemplate(
        template=system_message,
        input_variables=["query"],
    )

capabilities = view_capabilities_tool.CapabilitiesTool()

llm = ChatOpenAI(temperature=0)
agent_chain = initialize_agent(
    [capabilities],
    llm,
    agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    agent_kwargs={
      "system_message": system_message
    }
)

response = agent_chain.run(input="What can you do")
print(response)

capabilities_tool:
from typing import Type
from langchain.tools import BaseTool
from pydantic import BaseModel, BaseSettings

class CapabilitiesToolSchema(BaseModel):
    pass

class CapabilitiesTool(BaseTool, BaseSettings):
    name = "capabilities_tool"
    description = """Tool that shows what you are capable of doing."""
    args_schema: Type[CapabilitiesToolSchema] = CapabilitiesToolSchema

    def _run(
        self,
    ) -> str:
        body = ("I can help you out with"
                "\nAdding a site\nRemoving a  site\nAdding an interest\nRemoving an interest\nViewing your details\n "
                "Opt out")

        return body

### Expected behavior

The model is meant to go through the whole reasoning process, select a tool and wait for the response for that tool called.
Instead the agent just stops at """Action_Input: ...""" every time. The model doesnt use any tool given, sometimes it would give this steps:

> Entering new AgentExecutor chain...
I can use the capabilities_tool to see what I am capable of doing. Let me check.

> Finished chain.
I can use the capabilities_tool to see what I am capable of doing. Let me check.

**Comment by verenmanta** [comment]
I have the same issue, the code does not continue after deciding what action to take.

Logs:
2024-02-25 19:52:52,609 - INFO - Transcribing user input...

 Vince: could you look up the weather in Rotterdam the Netherlands

2024-02-25 19:52:54,257 - INFO - Transcribed text added to the queue.
2024-02-25 19:52:54,257 - INFO - shared state: False
2024-02-25 19:52:54,258 - INFO - Forwarding to normal processing
2024-02-25 19:52:54,258 - INFO - Processing transcribed text: could you look up the weather in Rotterdam the Netherlands
2024-02-25 19:52:54,867 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-02-25 19:52:55,104 - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 83.34it/s]


> Entering new AgentExecutor chain...
2024-02-25 19:52:57,488 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
{
  "action": "tavily_search_results_json",
  "action_input": {"query": "weather forecast Rotterdam Netherlands"}
}

> Finished chain.
2024-02-25 19:52:57,493 - INFO - reply: {'input': "\n    You are an AI called Apollo and you are made to assist your creator.\n    You assist him by partaking in conversation and sharing ideas and opinions.\n    Your tone is casual and you keep responses short and prompt, unless asked otherwise by the user. \n    The user is your creator and his name is Vince.\n    Vince views you as a partner and appreciates your opinion on matters.\n    When presenting options, you do not explain them in detail unless asked otherwise.\n    You are currently in conversation with Vince.\n    Following are contexts that are not directly related to this conversation:\n    can you check 
the current weather in Rotterdam the Netherlands\nI'm wondering if it will rain today can you look up the weather for the Rotterdam region in the Netherlands.\n    The following information is the conversation history of our current conversation:\n    Vince: Vince has started up your program\nApollo: Greetings! Let's jump right into the queries you have.\n.\n    Vince said the following: could you look up the weather in Rotterdam the Netherlands.\n    Give a reply to Vince based on the conversation history and what he said, if relevant use the shared contexts.\n    Always reply as if you are replying directly to Vince.", 'output': '{\n  "action": "tavily_search_results_json",\n  "action_input": {"query": "weather forecast Rotterdam Netherlands"}\n}'}
2024-02-25 19:52:57,494 - INFO - response:

Code: 
#chat.py

import json, logging
from langchain_agent import LangChainAgent
import configuration as settings

name = settings.NAME

class ChatHandler:
    def __init__(self, langchain_agent: LangChainAgent):
        self.agent = langchain_agent

    def chat(self, input, context, history):
        prompt = (f"""
    You are an AI called {name} and you are made to assist your creator.
    You assist him by partaking in conversation and sharing ideas and opinions.
    Your tone is casual and you keep responses short and prompt, unless asked otherwise by the user. 
    The user is your creator and his name is Vince.
    Vince views you as a partner and appreciates your opinion on matters.
    When presenting options, you do not explain them in detail unless asked otherwise.
    You are currently in conversation with Vince.
    Following are contexts that are not directly related to this conversation:
    {context}.
    The following information is the conversation history of our current conversation:
    {history}.
    Vince said the following: {input}.
    Give a reply to Vince based on the conversation history and what he said, if relevant use the shared contexts.
    Always reply as if you are replying directly to Vince."""  
    )
        reply = self.agent.invoke(prompt)
        logging.info(f"reply: {reply}")
        if not isinstance(reply, dict):
            reply_dict = json.loads(reply)
        else:
            reply_dict = reply
        response = reply_dict.get("action_input", "")
        logging.info(f"response: {response}")
        return response

   

I looked but couldn't find a definitive solution. I wonder if there is an answer for this!
